### ISSUE TITLE
deduping command history

### ISSUE THREAD

**Issue by sprynm** [cmderdev/cmder#1027]
Is there a way to make the up/down arrow keys only select unique commands from the history?  This would be a feature for any command line program.

I run one command a lot so recalling an early command requires 10-20 arrow up keys.  This reduces the utility of the history a great deal.

Any way to cycle frequently used commands would be useful.

**Comment by mrRosset** [comment]
If you don't already know it, ctrl + r is going to blow your mind

**Comment by sprynm** [comment]
Thanks @mrRosset, that will be very handy for longer commands.   Still a bunch of extra keys strokes for my work where up+up would be perfect.

**Comment by glucas** [comment]
History is a clink feature -- there are a bunch of questions/feature requests related to history over at https://github.com/mridgers/clink. It does support a bash-style ! to execute commands from history, but you can't currently see the history with command numbers (https://github.com/mridgers/clink/issues/362) so it's of limited use. 

Not an answer to your question but along the lines of the previous suggestion: I re-map C-p to history-search-backward, which allows you to type the first character or two of a command and then search for matching history entries. This results in fewer hits than a full C-r search, since it is just completing what you've typed. I often find a single char and one or two taps of C-p is sufficient to find what I want.

You can customize the shell key bindings by creatnig a clink_inputrc file in your home directory, e.g. with:

    # Use up/down to search history
    C-p: history-search-backward
    C-n: history-search-forward

**Comment by glucas** [comment]
Actually, it looks like clink does have an option to exclude duplicates from history. I think you can put this in your clink_inputrc:

    set history_dupe_mode = 1

That won't affect your existing history file. You can use e.g. awk to strip duplicates from your existing file with something like:

    cd %CMDR_ROOT%\config
    awk '!seen[$0]++' .history > tmp && mv tmp .history

**Comment by Chealer** [comment]
Which shell do you use? GNU Bash offers HISTCONTROL=ignoredups.
