### ISSUE TITLE
~ doesn't work in cmder?

### ISSUE THREAD

**Issue by searene** [cmderdev/cmder#1051]
``` shell
C:\Users\myusername
λ rm ~\Documents\Untitled.png
rm: `/c/Users/myusername' is a directory
```

I'm pretty sure `Untitled.png` exists, but I cannot remove it through the `rm` command.

**Comment by glucas** [comment]
Does it work if you don't use the '~'? If this is a cmd.exe shell then I believe the shell handles the path and doesn't understand the '~'.

**Comment by searene** [comment]
I just tried `rm C:\Users\myusername\Documents\Untitled.png`, which worked.

So this is an issue of `~` instead of `rm`

**Comment by radavis** [comment]
```
λ cd ~
The system cannot find the path specified.
```

ConEmu 160710 [64] {Stable}

**Comment by MartiUK** [comment]
Try using PowerShell.

**Comment by codesboy** [comment]
Try rm -rf /c/Users/myusername

**Comment by glucas** [comment]
So to clarify: Cmder does not interpret shell arguments (like '~'). 

If the underlying shell is cmd.exe then tilde is not supported in paths. If the underlying shell is PowerShell or Bash it will work. 

If you want to use a cmd.exe shell, then one thing you can do is expand the tilde before executing the command. This is supported via tilde-expand, which is mapped to Alt-~ by default. For example:

    c:\Temp
    λ cd ~\bin

before hitting Enter here, you can hit Alt-~, which results in something like:

    c:\Temp
    λ cd c:\home\bin


Cmder provides a bunch of (configurable) key bindings like this. Try Alt-h to see what is available.

**Comment by janschulz** [comment]
I use 

```lua


local function tilde_match (text, f, l)
    if text == '~' then
        clink.add_match(clink.get_env('userprofile'))
        clink.matches_are_files()
        return true
    end
end

clink.register_match_generator(tilde_match, 1)
```

in `<cmderroot>\config\whatever.lua` to get `~<tab>` to expand to my home dir.

**Comment by glucas** [comment]
@janschulz Ah, that's handy! I'm experimenting with handling any path that starts with tilde:

```lua
local function tilde_match (text, f, l)
    if text:sub(1, 1) == '~' then
        clink.add_match(string.gsub(text, "~", clink.get_env('home'), 1))
        clink.matches_are_files()
        return true
    end
end
```

Works OK, I may need to be smarted dealing with trailing slashes and so on.

**Comment by Beej126** [comment]
i had to change the 3 `get_env('home')` to `get_env('userprofile')` on my basic clink install (not using cmder) but otherwise it's an age old dream come true!! thank you thank thank you

for other's coming here for clink only, just tack this (along with the `register_match_generator` call shown in previous comment) onto your clink.lua file in your clink install folder (mine was c:\program files (x86)\clink\0.4.8)

**Comment by elisim** [comment]
I put "tilde_match" function in **cmderroot\config\tilde.lua** but it's not work for me.

I tried:
```
λ cd ~<TAB>
λ cd ~\Documents<TAB>
```

But nothing. I also tried to insert the function into  **cmderroot\vendor\clink.lua** at the end, but it still not working.

**Comment by daxgames** [comment]
Just tested this with latest cmder master branch [build](https://ci.appveyor.com/project/MartiUK/cmder/branch/master/artifacts) that re-enables loading user lua files and it works.

**Comment by DRSDavidSoft** [comment]
Personally, I went the other way and wrote a small batch script to handle `~` in the `cd` command itself natively, instead of replacing it when pressing <kbd>TAB</kbd>.

```batch
@if "%~1"=="/?" (@cd %*)
@set excd=%*
@set excd=%excd:"=%
@if "%excd:~0,1%"=="~" (@set excd=%userprofile%\%excd:~1%)
@if not "%~1"=="/d" (@set excd_param="/d") else (@set excd_param=)
@cd %excd_param% "%excd%"
```

You can save this as `[cmder_root]\config\excd.cmd`, and then you can test it like this:  
(Provided that `%cmder_root\config` is in your PATH, or you call `excd.cmd` directly)

```
λ excd ~\Desktop

C:\Users\David\Desktop
λ
```

Now you can alias it to `cd` instead of using the batch script:
```batch
alias cd=excd $*
```

Or, if the `%cmder_root\config` is not in your path, use it like this:
```batch
alias cd=%cmder_root%\config\excd.cmd $*
```

#### Results:

![tilde-cmder-cd](https://user-images.githubusercontent.com/4673812/94974535-bee70880-051b-11eb-9939-42413afb1beb.png)

It's so satisfying to use!

**Comment by daxgames** [comment]
Very nice.  Maybe it should be included in `%cmder_root%\vendor\bin`. :-)

**Comment by DRSDavidSoft** [comment]
@daxgames Thanks, I was going to make a pull request, but I thought I'd ask people to try it first.  If it's alright, I'll open a PR in the next days :)

**Comment by Beej126** [comment]
very slick... cmder is great... just to overshare, in case y'all haven't tried yet... the new Msft Terminal + Pwsh is pretty good too... tilde works... allowing unc path for current directory is nice... and you haven't lived till you've seen color emojis in your Windows terminal =)

![image](https://user-images.githubusercontent.com/6301228/95027970-73367b00-0651-11eb-98d5-b570423aaec5.png)
