### ISSUE TITLE
Branch hint shows Mercurial instead of Git

### ISSUE THREAD

**Issue by FrankPeters** [cmderdev/cmder#1052]
When I `cd` into a directory which has a Git repository I get the branch name and a suffix `{hg}`. That would suggest it is a Mercurial repository? Which it isn't.

I am running 160724 stable on Windows 10.

**Comment by janschulz** [comment]
The `{hg}` should be replaced [in the last step of building the hg part of the prompt with nothing](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L151-L178). So this suggests that clink (which does the replacements) fails to do that step, but as the git branch name is there, it fails after that step. 

What happens if you put `hg status` or `hg branch` in a terminal?

And: are you on the latest developent version?

**Comment by FrankPeters** [comment]
I am running the stable version indeed.

This is what I get:

``` λ hg status
'hg' is not recognized as an internal or external command,
operable program or batch file.```

So, I don't even have Mercurial active.
