### ISSUE TITLE
Cmder hangs after idling for a few minutes or when clicking above the cursor

### ISSUE THREAD

**Issue by ShimShamSam** [cmderdev/cmder#109]
I've noticed Cmder will hang for about 10 seconds if I let it idle (window not focused) for about 5 minutes. While it is hanging, all keyboard input is queued and finally output all at once when it stops hanging.

I have occasionally experienced this problem even without letting it idle, but it is much more common when another window has been focused for a while.

Windows 8.1
Cmder 1.1.3

_Edit:_ r3Fuze has noted that clicking above the cursor can also trigger the problem. It is possible that they are the same issue and I jumped to conclusions about what could be the cause.

**Comment by koumdros** [comment]
This is happening still whether I sued cmder or plain ConEmu+clink combo. I think it must be taken up with ConEmu developers..

**Comment by sekai92id** [comment]
still happening on me dunno how to fix it

**Comment by wuy3** [comment]
omg I was tearing my hair out trying to find out what was causing this with cmder. I almost dropped cmder because of this issue. You guys should definitely set this off by default. It's probably causing a bunch of newer users to just throw their hands and give up.

Btw. The settings window looks a bit different now than it used to in 2015. This is what it looks like now:

![image](https://user-images.githubusercontent.com/22990763/39898101-2675f58e-546a-11e8-84a8-9bf86d8ebef6.png)

**Comment by Schtrudel** [comment]
THANK YOU! It really drove me crazy. 
Amazing this is still a problem these days.
As the "cool kids" say on Youtube:

2019?
