### ISSUE TITLE
New Tab Startup Directory Option Doesn't Work

### ISSUE THREAD

**Issue by Nick-t-go** [cmderdev/cmder#1097]
There is an option when creating a new tab that says:

"Startup Directory For New Process"

It allows you to pick any directory you want but it still just opens with my root as the base directory in the command line.

**Comment by romansp** [comment]
Come up with the same issue. I guess that happens because of `%USERPROFILE%` in startup task. Managed to fix by following this comment: https://github.com/cmderdev/cmder/issues/91#issuecomment-194005860

**Comment by kibbled** [comment]
@romansp that doesn't really fix the problem, even if I set that to C:\ it will still ignore the directory I specify when opening a new tab. Very disconcerting that such a basic feature is essentially broke and no feedback from this project on multiple issues people have submitted over the last couple months.

**Comment by Artaches** [comment]
Here's a work-around: http://stackoverflow.com/questions/31933766/start-up-cmder-conemu-console-in-a-specific-folder/43836978#43836978

Basically, create a shortcut for ConEmu and change the "Start in:" attribute in the shortcut's properties.

**Comment by AntseN** [comment]
This is not fixed !    
  `-new_console:d:"C:\"` 

Still ignoring any of the path given to it.

**Comment by daxgames** [comment]
@antsen what exactly is not fixed?

If `cmder.exe` is in my path I can type `cmder.exe` from any directory and it will open in that directory.  I can even type `cmder.exe` in the Windows Explorer path bar and it opens in the current directory displayed in Explorer

I can launch `cmder c:\` and it will open in `c:\`

I can click the green + in conemu and specify a startup dir for a new tab there and it also works.

I think the problem is with your cmder tasks config the we provide defaults so for on a new install but never touch again because it becomes yours to managed.

Old versions of cmder had `-new_console:d:"%userprofile%"` in every task.  You need to remove this setting from the tasks in conemu that you use to launch sessions.
