### ISSUE TITLE
Suggestions for tabs, titles, menus, and tasks

### ISSUE THREAD

**Issue by jrmain** [cmderdev/cmder#1138]
I'm a huge fan of cmder, and there's very little about it that I would change, but there are a few minor things...
1. I'd like to see an option to change the window title based on the name of the current task. (Update: ConEmu by default changes the window title to match the tab title, so cmder seems to be overriding this behaviour.)
2. The highlighting of the current tab is kind of hard to see. An option to make the currently-selected tab more obvious would be helpful. (Update: it looks like this would have to be changed in ConEmu).
3. How about an option to have multiple rows of tabs instead of scrolling them horizontally? (Update: it looks like this would have to be changed in ConEmu).
4. Better navigation of the Tasks menu would be helpful. Currently I just get a series of 'More tasks...' 'More tasks...' 'More tasks...' entries. How about submenus or some other kind of grouping? (Update:  ConEmu supports one submenu level, and this works fine in cmder).
5. Minimize to notification area on startup would be nice. (Update: this works fine in ConEmu if the Windows shortcut is set to 'minimized'. It doesn't work for cmder.)
6. An easy way to duplicate a task would save some time. (Update: this was resolved with the task clone feature added to ConEmu recently.)

**Comment by ryantheleach** [comment]
I'd really appreciate the window title being dynamic, it helps with my time tracking software.

https://github.com/cmderdev/cmder/blob/2e77513674f0bd81a0fac52980e922d271d12dc5/launcher/src/CmderLauncher.cpp#L308

I suspect removing the /Title 's being passed into ConEmu would fix this, as if you pass a fixed title to ConEmu it will ignore all dynamic titles.

**Comment by tgice** [comment]
I also would like to see some control over the main window title (not the title that is settable on tabs).

This is important for me mostly because I use [Enso Portable](https://github.com/GChristensen/enso-portable) to switch between windows frequently, and do this based on current window title.  I may have multiple cmder windows open, and if they all have the same title, I can't quickly jump to the one I want, all without coming off the keyboard.

As others have pointed out, this is already doable in ConEmu, so surely it could be done here without too much effort.

Thanks for the product!

**Comment by jrmain** [comment]
Dear Mr. stalebot: please don't close this issue. Some of the problems I reported originally have yet to be resolved.

1. Still a problem.
2. Looks like a ConEmu issue.
3. Looks like a ConEmu issue.
4. No longer a problem once I discovered how to use menu sub-levels.
5. Still a problem.
6. Resolved with a ConEmu change.

**Comment by daxgames** [comment]
@jrmain 

5. Look at the `/x` arg of the latest unreleased [code](https://ci.appveyor.com/project/MartiUK/cmder/builds/24656226/artifacts). 
This allows you to pass conemu args to conemu when launching Cmder it might also help with 1.  Also regarding 1 if conemu does this by default it's probably a setting in conemu that sets this behavior and not Cmder overriding anything since Cmder can't override any Conemu behavior unless Cmder.exe is passing the name of the window as a conemu arg already.

**Comment by jrmain** [comment]
@daxgames - That looks promising for #5. I'll try it. Not sure it will help for #1.

**Comment by daxgames** [comment]
Cmder.exe is passing `/title Cmder` to conemu already so I doubt 1 will be fixed.
