### ISSUE TITLE
many commands failed with build 161022

### ISSUE THREAD

**Issue by haitaoxin** [cmderdev/cmder#1144]
Everything worked fine until I upgraded to build 161022 today. ls command caused error 
"      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0xB00000, BaseAddress 0xB90000, RegionSize 0x16D000, State 0x2000 C:\Program Files (x86)\Git\bin\ls.exe: **\* Couldn't reserve space for cygwin's heap, Win32 error 0"

uname and cat generate similar errors

**Comment by daxgames** [comment]
Upgrading ConEmu is not the same as upgrading Cmder.  Cmder is a compilation of several tools working together to form a whole.

I never upgrade ConEmu when it is a part of Cmder because bad things can happen.  You should be able to do this but I have had bad results doing this so I don't do it any more.

The only way I do this is if building cmder using scripts from the git repo and a new version of conemu is already included.

**Comment by Jackbennett** [comment]
@cmderdev/trusted-contributors Should the conEmu config shipped disable updates? We'll have to do more releases ourselves but also make a mechanism users see if there's newer cmder.

**Comment by Stanzilla** [comment]
as long as there is no proper version check for the whole cmder package, I don't see why we would disable the ConEmu updates. Usually the stable channel of it is actually quite stable.

**Comment by daxgames** [comment]
I am sure you see my comments above.  The times I have upgraded by clicking the button presented by conemu and the issues I have had have made me think it's not a good idea to do it.  Granted I have only tried it 2-3 times but I had issues every time.

You guys may have a different experience though.
