### ISSUE TITLE
Wrong info about config/ConEmu.xml

### ISSUE THREAD

**Issue by borekb** [cmderdev/cmder#1152]
If I'm reading things correctly, since #600 the ConEmu conflig is loaded from `vendor/conemu-maximus5/ConEmu.xml`, not `config/ConEmu.xml`. The config README might be incorrect: https://github.com/cmderdev/cmder/blame/master/config/Readme.md#L14

If someone confirms this, I'll be happy to submit a PR to fix this.

Also related: https://github.com/cmderdev/cmder/issues/695

**Comment by daxgames** [comment]
ConEmu conflig is loaded from vendor/conemu-maximus5/ConEmu.xml, not config/ConEmu.xml on an exist in install.

On a fresh install where cmder has never run the conemu.xml is copied from config/ConEmu.xml to vendor/conemu-maximus5/ConEmu.xml them conemu is launched and loads the config from vendor/conemu-maximus5/ConEmu.xml.

-- start unreleased functionality

The currently unreleased cmder.exe will on an existing install copy vendor/conemu-maximus5/ConEmu.xml to config/user-conemu.xml at launch to maintain a 'copy' of the current conemu config.  So as you make changes via conemu gui they are backed up so they are not lost upon deletion of the vendor/conemu folder.

On a new install/update if vendor/conemu-maximus5/ConEmu.xml does not exist and config/user-conemu.xml does then config/user-conemu.xml will be copied to vendor/conemu-maximus5/ConEmu.xml and used instead of config/conemu.xml.  

The above makes it safe to delete the entire vendor folder and not lose any user config assuming you are not going in an manually editing scripts in this folder.

-- end unreleased functionality

Hopefully this makes sense.

**Comment by borekb** [comment]
Great explanation, thanks. If I were to open a PR for config/README.md, should it be against the `master` or `development` branch?

**Comment by daxgames** [comment]
At this time you could do either.  I think we are still trying to decide which.

**Comment by daxgames** [comment]
Master is where the new config I spoke of above is located.

**Comment by Stanzilla** [comment]
@borekb @daxgames one of you making a PR for that?
