### ISSUE TITLE
Can I have a man command in cmder ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#1199]
I find a lot of Linux command in cmder folder without the man command.
If there is a way to use `man` command in `cmder` ?  I think it should be very useful.

**Comment by zpeller** [comment]
I can see, that this is closed as completed, but I can't seem to find the command (and the man pages) in the latest package. Where can I find it? Thx!

**Comment by DRSDavidSoft** [comment]
This issue is actually closed without completion.  The `man` command is in the scope of `git-for-windows`, not Cmder.

@zpeller If you also can't use `man` in Cmder, please be aware that this is due to `git-for-windows` [not containing the `man` package](https://stackoverflow.com/a/51262580/1454514), and Cmder can't add it, it needs to be done through the `pacman` package manager.

This feels like a great command to have, so you can search for issues (or create a new one) here:

https://github.com/git-for-windows/git

**Comment by kapitanluffy** [comment]
Seems like there are no plans for it in git-for-windows. Is there a way to manually add it instead?

**Comment by DRSDavidSoft** [comment]
@kapitanluffy To be honest, I feel like using something like WSL to Cygwin is better than git-for-windows since it's not complete.

In my opinion there are two feasible options:

1. Option A: **Installing MSYS2 on top of Git for Windows:** Going on this route is a bit tricky but it works.  
   - You can read more about it here: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper  
   - There is also a second guide here: https://www.pascallandau.com/blog/setting-up-git-bash-mingw-msys2-on-windows/
   I believe the man package is included with the default installation.  If not, it's rather easy to do it via the included package manager when you get the MSYS2/MINGW environment working.

   **Note:** You can also manually download and extract the `man` package into the respective required directory for Git for Windows.  I won't go into detail here since this is not related to the Cmder project but rather Git for Windows itself.  I have tested this before in the past, and it works great without any problem.

   If you want native `man` support in Git for Windows, you can always ask them out over their respo's issue tracker, which I've linked in my previous comment above.

2. Option B: **Uninstall Git for Windows** and **Install something else**:
   You can remove the installed git for windows (if any) and use one of the options below.  

   - **Cygwin:** https://www.cygwin.com/install.html  
   Have you wondered what the "MIN" in "MINGW" refers to, of which Git for Windows is based off? The Cygwin project is the fullest GNU project you can experience on Windows without any "minimal" or "subset" mindset being applied to it. (So, Git for Windows is based on MSYS2 which itself is based on Cygwin).

  - **WSL1:** This is Microsoft's flavor of the same idea, like how Cygwin works.  Binaries compiled for the NT kernel, like Cygwin and MSYS2. Here's an unofficial guide: [Install Cmder on Windows 10 with WSL1](https://www.dpoindexter.com/garden/install-cmder-on-win-10-wsl-1/)

  - **WSL2:** This time Microsoft went ahead and made a complete, virtualized Linux environment available on Windows. This is binary compatible with any Linux build (since a real Linux kernel is always running) but it's ultra fast since it's a subsystem that uses their "side-by-side" technology and works like a charm on Windows.
   Here's an unofficial guide: [Setup Cmder with WSL2](https://gist.github.com/ikhsanalatsary/2068a698a56d6b0a4a77a2e469650ed3)

   **Note 1:** You can choose to keep the existing Git for Windows if you can afford the extra space that it takes on your drive, if you do simply make sure that either it's not on your `%PATH%` or if it is, it comes after Cygwin/WSL and not before.

   **Note 2:** If you have downloaded Cmder Mini, it doesn't come with Git for Windows.  In this case, you only need to uninstall Git for Windows if you have installed it separately (mostly uncommon).

  If you have installed Cmder Full, it comes with Git for Windows. You can manually remove it from the `/vendor` directory inside Cmder root, but since we're doing some additional steps in the build process, I think it's better if you backup your current Cmder configuration, remove it entirely and install the mini version.


---

**Conclusion:** As you can see, there are many approaches on how to handle this. I suggest doing your research on what works best for you, and go that route.

Personally I was fed up with the rather in-complete MSYS2/Git for Windows environment.  Even though it's modern and has Windows-specific patches applied to the both of them, I decided against using them as my daily GNU/Linux environment on Windows, and installed Cygwin instead, which is the most complete way you can approach this. You can take a look at WSL and decide if it works for you.

The joys of working/developing on a Windows environment 😄
