### ISSUE TITLE
Command History not work in windows 10

### ISSUE THREAD

**Issue by saostad** [cmderdev/cmder#1210]
when I aciveated Settings > Startup > "Auto save/restore opened tabs" it just remember the address and I need to type all the commands again.
No History!

**Comment by daxgames** [comment]
History for cmder cmd.exe sessions is setup by execution of the on init.bat at session start.  This does not happen when restoring saved sessions, therefore it is working as expected.

**Comment by saostad** [comment]
So, How can I have history of commands?

**Comment by saostad** [comment]
I install Clinck and problem solved! 
http://mridgers.github.io/clink/

do you have any other solution ?

**Comment by daxgames** [comment]
Clink is included in cmder and provides history if init.bat is run probably because it is supposed to be portable.  I assume installing clink with the autorun option is running clink for all executions of cmd.exewhich is not portable..

**Comment by daxgames** [comment]
The question I would have now is where is your history being saved?  In installed clink default location, in %cmder_root%\config\history, or one or the other depending on how the session is started.

**Comment by saostad** [comment]
I am sorry, I am not expert in this software and concepts, I just installed on my computer, I don't know what is answer!

**Comment by james0r** [comment]
For me the problem was I had installed the portable directory in /Program Files/ and my user didn't have write access to the /config/.history file.

**Comment by andre-alck** [comment]
> For me the problem was I had installed the portable directory in /Program Files/ and my user didn't have write access to the /config/.history file.
> 
> To fix, I just moved the cmder directory to C:\Cmder where it can write to without elevated permissions.

It worked for me! Thank you so much!

**Comment by shwaindog** [comment]
If you give the config/clink_history file Modify and Write for "Users" in file properties security it should work even without needing to restart cmder.

**Comment by chrisant996** [comment]
> If you give the config/clink_history file Modify and Write for "Users" in file properties security it should work even without needing to restart cmder.

That won't be enough -- you have to give write permission to the whole Clink profile directory.  But it's a very bad idea to put the Clink profile directory in Program Files.  That's not where it belongs, at all.

(I'm the author of Clink.)

**Comment by DRSDavidSoft** [comment]
@chrisant996 I always install `Cmder` to `Program Files` in my workplace, and just give the permissions to the either `Users` group or the individual users on the machine.

This works very well for single-user machines (regardless of potential security implications), and has the downside of the shared configurations/history for shared machines with multiple users (which is fine in our company's case since we enjoy the shared history between different user accounts).

Maybe in later versions of Cmder we can install the binaries to `Program Files` while giving the users the option to save configurations in `AppData` (which is what is supposed to happen since it's under their user profile directory) through an installer.

This will only be required for non-portable installations, since Cmder originally grew only as a portable package, which meant the binary files and the configuration files were meant to be stored in close proximity of each other in a single folder.

**Comment by daxgames** [comment]
@DRSDavidSoft No Cmder is portable and always will be by default.  There is already an option to do a non portable install.

**Comment by daxgames** [comment]
There is absolutely no reason to install it in Progrm Files ESPECIALLY on a single user machine.

**Comment by chrisant996** [comment]
> @chrisant996 I always install `Cmder` to `Program Files` in my workplace, and just give the permissions to the either `Users` group or the individual users on the machine.
> 
> This works very well for single-user machines (regardless of potential security implications), 

The security implications are why not to do that.

**Comment by daxgames** [comment]
Exactly

**Comment by DRSDavidSoft** [comment]
Good points!

I believe the idealistic approach would be to release two packages;
1. The "portable" ones as we do now, available in `.zip` and `.7z`
   - (The **default** option as @daxgames put it, which contains the binaries and config files in a single folder)
3. Using one of the existing "installers" that is available for Cmder unofficially, maybe adopting one and extending it
   - (In which case, we will use the existing multi-user frustule and each profile will point to the correct user's AppData folder while the binaries are installed in Program Files and updatable by next releases of the installer)

In the case of latter, since the Write permissions are not granted to non-Administrators, the security concerns are satisfied (as mentioned by @chrisant996) and also the config files are written to the correct directory per-user, allowing customizations per-user and updates to be applied.  It is the industry-wide standard for all mult-user Windows apps that have config files.

In the case of a portable installation, Cmder (along with all binary files and config files) can be installed to AppData, which is also standard practice.

Lastly, the **default** way to use Cmder remains to manually extract the archive file to an arbitrary folder (such as `C:\apps`) or something like that, truly the portable way to carry Cmder with you, the original spirit. However, by integrating Cmder into other stuff (like the non-portable versions of VS Code and WT) we're already sacrificing the "portable" nature of Cmder, so it'd only make sense to offer installable versions of Cmder to people in the distant future (or near future).
