### ISSUE TITLE
Multiple tabs displays multiple windows 

### ISSUE THREAD

**Issue by bmeverett** [cmderdev/cmder#1286]
Is there a way to make it so that no matter how many tabs are active only one window is shown in the taskbar? Currently with two tabs open I see two windows.

![image](https://cloud.githubusercontent.com/assets/3941006/23507914/3776ac96-ff1d-11e6-8293-fc1aa0d383d6.png)

Not sure if this is a limitation of how Windows is displaying the program and just something windows does on its own.

**Comment by bmeverett** [comment]
Found it in settings

**Comment by ClayBenson94** [comment]
@bmeverett Do you have where this is in settings? I have the same issue and cannot find it.

**Comment by bmeverett** [comment]
@ClayBenson94 here you go!

![image](https://user-images.githubusercontent.com/3941006/32005343-094e616e-b972-11e7-81d5-de3f08573d4c.png)

**Comment by juanpedropuig** [comment]
![image](https://user-images.githubusercontent.com/67132645/147798082-cfc9cb4c-9637-4485-934d-d868656b7e76.png)
Why am i seeing it like this on the taskbar?

**Comment by chrisant996** [comment]
> ![image](https://user-images.githubusercontent.com/67132645/147798082-cfc9cb4c-9637-4485-934d-d868656b7e76.png) Why am i seeing it like this on the taskbar?

I think you are asking about the overlay icon.  See screen shot in preceding comment to see where the checkbox can be found for that.  The overlay icon shows the current tab's icon as a small overlay over the main Cmder program icon.

**Comment by alkorlos** [comment]
Hello @bmeverett

Are you still using windows and cmder?

I have same issue

Now the settings screen looks like this:
![Снимок экрана 2023-06-01 143054](https://github.com/cmderdev/cmder/assets/14668230/a2b2fe3f-ea03-454e-bd26-28616dea774c)

Active console only — Show tabs from active console only
Now this setting hides the tabs from the panel above the settings window on the screen.

Far windows — Show all Far Manager windows (panels, editors, viewers) instead of one tab for one console
If I understand the description correctly, this is what now need for this issue, but it does not work for me

**Comment by daxgames** [comment]
@alkorlos if you have questions about this screen it is better to ask @Maximus5 over in the Conemu repository.  This is not Cmder but an external component Cmder uses.

**Comment by alkorlos** [comment]
Thank you!
Yesterday I wrote incorrect information in the comment, I figured it out, the comment was deleted.
