### ISSUE TITLE
very slow to terminate a node command

### ISSUE THREAD

**Issue by beeplin** [cmderdev/cmder#1289]
os: windows 10 x64 1607
cmder: 1.3.2

In cmder, after running a node program (like `npm start` or `npm run dev` during web development), when pressing Ctrl-C twice to terminate the program, it always has to wait for a long time (arount 30 sec or even more) to terminate.  Other terms like `git bash` or `windows cmd` don't have this problem.

**Comment by Jackbennett** [comment]
I get this a lot too and I just use `powershell.exe` not cmder. I think it's just something node does if it fired off a lot of running jobs in child processes or they have large callbacks pending. Node needs to get a gap in the event queue to process the kill command `ctrl-c` makes.

But if anyone gets an actual answer I'd love to know too.

**Comment by alexgabriel-ca** [comment]
In my case, even running basic node commands takes longer than expected to complete.  I am working on an async project (command line), and so far whenever I run node followed by the file name, it takes 2-3 seconds to run.  I've noticed this behaviour only exists with async code, though, as running standard call stack based code is relatively fast.  I've tested this on git bash as well as cmd.exe

You might want to take a look to see whether or not you're running async code since that seems to be the stumbling block for me.
