### ISSUE TITLE
Remove PsGet module

### ISSUE THREAD

**Issue by adamskt** [cmderdev/cmder#1318]
This module clobbers the Install-Module and Update-Module cmdlets available widely in PowerShell 5.1: [PowerShellGet](https://msdn.microsoft.com/powershell/reference/5.1/PowerShellGet/PowerShellGet)

**Comment by Jackbennett** [comment]
We'll have to do something about the clobbering because it can't be assumed people are updating powershell.

**Comment by Stanzilla** [comment]
@Jackbennett since PS is no longer the default, can't we assume that people that switch to PS know what they are doing and take care of that?

**Comment by Jackbennett** [comment]
You'd think but there's a lot of people that would be migrating to powershell and may be using cmder, so anything that helps onboard people is a win. But that's not to say it couldn't be replaced with a warning like "hey, your PS version X is old, consider updating to Y < wmf link >". 

But expecting updating powershell doesn't make cmder portable.

I should think reading how PS loads module we should find a way to not clobber things. I just haven't had time to look and test.

**Comment by pyranja** [comment]
I hit this issue because the PsGet version of `Install-Module` uses `-ModuleName` while the PowerShellGet (bundled with recent PS versions) version uses the standardized `-Name`. I have a workaround, that avoids installing PsGet in `profile.ps1` if the `Install-Module` command is already available. See https://github.com/pyranja/cmder/commit/815b99b98b3e921234d685d4743d0b12d10489fb .

Maybe that is already appropriate for a wider audience?

**Comment by Stanzilla** [comment]
@pyranja nice, PR please
