### ISSUE TITLE
Have you tried tmux ? 

### ISSUE THREAD

**Issue by Xsmael** [cmderdev/cmder#1319]
https://tmux.github.io/

check out this project,  they have very nice feature that could be implemented in cmder, 
like syntax highlighting and many more, i just thought it could inspire you, and since i like cmder,  these feature will be more than welcomed!

**Comment by DRSDavidSoft** [comment]
Interesting. I believe Tmux + Clink + Cmder would make a great combination in Cmder.

**Comment by daxgames** [comment]
I am a heavy tmux user but unfortunately I have not found a version that works on Windows in cmder.

**Comment by sanguis** [comment]
I am using the windows 10 Ubuntu install. the tmux bind key is not working for me. I can bind but then I cant split the window it prints %

**Comment by brodybits** [comment]
From <https://jeffawang.com/posts/how-i-use-tmux/> it looks like someone got tmux working together with ConEmu on WSL. Looks like just one step away from using tmux together with cmder.

**Comment by dball-adashi** [comment]
I found that you don't need ConEmu and can just use Ubuntu with WSL (Windows Subsystem for Linux) to get access to TMUX and what initially looks like a really good development environment.

However I have not ironed out all of the details as it gets weird quick.  

Unbuntu run inside of WSL gives you full access to your hard drives and many of your programs.  For example, if you run Notepad, ubuntu will launch notepad as a window in windows.    It includes the same paths as windows and git bash (MinGW) but adds its own first as shown below. 

$ echo $PATH | sed -e 's/:/\r\n/g' | head -15
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/mnt/c/PROGRA~1/ConEmu/ConEmu/wsl
/mnt/c/Program Files/ConEmu/ConEmu/Scripts
/mnt/c/Program Files/ConEmu
/mnt/c/Program Files/ConEmu/ConEmu
/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath_target_659851718
/mnt/c/ProgramData/Oracle/Java/javapath_target_659875750
/mnt/c/Windows/System32

Microsoft recommends installing node directly on the ubuntu system.  If you try to run the version of node installed on windows, it does not find it, even though it is in the path.  If you explicitly call it, it throws an exception.  This is very different from using node from minGw which appears to just run it as a windows command line application.  I find it problematic that some windows executables work and others do not when working within WSL.

This path may be excellent once you install the duplicate programs on ubuntu and windows and have your environment set up so that each environment executes the proper version of similar programs.  I am new to WSL and don't know how well it works for a development environment where you need access to command line programs installed as part of windows.   

It may be that this is not meant to be an enhanced development environment where tooling is used within WSL and is instead meant to allow developers to test their applications built with visual studio on a linux environment without having to send the files to a linux vm.

cygwin looked like a better path forward but a bug in one of our tools that failed to work within cygwin really soured this experience as it took a long time to realize the behavior was specific to cygwin.

If you have successfully worked WSL and tmux into your development workflow and been able to include windows command line applications as part of that, I would really like to hear about your experience.
