### ISSUE TITLE
not support docker stop $(dokcer ps -q -a)

### ISSUE THREAD

**Issue by boer0924** [cmderdev/cmder#1324]
not support docker stop $(dokcer ps -q -a)

tail -f not allow space line. when tail nginx logs.

**Comment by Jackbennett** [comment]
`docker stop $(dokcer ps -q -a)` That's a powershell line are you using the powershell task?

**Comment by daxgames** [comment]
That is bash syntax.  Are you using git-bash or cmd shell?

**Comment by boer0924** [comment]
@daxgames  so sorry！ I forgot repaly!

I use cmd({cmd::Cmder}) shell `docker stop $(dokcer ps -q -a)` not work.

when I use powershell shell it's worked!

**Comment by Jackbennett** [comment]
You know when you type in the shell it then runs that command? `$()` to powershell creates a new shell  for that line and returns the output. So it runs that bit first. That's why it worked. 

Like maths `1+1 + (2 + 2)` -> `1 + 1 + 4` -> `6`

I guess bash is where powershell got the concept from.

It's exactly the same as;

```
$containers = docker ps -q -a
docker stop $containers
```

also just noticed the do**kc**er spelling mistake.
