### ISSUE TITLE
Cmder console crashes on restart as admin

### ISSUE THREAD

**Issue by gsbabil** [cmderdev/cmder#133]
> Cmder version: 1.1.3
> Windows version: 8.1 (64bit)

**To reproduce:**
- Run Cmder
- Right-click on the console tab and select "Run as Admin"
- When the UAC prompt appears (shown in attached screenshot), select NO
  ![capture-1](https://f.cloud.github.com/assets/1061108/2048645/9623b6d6-8a4e-11e3-87cd-0461ebeeeeb1.PNG)
- The Cmder console crashes with 
  ![capture-2](https://f.cloud.github.com/assets/1061108/2048646/b58085e0-8a4e-11e3-9ed8-51531321ca76.PNG)

**Comment by vadimi** [comment]
@gsbabil I just had the same issue with `No consoles` when I tried to open new tab as administrator. The problem is that in admin mode `cmder` starts `cmd` with the following command: `cmd /k "%CMDER_ROOT%\vendor\init.bat"`and apparently `%CMDER_ROOT%` is not set correctly, so when I change it to the full path of `cmder` - it works perfectly fine.
