### ISSUE TITLE
Provide custom/alternative tab bar style

### ISSUE THREAD

**Issue by Loilo** [cmderdev/cmder#1333]
I love using cmder when I'm on Windows and it regularly fills my complete second screen.

Now the only thing hat bothers me from time to time is that I've made my whole screen pretty dark in color (dark windows task and title bar) so the light cmder tab bar really sticks out.

It would be nice to be able to give the tab bar a custom font and background color, or (which may be significantly less work) just an alternative, kind of "inverted" theme with dark background and light tab labels.

Thanks for all your great work on cmder!

**Comment by Stanzilla** [comment]
We use ConEmu for that, so you'd have to make a request over there.

**Comment by jemhuntr** [comment]
Hey there. Having this same issue. In fact, I don't even use the tab bar itself because it ruins the a e s t h e t i c of cmder overall. I set it to be hidden completely even if I have multiple tabs.

Perhaps we could display a textual representation of tabs down the status bar of cmder?
![cmder](http://i.imgur.com/lHin3J4.png)

See: those little text thingies at the bottom-most part of the window.

Now, imagine that instead of showing just the current tab title on the left hand side of that status bar, there could be a textual display of tabs like:
```
tab            active tab         another tab            more tabs
|              |                  |                      |      |
V              V                  V                      v      v
python - ... | [ cmd - git... ] | git clone - git@g... | bash | cmd:Admin
```

Is this possible?

**Comment by ronjouch** [comment]
> We use ConEmu for that, so you'd have to make a request over there.

Indeed. Relevant ConEmu issues: https://github.com/Maximus5/ConEmu/issues/1661 , https://github.com/Maximus5/ConEmu/issues/1608
