### ISSUE TITLE
Text is not shown in the window but when I select, it can be seen

### ISSUE THREAD

**Issue by yugansh20** [cmderdev/cmder#1346]
Hey 

I am not able to see some of the text in the cmder window after running command.
But when I select that area, I am able to see the text.

Is it some configuration or some color mismatch??

**Comment by ooboqoo** [comment]
I happen to suffered the same problem, I tried to figure out this in "Setting -> Features -> Colors", but not work, the **text color** and **background color** always choose the same color

PS. haven't seen it before, and it happens when using react-native cli

![img1](https://cloud.githubusercontent.com/assets/18899610/25091988/5957599e-23be-11e7-9075-e76d1c403b71.PNG)
![img2](https://cloud.githubusercontent.com/assets/18899610/25091995/5d619be4-23be-11e7-871b-bcda68469aa9.PNG)

**Comment by dk0r** [comment]
@ooboqoo I am experiencing exactly the same issue w/ react-native 😞

**Comment by abhishek-nair** [comment]
Yep, am facing the same issue on react-native, Also its happening in both conemu and cmder though.

**Comment by drgfire** [comment]
happens when i use [now-cli](https://github.com/zeit/now-cli). specifically when using `now help`

occurs irrespective of theme in the cmder shell and with a fresh copy of the program.


![before highlighting](https://cloud.githubusercontent.com/assets/19524316/26340294/6e92bda4-3f42-11e7-9794-b3a600925a94.png)

![after highlighting](https://cloud.githubusercontent.com/assets/19524316/26340305/81f06bda-3f42-11e7-9264-77c316b3787b.png)

**Comment by yugansh20** [comment]
Any updates on this??

**Comment by drgfire** [comment]
same issue as #1300, i think.

**Comment by JaneDawson** [comment]
same here when using Ionic CLI 3.4.0 upwards... Did anybody find a solution?

**Comment by JaneDawson** [comment]
Found a workaround: I created a small PNG File filled with a color I like as background. In cmder in "Settings" -> "Main" -> "Background" I chose this PNG file to be the background image (placement "Stretch-Fill").
In "Settings" -> "Features" -> "Colors" I then changed color 0 (which defines the background color and the color of the text which is not visible) to a color I like for the text.
"Save Settings" and everything looks as it's supposed to be...

**Comment by AbhishekNairTnex** [comment]
Thanks Jane, This sorted out this issue.

**Comment by jcollum-cambia** [comment]
Happening here too: 

Conemu: 

![image](https://user-images.githubusercontent.com/29718037/29928793-a009e27e-8e1e-11e7-8186-aad6f536a8cf.png)

Same theme in Cmder: 

![image](https://user-images.githubusercontent.com/29718037/29928815-b0efca5e-8e1e-11e7-9539-1916553bd664.png)

So it's happening in Cmder but not ConEmu with the same theme (Solarized Light).

**Comment by DmitryGonchar** [comment]
Had little problem with JaneDawson [solution](https://github.com/cmderdev/cmder/issues/1346#issuecomment-315044344) - that in full screen on Windows I got a white stripe at the bottom of the window.

So an alternative solution, which worked better for me (without stripe), is in  "Settings" -> "Features" -> "Colors", in "Standard colors" section - chagne Text: dropdown from "auto" to "#0" (can be any number or color), Back: to "#1" e.g.

Setting "Background" png is not needed then

**Comment by OogieBoogieInJSON** [comment]
@DmitryGonchar That worked, thank you!

**Comment by sandropoluan** [comment]
Any update?

**Comment by pcguru** [comment]
Setting colors as dmitryGonchar described does not work for me, the bg image trick works though.

**Comment by donjo9** [comment]
I had the same problem with React-Native and the latest stabel ConEmu, installed the latest preview version of ConEmu and the problem went away

**Comment by dnl-re** [comment]
@donjo9 that did the trick. Updated from 180206 preview to 180626 preview and that solved it.

**Comment by StNick** [comment]
Came here looking for a solution but in the end I realised that this only seems to be a problem for me when running in a screen session.  Not really sure where the blame lies, but for now, I'll run my unit test outside of screen.

**Comment by bartvanandel** [comment]
I'm running the 180626 preview, and without any workaround (like setting custom colors or a background image), the issue is still present. An HTML dump shows that the foreground color and background color of the affected sections have the exact same value, so it looks like the "Adjust lightless of indistinguishable text" feature (which is enabled in my setup) is failing.

Looking forward to a real solution.

**Comment by majidaldo** [comment]
not stale
