### ISSUE TITLE
display current directory without full path

### ISSUE THREAD

**Issue by rss81** [cmderdev/cmder#1400]
Cmder/conemu by default displays the full current path, I'd like to it to show only the current directory. Is that possible? I've looked at the settings and have been unable to locate where or how this might be done.

**Comment by glucas** [comment]
Assuming you're in a cmd.exe shell, the prompt is configured via the PROMPT variable. Try `prompt /?` to see the options. It looks like there is no built-in option to display only the directory name.

With cmder (more specifically, with clink) you can add additional prompt behavior by writing some lua code and registering a clink prompt filter. So you can probably achieve what you want by setting the PROMPT variable so that it does not include any path, and then adding a clink prompt filter to add the current directory.

**Comment by glucas** [comment]
Cmder sets up the prompt in a lua script that is registered with clink as a prompt filter. If you don't want to print the full path I believe you would need to tweak the code in cmder/vendor/clink.lua -- I don't see a way to configure this besides changing the code.
