### ISSUE TITLE
tab cant autocomplete "Desktop"

### ISSUE THREAD

**Issue by tooyangtoonaive** [cmderdev/cmder#1448]
version 1.3.2

ls -l

drwxr-xr-x 1 zc 197121       0 七月 23 20:24  Desktop/
drwxr-xr-x 1 zc 197121       0 二月 26 16:34  Documents/

Either "cd" or "ls" can only autocomplete Documents/

**Comment by DRSDavidSoft** [comment]
This is by design, rather than an issue. Clink uses linux-based **readline** for tab auto completion, which means it doesn't traverse between directories starting with the letter D.

Solutions:
- type `D`, double-press tab
- type `Des`, press tab once

The latter works when you've typed enough letters for readline's guess to only match _one_ result, which it will auto complete.
