### ISSUE TITLE
starting powershell.exe form total commander does not sart cmder

### ISSUE THREAD

**Issue by bitbonk** [cmderdev/cmder#1466]
When I start powershell.exe directly by double clicking c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe within total commander, it is not run with cmder, instead the regular blue terminal opens. 

But when I do exactly the same thing in windows explorer cmder opens.

Why is that so, and what can I do agains it?

**Comment by daxgames** [comment]
Because PowerShell is an application and cmder is an application.  To my knowledge you cannot associate an application with an application.  Of you want to launch PowerShell in cmder run cmder then launch a PowerShell task..

**Comment by daxgames** [comment]
@bitbonk look in Cmder 'Setup Tasks->Integration->Default Term->List of Hooked Executeables'.  I think if you add total commander's exe file here it may launch conemu when clicking powershell from total commander.

It is probably not actually doing what you want though.  Yes it is launching conemu if you launch powershell but that conemu session will not have cmder enhancemnents since the cmder powershell task is not being launched.

**Comment by bitbonk** [comment]
@daxgames Thanks for the tip, that all I wanted. I acually had `totalcmd.exe` in the list but it had to me `totalcmd64.exe` in my case. It works now. This issue can be closed.
