### ISSUE TITLE
How to change the ConEmu.xml location

### ISSUE THREAD

**Issue by copdips** [cmderdev/cmder#1470]
Hi, 

I have a multi-users environment, each user needs to use his own ConEmu.xml on the same server, as different people have different preferences on shortcuts, sizing etc.

Currently the conf file must be at : `vendor\conemu-maximus5\ConEmu.xml`

Could we change it to another location outside of cmder folder, sth. like a homedir:  `$env:userprofile\cmder\ConEmu.xml`

Thx.

**Comment by daxgames** [comment]
You could try using this to launch cmder instead of using cmder.exe.  https://github.com/cmderdev/cmder/blob/master/Cmder.bat

Note: This is not part of the cmder binary distribution and will need to be downloaded and copied into cmder manually.

To launch type or add to a shortcut:

```
Cmder.bat [path-to-user-conemu.xml]
```

There may be side effects but it is the only way that I know of.

**Comment by Lucas-C** [comment]
From the doc, you can try to modify the registry:
https://conemu.github.io/en/SettingsFast.html#settings-storage
