### ISSUE TITLE
HOME PATH shows incorrect format has issuse with rsync in vagrant

### ISSUE THREAD

**Issue by jonnicm** [cmderdev/cmder#1489]
I have managed to get a vagrant box up and running in Cmder however when trying to rsync the vagarnt folder I get:

![image](https://user-images.githubusercontent.com/32008568/30509650-3a481d56-9af9-11e7-8af1-2a4ddd5a385b.png)

I also get

![image](https://user-images.githubusercontent.com/32008568/30509629-ef28b34e-9af8-11e7-844b-850a946eac4b.png)

Need F:\Devops

**Comment by daxgames** [comment]
'pwd' is a git bash command and you are not in a git bash shell you are in a cmd shell.  'cd' will return 'F:\Devops'.   rsync is not a part of the cmder package so what are you using to get that?  It is an gnu utility and thus would not understand Windows paths lik 'F:\Devops'.

Try what you are trying from a bash shell instead of the cmder default cmd shell.

**Comment by daxgames** [comment]
I assume this helped? :-)
