### ISSUE TITLE
editing back lines crazyness

### ISSUE THREAD

**Issue by Gfurst** [cmderdev/cmder#1523]
there is some behavior that is driving me completely crazy, and I'm not sure how to explain or whether its from cmder, conemu, or cmd standard itself, I'll try my best to explain it

when going back a previous command and editing, it will go nuts, like the cursor is not obeying you or replacing stuff instead of inserting, and as frustrating it is to try and get the command right, when you finally read it properly and submit it, the sequence string is not what is delivered for the command and it fails.

**Comment by lukescammell** [comment]
Luckily I've not experienced anything like this, so I'm offering some blind advice instead, since I can't help debug it.

Try [downloading a fresh copy](https://github.com/cmderdev/cmder/releases/download/v1.3.2/cmder_mini.zip) and extracting it to a temporary directory and see if that suffers similarly.

If it doesn't suffer from your problem then it's a configuration issue with your current version of cmder and using a fresh copy is an easy fix :)

**Comment by Gfurst** [comment]
well, it was a very recent install, like from this month still, and I'll see if I can record the desktop while it happens, as it would be much easier than trying to explain it.

**Comment by siyuan** [comment]
I have similar problem. When you use Linux shell's shortcuts like ctrl + a (back to front), the edit will wrong, please fix it. Thanks.
