### ISSUE TITLE
cmder slow running commands on Windows 7 X64 Enterprise

### ISSUE THREAD

**Issue by vurso** [cmderdev/cmder#1552]
As per the title downloaded the latest release of Cmder and installed on a new Windows 7 X64 Enterprise laptop (i7 HQ, 24GB ram, SSD so plenty fast).

Cmder starts up fine however when I run commands like ls for example it lags very badly (executing the actual command seems fine however).

**Comment by aflansburg** [comment]
I also experience this on occasion. Typically when running file system operations such as 'cp' or 'ls'. The longest delay I've experienced between entering a command and it's actual execution is with the 'ls' command. Given - 'ls' is not really a Windows command, but I find myself stuck using it instead of 'dir'

**Comment by sqqqs** [comment]
This is the MinGW problem. Cmder is not to blame.
https://github.com/Alexpux/MSYS2-packages/issues/138

**Comment by sillmnvg** [comment]
Having this same issue on an i7/16gb workstation laptop as well running Win 7 x64 Ent.
