### ISSUE TITLE
Moving files with ../

### ISSUE THREAD

**Issue by kernelp4nic** [cmderdev/cmder#158]
Hello! There is a way to move files like this? (the *nix way)

```bash
iblistener (master)
λ mv project\plugins.sbt .
mv: `project\\plugins.sbt' and `./project\\plugins.sbt' are the same file

iblistener (master)
λ mv project\plugins.sbt ../
mv: cannot move `project\\plugins.sbt' to `../project\\plugins.sbt'

iblistener (master)
λ mv project\plugins.sbt ..\
mv: cannot move `project\\plugins.sbt' to `..\\/project\\plugins.sbt'
```

**Comment by hoozifachi** [comment]
It works correctly if you use forward slashes.

`cp ../ch07/karma.conf.js .`

Pressing tab to autocomplete your path puts in backslashes, so it doesn't help much.

**Comment by narnaud** [comment]
That's because the mv and cp commands (and also rm ones) from msysgit are too old.
I would suggest that you install [Gow](https://github.com/extofer/gow) or [GnuWin32](http://gnuwin32.sourceforge.net/), and make sure they are at the beginning of the path.

I'm using my own set of utils here: [win32-utils](https://github.com/narnaud/win32-utils) as GoW replaced ssh with plink.

**Comment by Jackbennett** [comment]
Seems fixed long ago when we updated something.
