### ISSUE TITLE
X-Forwarding Not Working 

### ISSUE THREAD

**Issue by TheAssCoder** [cmderdev/cmder#1599]
### Newbie here so sorry if this issue is in any way not what is expected here 

Hi, 

Big fan of the emulator but at the moment I am stuck using puTTy for most of my cluster based work as I need x-forwarding. I have looked at every guide that currently exists as of now 26/12/17 talking about cmder/conemu and x-ming/x-forwarding and nothing seems to work both for myself and others on forums. 

Can we get a fix or if it's a new feature, can we get it added? If cmder already supports it, can we get a mini guide on how to make it work?

**Comment by mrRosset** [comment]
I'm able to get it to work with Xming. I need to have an environment variable called DISPLAY with value "localhost:0.0" (or to be more general what is written when you put your mouse over the xming tray icon)
And they simply have Xming started before I open cmder.
Also depending on the server configuration I need to do ssh -XY instead of simply X to force it to use a non-trusted x11 server.

**Comment by TheAssCoder** [comment]
That's what I am doing but it does not seem to work. xming displays "localhost:0.0"  and I try to add that to the env variable on the cluster. I am not sure why it's still not working. Any idea what it could be?

**Comment by holgerbrandl** [comment]
Also having some docs about how to setup x-forwarding with cmder using xming or whatever is needed. would be great.
