### ISSUE TITLE
Using the context menu "Cmder Here" should create a new tab (if there's existing terminal) instead of creating a new window

### ISSUE THREAD

**Issue by arvilmena** [cmderdev/cmder#1645]
Hello mates :)

Do we have an already existing way to enable this: 

1. Say, I already have an existing CMDER window
2. I go to `D:/somewhere/directory`, Right click -> Cmder Here
3. I wish that the CMDER terminal that will open to go to the already existing window as a new tab (only if there's already existing window, if none, create a new one)

Is this possible? Because my screen is clustered with too many terminal :(

Regards,

**Comment by ClericPy** [comment]
1. find the reg path with regedit.exe
2. set  **"/single"** arg for the command

> **"F:\cmder\Cmder.exe" /single "%V"**

#### as below:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command]
@="\"F:\\cmder\\Cmder.exe\" /single \"%V\""

```

**Comment by DRSDavidSoft** [comment]
Since this issue is related to how ConEmu works, a modification based on [this](https://superuser.com/questions/757434/how-do-i-configure-conemu-to-open-a-new-tab-instead-of-a-new-window-when-run-on) would work (I use a variation of that myself).

The question is, whether the moderators approve of changing the default behavior in favor of tabs.

Personally I think using tabs is a much better solution, and a window per context menu is pointless.

**Comment by mew1033** [comment]
@DRSDavidSoft Can you explain a little more how you got this working?

**Comment by Puggers** [comment]
@DRSDavidSoft Sorry to bother you with this, but I am really not versed in dealing with registry files, I was hoping you would have a sample of what the registry key should look like with this modification?

> @mew1033 Cmder launches ConEmu by calling it from the `Cmder.exe` binary.
> 
> You'll have to either compile `Cmder.exe` with [this option](https://superuser.com/questions/757434/how-do-i-configure-conemu-to-open-a-new-tab-instead-of-a-new-window-when-run-on) built it, or modifying the Registry key for the [context menu](https://github.com/cmderdev/cmder/wiki/Context-menu-integration) to run ConEmu with the switch directly.
> 
> I went with the latter at the time of writing my comment.
> 
> @daxgames Could you add this option to the launcher code?
> e.g. `Cmder.exe /newtab %v` could be used to open a new tab in ConEmu.

**Comment by daxgames** [comment]
Just use latest cmder 1.3.11 and register with `cmder /register /single`.  Works for me to open a new tab in an existing window.

**Comment by GreatFireWall** [comment]
@daxgames Can you tell me the step by step ?

**Comment by daxgames** [comment]
Read the above post

**Comment by DRSDavidSoft** [comment]
@GreatFireWall Since it may be a bit confusing, I'll explain in detail:

- When you download the Cmder *.zip* file, it will contain a file with this name: <kbd><img src="https://raw.githubusercontent.com/cmderdev/cmder/master/icons/icon_48.png" width=16 /> Cmder.exe</kbd>  
   This is called the *cmder launcher* and it's used in Cmder to open a terminal.

- One of the things that the launcher do is *registering the context menu* for windows.
   **How does it do it?** By running the .exe file with the switch: `cmder.exe /register`.  
   You can type it _in a terminal_ while you're in the cmder directory (e.g. C:\apps\cmder)

   So, if you execute the switch that I mentioned above, then Cmder will install the context menu.

- Now, we get to the part that @daxgames said. In cmder **version 1.3.11 (and above)**, a new switch has been added to the launcher, that allows you to register Cmder with the _single instance_ windows enabled:
   ```
   cmder.exe /register /single
   ```

   **What does that mean?** well, the `/single` switch means that any new cmder terminals will open _in a new window_ instead of a new tab.

**NOTE 1:** You can omit the `.exe` extension (and any other [path extensions](http://environmentvariables.org/PathExt))  in Windows, hence why @daxgames wrote `cmder /register /single`.

**NOTE 2:** To use this, you *must* update to the [latest version](https://github.com/cmderdev/cmder/releases) of Cmder (which is 1.3.11 as of writing this).

I hope this helps! :)

**Comment by GreatFireWall** [comment]
@DRSDavidSoft Thank you !  Solved !

**Comment by DRSDavidSoft** [comment]
A couple of more notes:

- This update was made in pull request #1982.
- All it does is to pass the `/single` switch to ConEmu (note: that is what is used as for terminal emulator@)

You can read more about what the switch actually does in ConEmu here:
https://conemu.github.io/en/ConEmuArgs.html

**Comment by GreatFireWall** [comment]
By the way, How can I do `Cmder Here` as Administrator ?

**Comment by DRSDavidSoft** [comment]
@GreatFireWall Do you want to have one `Cmder Here` that opens as administrator, or to have two options like `Cmder Here` and `Cmder Here as Administrator`?

In any case, I suggest to use [`csudo`](https://conemu.github.io/en/csudo.html) instead, e.g. `csudo notepad.exe`, `csudo nano.exe`, etc. when you're in Cmder window to run an executable (such as `notepad.exe` and `nano.exe`) as administrator.

For example, you can **get a new Cmder as administrator window**, by running `csudo cmder`. This only works if you're on the latest version, and have [added `[cmder_root]` to your `%PATH%`](https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables#3-adding-to-path).

If you want to _always_ start Cmder as administrator, the `-new_console:a` switch should be used (the `a` stands for administrator). 

---

P.S. To see how your context menu is set-up, go to here (<kbd>Win</kbd> + <kbd>R</kbd> → `regedit.exe`):
```batch
HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder
```

From the toolbar, go to **File** → **Export** and save the file (e.g. `my_cmder.reg`).

Then attach it to your comment (by dragging and dropping it), so I can see how your current Cmder context menu is set-up.

**Comment by GreatFireWall** [comment]
@DRSDavidSoft Thanks for your detail guide.

Yes, I want to have `Cmder Here` and `Cmder Here as Administrator` both. 

Currently, I use `cmder.exe /register /single` register for `Cmder Here`, so I want to make `Cmder Here as Administrator` `single` also. Is this possible ?

This is my `HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder`:

![image](https://user-images.githubusercontent.com/4510984/56709909-54db0900-6756-11e9-9ead-46af2ebb94c1.png)
![image](https://user-images.githubusercontent.com/4510984/56709918-602e3480-6756-11e9-962d-0920dc2e30c6.png)
