### ISSUE TITLE
How to store configuration

### ISSUE THREAD

**Issue by DRSDavidSoft** [cmderdev/cmder#1695]
We need to come up with a standardized way to store Cmder configuration [here](https://github.com/cmderdev/cmder/tree/master/config).

I'm working on a branch to customize the prompt color and handle character (currently λ) from the `/config` directory, and similarly, a lot of `init.bat` (e.g. @daxgames's recursive path enhancing) could benefit from a stored configuration file.

@cmderdev/trusted-contributors - What would you vote as a suitable container for the Cmder configuration?
- XML
- YML
- JSON
- TXT/INI
- BAT/SH
- (other)

Keep in mind that it needs to be:
- easy to edit for user
- accessible from both batch and bash environments
- uniform across all vendored platforms

**Comment by DRSDavidSoft** [comment]
@daxgames That's good (and looking forward to your PR) – though by not unified, I mean that each shell is currently loading its custom script. e.g. for changing the prompt color from green to cyan, I have to modify these <u>3</u> files:

- git-prompt.sh
- clink.lua
- profile.ps1

It would be better to have a single `console.lua` file in /config, which then would be parsed by each of those files using Lua executable. Additional _platform-specific_ scripts then would be separated to .sh, .bat, .ps1 and .lua scripts in the `/config` directory.

So, a newbie user could easily edit that `console.lua` file to achieve customizing the prompt, essentially instructing the `/vendor`-based scripts on _how_ to set the prompt. If further modification is required, (besides other unified files such as `git.lua`, `path-enhancing.lua`, etc...) then he/she can write a custom script to run on start-up.

I see _many_ parallels between platforms that Cmder supports, besides customizing prompt. That's what I meant, for example, to set the path depth limit from `/config`. Also, that's why I suggested container formats like XML, YML, and JSON. Because they're specifically made to hold _data_, rather than execute code. (I'm fine with .lua, though, as it's already easy to edit.)

There are [methods](https://gist.github.com/pkuczynski/8665367) for bash to parse .yml, or better we can include a lua.exe binary (<50KB) in the `/vendor` directory to parse console.lua and adjust color and the λ handle accordingly.

I imagine on the first initial start-up, a copy of console.lua should be generated into `/config`, and user is instructed to edit that file for any customization. Then clink.lua would include it, and substitute portions of prompt with the defined values. For bash, it would do the same, except bash is responsible to load the console.lua script and substitute the portions the bash way (it still sets the λ as handle, but it's read from `console.lua` rather than **hardcoded** directly in `git-prompt.sh` or `cmder_exinit`.)

So, with that said,
1- does it make sense?
2- do you agree/disagree?

**Comment by daxgames** [comment]
@DRSDavidSoft. Don't get me wrong, I like the idea in principle.  I just question the effort vs the reward, how much will it get used.  I sometimes wonder how much current configuration features available to cmder users are actually used beyond the most advanced users, Ex: contributors to the project.  Many users don't use all three shells, I bet many use only the default cmd.exe based shell.

I don't think Lua is the right thing to use.  Lua is a programming language and while that may be great you and me a normal user not so much.

As far as modifying 3 files to change prompt color every time you uodate, the flaw is in editing files in the `vendor` folder.  You should be able to copy the sh and write a ps1 into `%cmder_root\config\profile.d` config them the way you want and those settings will survive cmder updates.  That may be an overkill way of doing it for PowerShell because profile.ps1 has some ability for user prompt customization built in, I think, but that's a very quick idea of how to do it without looking at the code.  The clink.lua edit would require the future PR I have mentioned to enable user lua load to allow lua changes to persist.

The thing is the majority of cmder users do not need or want to do this kind of config.  I almost think documentation of how to do these advanced configs has a better ROI.

I know how it is though, If you have to do this though just make sure everything youbdobis backwards compatible for those that may net need the functionality.

Just my $.02

**Comment by DRSDavidSoft** [comment]
Thanks for your considerations, I believe you are right. For now I'll hold this until you finish your PR - to make sure it's implemented right. (Please mention this issue on your PR when you make it.) Any edits I make, I'll also make sure it's fully backwards compatible.

I might make this as a separate package, like a plug-in to Cmder. (As long as it's calling executables from /config, it should be fine.)

I believe if this makes modification to prompt easier for power users (and contributers), it deserves to be done. Though I think if users will be able to easily use this, it would even be used more, since some issues and forks regarding changing the prompt has already been made.

Thanks!

**Comment by DRSDavidSoft** [comment]
@Stanzilla and @MartiUK any thoughts?

**Comment by Stanzilla** [comment]
I'm with @daxgames here, after the Lua loader is done, we are pretty good when it comes to storing user data.

**Comment by DRSDavidSoft** [comment]
↩️
