### ISSUE TITLE
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" causes lambda prompt not appearing

### ISSUE THREAD

**Issue by Kurdym** [cmderdev/cmder#1807]
On a fresh unzipped cmder, I get this on startup:

![image](https://user-images.githubusercontent.com/1431462/41205981-6d562b76-6cfd-11e8-97b4-04217a971d3a.png)

When uncommenting "call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"", and then startup, I first have to exit to get to the Lambda:

![image](https://user-images.githubusercontent.com/1431462/41205986-76948b7e-6cfd-11e8-83c3-8b9b97e5409b.png)

I want the second situation to be like the first, directly to the Lambda prompt.

**Comment by Archez** [comment]
This is being caused by the last few lines of `start-ssh-agent.cmd`. Specifically these lines (84-86):
```
@IF NOT ERRORLEVEL 1 @(
    @CALL cmd %*
)
```
Here, a new cmd prompt is being spawned with the arguments supplied by `%*` (which currently is empty, causing the prompt to wait). Unfortunately these lines of code are provided by git-for-windows, not cmder.

A workaround that you can use would be to adjust the line in `user-profile.cmd` to say:
```
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" /k exit
```
The `/k exit` will be used as the arguments supplied by `%*` and will effectively auto exit the new cmd for you.

**Comment by reypm** [comment]
@Archez I am having exactly the same issue but your solution is working partially for me. Having the line as you said before in the `user-profile.cmd` does start the agent properly but I got the following message after run the command: `ssh-add ~/.ssh/id_sls`:

```
λ ssh-add ~/.ssh/id_sls
Error connecting to agent: No such file or directory
```

Do you have any suggestion and/or idea in how to fix this?
