### ISSUE TITLE
version 1.3.6  lanuchs so slower than 1.3.5 

### ISSUE THREAD

**Issue by CuriousFu** [cmderdev/cmder#1821]
version 1.3.6  lanuchs so slower than 1.3.5

**Comment by daxgames** [comment]
I don't see a difference? Both launch the same for me.  0.3.6 is actually faster see below for the proof.

Added `echo. | time` to top and bottom of `init.bat` in both `v0.3.5` and `v0.3.6`.

v0.3.5
```
The current time is: 17:12:10.26
Enter the new time:
The current time is: 17:12:10.72
Enter the new time:
```

v0.3.6

```
The current time is: 17:10:13.53
Enter the new time:
The current time is: 17:10:13.76
Enter the new time:
```

Can you elaborate?

**Comment by gunr2171** [comment]
In 1.3.6 I'm getting around 10 second wait time between the screen showing up and the terminal being ready for input:

```
The current time is: 16:25:09.05
Enter the new time:
The current time is: 16:25:18.21
Enter the new time:
```

I'll update this post when I get 1.3.5 back on this system to see the difference.

**Comment by daxgames** [comment]
@gunr2171 Cmder 1.3.6 `init.bat` is doing more when it runs so it is a little slower we already know that.  I doubt we can make it much faster without removing the additional functionality.

You can try [this](https://ci.appveyor.com/project/MartiUK/cmder/builds/19931484/artifacts).  It has been optimized for speed a little more than the released Cmder 1.3.6 and has a built in `timer.cmd` to time `init.bat` if the `/t` argument is specified in the ConEmu Task that starts `init.bat`.

Edit the Cmder task in this new build and add a `/t` to automatically time the `init.bat`.  See the new task command below:

```
cmd.exe /k ""%ConEmuDir%\..\init.bat" /t "
```

Actual Sample Output from my system:

```
Start Time:   19:58:18.58
End Time:     19:58:20.06
Elapsed Time: 0:0:1.48 (1.48s total)

C:\Users\user\cmderdev
λ
```

If you want to you can also time other Cmder versions by:

_Note: The `/t` argument is not supported or required on older Cmder versions if you follow the directions below!_

Copy `%cmder_root%\vendor\bin\timer.cmd` into a previous Cmder install in the following location `%cmder_root%\bin\timer.cmd`.  

Add the following to the top of the `init.bat` after @echo off:

```
set cmder_init_start=%time%
```

Add the following to the bottom of the `init.bat` above the last exit:

```
set cmder_init_end=%time%
timer %cmder_init_start% %cmder_init_end%
```

**Comment by daxgames** [comment]
@gunr2171 Cmder Fast Mode Init takes my init times from 1.81 down to .74 seconds.

**Comment by gunr2171** [comment]
Thanks for the new builds.

First results using only the `/t` flag, including retesting the official 1.3.6 build.

|           | Home | Work |
|-----------|------|------|
|     1.3.6 | 2050 | 9048 |
| 1.3.6.765 | 2194 | 8028 |
| 1.3.6.781 | 2192 | 8490 |

Two things of note

1. The previous values for 1.3.6 I did before were `1960` and `7173` ms for Home and Work, respectively. I'm not sure why using `timer` rather than `echo. | time` added so much time.
2. 1.3.6 retiming were still faster than the dev builds (again, this is only using the `/t` flag).

I ran 781 with the `/f` flag as well.

|                      | Home | Work |
|----------------------|------|------|
| 1.3.6.781 with /t /f |  995 | 5552 |

Home went down a second, Work went down 3 seconds.

I'm going to keep playing with this at work to see if I can deal with a 5.5 second start up by sacrificing git recognition (because that's a feature I really like).

**Comment by manatlan** [comment]
Thanks ! ...
I'm a new user of this marvelous tool ... the only things which bored me : it's the time between opening a new tab, and the prompt ready (more than 2sec ?! on a core i7 with 16go ram on w10 ?!?))
I tested the 1.3.5 : and it's now (just) "acceptable" ... I'll stick with it 
Thanks for the tip !

**Comment by daxgames** [comment]
Closing since 1.3.8 was released with `/f` optimization
