### ISSUE TITLE
D:\Program Files\cmder\vendor/clink.lua:328: invalid use of '%' in replacement string

### ISSUE THREAD

**Issue by jay763190097** [cmderdev/cmder#1845]
when i use open Cmder in svn directory, it hint this message.

**Comment by jay763190097** [comment]
I cannot right-click to open cmder under D:\ or E:\ ......

**Comment by daxgames** [comment]
@jay763190097 

"when i use open Cmder in svn directory, it hint this message"

I don't use nor do I know how to use svn so I can't duplicate the issue to try and fix it.

"I cannot right-click to open cmder under D:\ or E:\ ......"

The above does not work, I don't know why but it is low on the priority list to fix.

**Comment by SmGG** [comment]
@daxgames  because there are Chinese characters in the path
you can temporarily solve the problem by comment the line 328 and 329 in clink.lua @jay763190097

**Comment by Tomalak** [comment]
Hi @daxgames, this error is can happen when `string.gsub()` is called with a raw replacement string, i.e. one that contains user input and can therefore contain rogue `%` characters. It's fixed by escaping `%` to `%%`.

[For example here](https://github.com/cmderdev/cmder/blob/ae2fda72fd15854a80b41d2457aaa156a205a60f/vendor/clink.lua#L50), where `lambda` comes from the user's environment and could contain virtually anything:

```lua
-- broken for any value of lambda that contains %
string.gsub(cmder_prompt, "{lamb}", lambda)

-- fixed
string.gsub(cmder_prompt, "{lamb}", lambda:gsub("%%", "%%%%"))
```

It can't hurt to scrutinize all `gsub()` calls in `clink.lua` and add such escaping code - currently there seem to be only 9 such lines overall, and not all of them are even relevant.

**Comment by Tomalak** [comment]
@Stanzilla Done. #1991

**Comment by Stanzilla** [comment]
thanks!
