### ISSUE TITLE
Opening `code .` messes up with autohotkey

### ISSUE THREAD

**Issue by masters3d** [cmderdev/cmder#1876]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
When using cmdr to launch `code .`, vscode will not react to any of the autohotkey scripts. I downloaded and launched using ConEmu but this issue is not there. 

At first I thought this was a vscode issue (which it could still be) but I wanted to cross post here to see if this could be cmdr issue instead (likely)

https://github.com/Microsoft/vscode/issues/57121

**Comment by daxgames** [comment]
I see previous versions of decide.  Were you using cmder at the time they worked for you?  What versions of cmder have you tested?

**Comment by masters3d** [comment]
only Cmder 1.3.5 

 https://chocolatey.org/packages/Cmder

**Comment by daxgames** [comment]
@masters3d  Could you try the latest version please

**Comment by Perverance** [comment]
I'm having the exact same problem.

**Comment by chrisant996** [comment]
It's caused by the combination of [ConEmu](https://conemu.github.io)'s keyboard hooks plus AutoHotkey's keyboard hooks (and maybe plus VSCode).

Playing with these and other similar settings might help, but also might cause other problems.
https://conemu.github.io/en/SettingsFeatures.html#id1752
https://conemu.github.io/en/SettingsKeyboard.html#id1649

Cmder can't do anything about this.  I recommend searching issues in the ConEmu repo and maybe opening a new issue there.  But it's very likely a problem that won't have any solution.
