### ISSUE TITLE
Number calculation?

### ISSUE THREAD

**Issue by rasoulian** [cmderdev/cmder#1878]
Do you have any plan to support number calculations?
Such as: 
12+12
24

**Comment by DRSDavidSoft** [comment]
@rasoulian The same feature you are asking is already implemented in Gnu's [`calc.exe`](http://isthe.com/chongo/tech/comp/calc/index.html), I use it on a daily basis.
You can download it from here:
https://sourceforge.net/projects/gnuwin32/files/calc/2.11.10.1/calc-2.11.10.1.exe

(In order to not conflict with Windows' own `calc.exe`, you may rename it to something like `calcgnu.exe` and call it from Cmder.)

**Comment by daxgames** [comment]
@rasoulian in cmd.exe based and git bash based shells this is already possible.

Cmder cmd.exe

```
set /a sum=12+12
echo %sum%
24
```

Git Bash

```
expr 1 + 1[enter]
2
```
