### ISSUE TITLE
just found out this excellent software!

### ISSUE THREAD

**Issue by abdulbadii** [cmderdev/cmder#1894]
### Description of the issue 
I just found out this excellent software this minute, so quick questions:

- is cmder a shell interpreter with commands are the same with Windows builtin cmd.exe or TCC.exe by JPsoftware or what?
- I am on Windows 10 and its port Linux ie. MSYS2 , running TCC and Bash back and forth concurrently. How can I take most usage and benefit of them along with cmder?

Thanks in advance.

**Comment by daxgames** [comment]
Cmder is a portable enhancement for cmd.exe, Powershell, and Git Bash sessions.  The main goal is to make Windows cmd.exe shells more useable/functionalfor a Linux user.  It is several tools stitched together using some init scripts.  The component that provides much of the functionality you see in `cmd.exe` sessions, `clink`, unfortunately is not compatible with `tcc`.  We have done every thing we can to enable `tcc` use with `cmder` but since we do not maintain `clink` or `tcc` we can't fix this incompatibility.  There are closes issues on this in the cmder issues area of you want more detail.

You can add other `` to cmder to launch other shells, I have done msys2 sobi know it works and it can take advantage of cmder init script processing.  See the read me.2nd on integrating external shells.

Hope this helps.

**Comment by daxgames** [comment]
@abdulbadii Does this answer your question?  If so please close the issue.  If we do not hear from you in 5 days the issue will be closed.

**Comment by daxgames** [comment]
No response from @abdulbadii closing.
