### ISSUE TITLE
Unicode character recognition

### ISSUE THREAD

**Issue by giuliannosbrugnera** [cmderdev/cmder#1919]
I was reading the issue #1688 and I was wondering why Cmder can render the character → properly

![image](https://user-images.githubusercontent.com/7342802/47261211-ae5d3500-d4a0-11e8-9365-9a460daaee72.png)

but cannot render the character ➜ properly

![image](https://user-images.githubusercontent.com/7342802/47261206-9685b100-d4a0-11e8-8300-e74e8b714a89.png)

Is there anywhere I can look into which Unicode characters Cmder will/ will not render?

**Comment by codesinthedark** [comment]
Yes, running 
cmd /c "%ConEmuBaseDir%\Addons\utf-8-test.cmd"
does not show all character properly in the first row (Specials)

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)

**Comment by awijeet** [comment]
I also had the some similar issue, to get the solution I changed "Alternative Font" to MS Gothic and now fonts are appearing instead of blocks. Hope it helps to follow the path. 
![Annotation 2019-12-18 162219](https://user-images.githubusercontent.com/377668/71080283-db939900-21b2-11ea-83aa-4fa5e8feb649.png)
