### ISSUE TITLE
link cmder with the sublime text 3

### ISSUE THREAD

**Issue by jjen9** [cmderdev/cmder#1967]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by jjen9** [comment]
Hi world !  Terminal : the terminal: C\ProgramData\cmder\cmder.exe 
was not found

**Comment by jjen9** [comment]
@daxgames I installed package terminal when I click on ctrl+shit+t to run cmder from sublime I got this message : " Terminal : the terminal: C\ProgramData\cmder\cmder.exe
was not found "
 I try to fix it but unsuccessfully

**Comment by jjen9** [comment]
also not working but I'm gonna close the issue if this cool for you.

**Comment by daxgames** [comment]
@jjen You are missing a `:` try:

```
"{
	// The command to execute for the terminal, leave blank for the OS default
	// See https://github.com/wbond/sublime_terminal#examples for examples
	"terminal": "c:/users/user/cmderdev/cmder.exe",

	// A list of default parameters to pass to the terminal, this can be
	// overridden by passing the "parameters" key with a list value to the args
	// dict when calling the "open_terminal" or "open_terminal_project_folder"
	// commands
	"parameters": [],

	// An environment variables changeset. Default environment variables used for the
	// terminal are inherited from sublime. Use this mapping to overwrite/unset. Use
	// null value to indicate that the environment variable should be unset.
	"env": {}
}
"
```

**Comment by jjen9** [comment]
not working again

**Comment by wesleypimentel** [comment]
Hi! Same problem here. Solutions? Tks

**Comment by jagreetdg** [comment]
AFAIK the problem is with the basic ST3 Implementation not Cmder. Cmder requires admin privileges for certain tasks everytime it runs, and ST3 somehow won't show a "Give Admin Rights" UAC Dialogue Box everytime it is invoked, hence it plain rejects the call and shows "Access Denied" or "Not Found" error. This is also typical while building a file using ST3 when the "ComSpec" Environment Variable is set to Cmder instead of cmd.exe.

Steps to reproduce this bug :
1) Set your default Windows terminal to Cmder by changing the "ComSpec" variable and try building any file using the inbuilt ST3 Build System.
2) Set the default terminal to Cmder in ST3 Terminal Plugin Settings and try Ctrl+Shift+T to bring up the terminal, either it won't come up at all, or show a corresponding error message.

Refer to this [issue](https://github.com/SublimeTextIssues/Core/issues/1200) for more insight.
