### ISSUE TITLE
Clink.lua can't concatenate '?'

### ISSUE THREAD

**Issue by AantonM** [cmderdev/cmder#2037]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
I've got a several projects. The version-control system I am using is mercurial. When I navigate between them some of them are ok, but the tip (master) ones, as soon as get into the project, Cmder prints out:

> C:\cmder\vendor/clink.lua:346: attempt to concatenate field '?' (a nil value)

This appears only when I am using the cmd, in a powershell tab there is no message.

I'm having the latest version of Cmder (Version status:180626).

I saw that it should be fixed by https://github.com/cmderdev/cmder/issues/1978 , but apparently it is not.

Regards,

**Comment by Stanzilla** [comment]
That version is the conemu version, make sure you download a recent Cmder zip

**Comment by AantonM** [comment]
Yep, I am sure. I saw that problem. Then I downloaded the latest one and it appear again. That's why I raised it as an issue.

**Comment by AantonM** [comment]
I got the _v1.3.11_ version from (22 Dec) and it is still reproducible.
If there is newer version I can take please let me know.

**Comment by Stanzilla** [comment]
https://ci.appveyor.com/project/MartiUK/cmder/builds/21406181/artifacts try one of these

**Comment by blghns** [comment]
I was confused with this too, but trying that artifact and also more recent builds it looks like its been fixed.

@AantonM v1.3.11 is tagged at https://github.com/cmderdev/cmder/commit/524fce25ab54f56174ecd00119928949a83e98e8 which is pull request #1999 but issue you mention #1978 is fixed in pull request #2002 which is not released yet.

Thanks @Stanzilla I think you can close this
