### ISSUE TITLE
Characters inserted when pressing arrows keys and delete key

### ISSUE THREAD

**Issue by samuelbodin** [cmderdev/cmder#2114]
Hi, I've been using Cmder for some time now and really enjoy it. I'm not sure whether this concerns Cmder or ConEmu  - sorry in advance (let me know and I'll report to conemu instead). 

### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder version 1.3.11.843
ConEmu version 180626 preview
Windows 10, WSL Ubuntu 18.04 LTS

### Description of the issue
Certain characters are inserted into the terminal window when I press any of the arrow keys or the delete key. The behavior seems random, sometimes pressing any of the mentioned buttons work as intended. So far I've only noticed this happening while in ghci (interactive Haskell interpreter) or when searching for files using kein/ctrlp.vim. (see attached screenshots). This behaviour is not encountered when running the WSL-bash by itself, only when running it via Cmder. 

GHCi 
![1](https://user-images.githubusercontent.com/19345463/60191847-40d68500-9835-11e9-9ae3-f1b054cdabfd.png)
Holding down left key for about 6 seconds
![2](https://user-images.githubusercontent.com/19345463/60191849-4207b200-9835-11e9-8c06-77f2a0a13d9f.png)
Holding down delete key for about 10 seconds
![3](https://user-images.githubusercontent.com/19345463/60191851-4338df00-9835-11e9-86ae-20ebba3d31ed.png)

### Steps to reproduce
- On WSL Ubuntu 18.04 LTS, install [HaskellStack](https://docs.haskellstack.org/en/stable/README/). 
- Create new stack project `stack new testproject simple` 
- Change directory to new project 
- Run GHCi `stack ghci`
- Once GHCi has loaded, hold down left arrow key (or the other buttons)

**Comment by daxgames** [comment]
This is not a cmder issue. if you are using wsl  you are not using cmder you are using wsl in conemu.

**Comment by kayzzen01** [comment]
I have the same problem. I uninstalled the OpenSSH client along with Windows to use only cmder tools.
This problem for me occurs when I access via ssh and use vim to edit a file. Should this happen?

Using standard Windows ssh client this problem does not occur, however I cannot export X server. Amazingly, I now decided to install the Windows OpenSSH client again and test and managed to use graphics applications. The authentication error I received was this:

`CreateProcessW failed error: 2 ssh_askpass: posix_spawn: No such file or directory Host key verification failed, jupyter notebook on remote server`

Apparently it is not a problem with cmder, but with ssh that comes with git-bash. Interestingly, this problem does not occur if you open git-bash from the executable outside the cmder, this problem does not occur.

The only problem that can happen then is that the user is not allowed to install or reinstall the Windows OpenSSH client.

Some examples of the problems were happening before I started writing this comment and reinstalling the OpenSSH client ;-)

Editing in VIM
![cmder-vim](https://user-images.githubusercontent.com/1083945/104512387-de86d600-55cc-11eb-81e9-496261d2877f.png)

Using cfdisk on the server(Using screen in text mode)
![cmder-cfdisk](https://user-images.githubusercontent.com/1083945/104512754-74bafc00-55cd-11eb-8da3-5925907fb00e.png)

I know that maybe this is not the best place to find the cause of this problem, but I thought it was important to expose some more information.

I would really like to know what's wrong when using ssh that comes with git-bash.

**Comment by kayzzen01** [comment]
I would like to share the solution which I found.
In the post above I mentioned that the connection had miraculously worked. This was because I had a ssh authentication key registered on the server. I just had to change the door to see the error again.

Searching some more I found the solution which is to use the ssh of the [MS PowerShell](https://github.com/PowerShell) project or even use what comes by default in Windows. The solution is to create a folder on drive c: called dev and an empty file inside the folder called tty.

`c:\dev\tty`

Now VIM no longer has bugs using the arrows and I can export X using VcXsrv to open graphics applications.  😄😄😄

Here are the references:
https://unix.stackexchange.com/questions/207365/x-flag-x11-forwarding-does-not-appear-to-work-in-windows
https://github.com/PowerShell/Win32-OpenSSH/issues/1088
https://stackoverflow.com/questions/51866922/ssh-keygen-does-not-find-ssh-askpass
https://github.com/PowerShell/Win32-OpenSSH/issues/966
https://github.com/PowerShell/Win32-OpenSSH/issues/1515
