### ISSUE TITLE
tmux layout rendering issue in {cmd::Cmder} mode

### ISSUE THREAD

**Issue by lyhistory** [cmderdev/cmder#2185]
### Purpose of the issue
- [Y] Bug report (encountered problems/errors)

### Version Information
ConEmu 180626 preview
Windows 10 Pro

### Description of the issue
open console in {cmd::Cmder} mode, using tmux, the layout rendered wrongly very often,
please refer to the screenshot below, by right the cursor should be always above the green status bar, but sometimes it even rendered with multiple duplicated status bar;
I workaround this issue by using {bash::bash} mode, so far it works fine with this mode.
![image](https://user-images.githubusercontent.com/1522513/66463443-a16d9300-eaaf-11e9-94d4-3d3fea5ea6b3.png)

**Comment by daxgames** [comment]
how did you install tmux so we can try and duplicate this.  Chances are though this is something you need to report [here](https://github.com/Maximus5/ConEmu/issues)

**Comment by lyhistory** [comment]
> 
> 
> how did you install tmux so we can try and duplicate this. Chances are though this is something you need to report [here](https://github.com/Maximus5/ConEmu/issues)

you can install it with:
```yum install tmux```
or manually follow this gist:
https://gist.github.com/pierreprinetti/86fbcd28e5cc1b3e0b9b762e4c12fad2
actually recently everything working fine and I failed to reproduce it at the moment, will report it if it shows up again.
thanks

**Comment by daxgames** [comment]
This is not a cmder issue.  If it happens again you need to report it to the developer of conemu

**Comment by didw** [comment]
I have same issue.
It always happened when I use Ubuntu18.04 + tmux + cmder.
It's find when I use putty.
![cmder_tmux_issue](https://user-images.githubusercontent.com/7973071/70036719-ac98f700-15f8-11ea-98f5-4e364393aaaf.JPG)

**Comment by daxgames** [comment]
@didw This is not a cmder issue. If it happens again you need to report it to the developer of conemu

**Comment by JahooYoung** [comment]
I have the same issue.

It only happens when using cmder. I use Windows Terminal for testing and it turns out the same, so I think it is not a issue of conemu.

This is WindowsTerminal(v1.0) + WSL + ssh + tmux:
![image](https://user-images.githubusercontent.com/12966985/83422438-1edd7d80-a45c-11ea-911c-a5e052991bc9.png)

This is WindowsTerminal(v1.0) + cmd + ssh + tmux:
![image](https://user-images.githubusercontent.com/12966985/83422495-3288e400-a45c-11ea-81fb-60b55be072de.png)

This is WindowsTerminal(v1.0) + cmder + ssh + tmux:
![image](https://user-images.githubusercontent.com/12966985/83422521-3e74a600-a45c-11ea-9e6c-ded1f97b01ee.png)

**Comment by zldrobit** [comment]
I install cmder 1.3.19 to replace cmder 1.3.12, and the problem disappears. Interestingly, both cmder 1.3.19 and cmder 1.3.12 use ConEmu 210912.
