### ISSUE TITLE
Creation of an alias with 'DO'

### ISSUE THREAD

**Issue by MiroslavMikus** [cmderdev/cmder#2200]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

160626 preview

### Description of the issue

Hey, I'm trying to create a new alias:

> alias fedir=FOR /d %G in (%cd%\*) DO (cd %G & $* & cd..)

This will lead to a syntax error:

> "DO" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

**Q: Is there something I did wrong wit the alias command?**
FYI: If I copy the alias to the __user_aliases.cmd__ manually:

> fedir=FOR /d %G in (%cd%\*) DO (cd %G & $* & cd..)

The alias itself works just fine

>Example: fedir git status

Thank you in advice

**Comment by daxgames** [comment]
Some more complex aliases may need to be added directly to the file.

**Comment by MiroslavMikus** [comment]
Would be possible to add support for escaped aliases?
Example:

> alias fedir="FOR /d %G in (%cd%*) DO (cd %G & $* & cd..)"

OR

> alias fedir='FOR /d %G in (%cd%*) DO (cd %G & $* & cd..)'

**Comment by daxgames** [comment]
The problem is the alias command is a `*.cmd` and the alias you are trying to add is lower level command code that is interpreted and executed instead of being used as input nothing we can do about that.

A LOT of work has been done to try and make the `alias` command as functional as possible.  It may be possible to do what you ask but more trouble than its worth IMHO.

If you want to try to make it better PRs are welcome.

If not just edit the file.
