### ISSUE TITLE
sftp.exe command text becomes invisible when type tab or arrow key

### ISSUE THREAD

**Issue by linqh1** [cmderdev/cmder#2234]
Version: 2019.10.12

When I found this problem, I thought is was caused by ConEmu. So I open a  issue(https://github.com/Maximus5/ConEmu/issues/2038)  for ConEmu.

But I when test sftp.exe in D:\Program Files\cmder\vendor\git-for-windows\usr\bin\sftp.exe using Windows cmd, the problem still not be resolved.
![image](https://user-images.githubusercontent.com/42435177/71340678-8d0b4380-2592-11ea-9303-ef0692f37330.png)

And when I change to babun's sftp.exe, everything work fine.
![image](https://user-images.githubusercontent.com/42435177/71340704-9ac0c900-2592-11ea-9922-d271e2f09e1d.png)

So I doubt that there are some problem in D:\Program Files\cmder\vendor\git-for-windows\usr\bin\sftp.exe

**Comment by linqh1** [comment]
Issue reproduce step:
1. login with %YourInstallPath%\cmder\vendor\git-for-windows\usr\bin\sftp.exe
2. type 'get ' and any file prefix like 'get cmder.'
3. type tab to show full name
then you will found the characters you type before is disappeard. But when you type enter key, sftp still can recognize those disappeared commands, whose can not even be copied.

(using arrow key to select history command can also reproduce this issue)

**Comment by linqh1** [comment]
Found another key:Backspace

**Comment by daxgames** [comment]
Does this happen in a normal windows cmd.exe prompt outside cmder?  If so its not a cmder issue.

**Comment by linqh1** [comment]
> Does this happen in a normal windows cmd.exe prompt outside cmder? If so its not a cmder issue.

Yes, it does. 
It seems that there are some problem in cmder\vendor\git-for-windows\usr\bin\sftp.exe.
I don't know where I should report this issue, so I open a issue for cmder

**Comment by daxgames** [comment]
It is git for windows. We just package it with our stuff so you could report it there

**Comment by spikendoo** [comment]
### Has this been reported to the git bug/mailing list? 

I don't see it. [Searched for the issue on git mailing list](https://groups.google.com/forum/?fromgroups#!searchin/git-users/sftp%7Csort:date)

The problem **persists in Git v2.26 (2020-03-22) -- 4 months later**

* I concur this is NOT a cmder bug (so wrong forum to report it)
* I am not reporting it here. I am providing an update here simply because this is the only reference to the problem I am seeing.

The **update** is *"it doesn't seem to have been reported"* so its not likely to get fixed.

Strange. This is pretty annoying. (sorry for the rant)

I presume people just use a different sftp option on windows instead of reporting the problem. 
1. sftp from Windows 
2. putty, etc

**Comment by jasonbrianhall** [comment]
It's 2023 and the issue is still there.

**Comment by DRSDavidSoft** [comment]
@jasonbrianhall We have enabled the [msys connector](https://github.com/Maximus5/ConEmu/issues/2038#issuecomment-568368759) on recent builds of Cmder. Download the latest version and extract it to a new path so the latest `ConEmu.xml` file is created, then test again. If the issue still persists, it seems that the `sftp.exe` from the [babun project](https://babun.github.io/) works instead of the one provided by the bundled Git in Cmder. In that case, modify your PATH so that the executables from babun gets prepended to PATH first (and git last) so babun's `sftp.exe` is used instead.
If none of these helped, post a reply so we can investigate.
