### ISSUE TITLE
Reset setting default lose Cmder

### ISSUE THREAD

**Issue by minhducykk** [cmderdev/cmder#2240]
I have a small problem resetting install default, Cmder is lost and I cannot use the Linux commands anymore. And I don't know how to reset Cmder either. Please help

**Comment by daxgames** [comment]
The easiest way would be to delete `%cmder_root%\config\user-conemu.xml` and `%cmder_root%\vendor\conemu-maximus5\conemu.xml` then start/restart `Cmder.exe`

**Comment by daxgames** [comment]
Reset default in conemu restores default conemu, a component of cmder, to default.  This is, unfortunately, expected and unavoidable behaviour.

**Comment by minhducykk** [comment]
Thank you. It work good.

**Comment by endolith** [comment]
>  This is, unfortunately, expected and unavoidable behaviour.

You could at least warn about this much more visibly?

**Comment by chrisant996** [comment]
> > This is, unfortunately, expected and unavoidable behaviour.
> 
> You could at least warn about this much more visibly?

That would be nice.  But unfortunately it's not really possible to warn when using the ConEmu command to restore ConEmu default configuration.
- Cmder is a bundle of scripts and configuration that integrates some other things (ConEmu, Clink, git, etc).
- ConEmu doesn't know about Cmder and doesn't involve or consult Cmder when a user instructs ConEmu to restore default configuration.

It's not "Cmder default configuration" that's being restored -- it's _ConEmu_ default configuration that's being restored.  And ConEmu default configuration doesn't include Cmder because ConEmu doesn't know anything about Cmder.

However, maybe there's a way that Cmder.exe could detect on launch when configuration has been removed, and warn at that point and/or ask whether to restore it.

**Comment by endolith** [comment]
I was just thinking of a text warning in the .zip file or on the website, but that would be even better.

**Comment by endolith** [comment]
Also, deleting those xml files restores most of the functionality, but I could swear there used to be a "Cmder here" Explorer integration?  Now it just says "Conemu here".  Am I imagining things? Is there a way to get that back?
