### ISSUE TITLE
startup scripts (under profile.d) will be executed twice.

### ISSUE THREAD

**Issue by ikhosravi** [cmderdev/cmder#2291]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Version 1.3.14.982

Windows 10 Pro 18363

### Description of the issue

I put a sample "X.cmd" script under my profile.d folder so it will be started every time I open a new session on Cmder. but the point is the script will be executed twice. as I see the result twice.
even if I put a simple echo command in it, I will see the output twice.

**Comment by daxgames** [comment]
@ikhosravi are you using Cmder or Cmder Mini.  If you are using Cmder Mini do you have Git installed and if so where?

You could try posting the output of the `cmder_diag.cmd` script.

You could also add a `/d ` after `init.bat ` to the task starting cmder to get additional debug output and post it.

**Comment by ikhosravi** [comment]
@daxgames
I'm using Cmder and not mini.
here is cmd_diag output:
[diag_output.txt](https://github.com/cmderdev/cmder/files/4434687/diag_output.txt)

init.bat /d
[init-debug.txt](https://github.com/cmderdev/cmder/files/4434742/init-debug.txt)

**Comment by daxgames** [comment]
@ikhosravi You are correct you are using Cmder but jast as an FYI you also have Git installed separately.  This is perfectly fine since Cmder will automatically use your user installed Git if it is newer than the Git embedded inside Cmder.

As for your issue I cannot reproduce it using the Cmder Full 1.3.14.982 release with User Git installed exactly as you are using.

Have you made any edits to Cmder files inside the vendor folder or made any other adds to the config folder?

Try this 1.3.15-pre [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by WildOrangutan** [comment]
Can reproduce on 1.3.14.982 (mini). Completely fresh install, since I started using Cmder today.

In my case, script is executed 3 times tough. Same also happens with `user_profile.cmd` script.

**Comment by daxgames** [comment]
@WildOrangutan see the post above.

**Comment by WildOrangutan** [comment]
1.3.15 doesn't have that issue any more 👍
