### ISSUE TITLE
New console created as cmd.exe instead of cmder

### ISSUE THREAD

**Issue by Makishima** [cmderdev/cmder#2310]
Hello! 
My tasks setup looks like that
![изображение](https://user-images.githubusercontent.com/5548003/80573781-4c707a80-8a09-11ea-8d5c-d8f611f712c0.png)
But when I double click on tab bar there is always cmd on first place
![изображение](https://user-images.githubusercontent.com/5548003/80574684-f8669580-8a0a-11ea-8a00-db440d74e9b5.png)
How I can change that behavior?
![изображение](https://user-images.githubusercontent.com/5548003/80574905-601ce080-8a0b-11ea-8ef1-b2063782d8d0.png)

**Comment by daxgames** [comment]
@Makishima I don't really understand the question.

If you are asking why is `cmd.exe/k ...` first in the `Create new console` dialog then that is a question for the Conemu developer @Maximus5.  My assumption has always been was that that comes from the currently launched task or possibly the default startup task.

As for the difference in icon on the tab bar, that is probably because one tab was launched from a task, `cmd::cmder`, that specifies an alternate icon and the other was launched from the `Create new console` using the command on the first position that you are asking about that does not specify an icon.

**Comment by Makishima** [comment]
Thanks
