### ISSUE TITLE
Why italics

### ISSUE THREAD

**Issue by mmmatjaz** [cmderdev/cmder#2321]
This is not really an issue, just a question:
Sometimes, when I'm in a folder that is a git repository, the branch label becomes italic, e.g.:
_(master -> origin)_  
What does that mean?

**Comment by daxgames** [comment]
My Cmder git status prompt has never been in italics so I can't answer the question.

**Comment by noopole** [comment]
I just had the same behaviour.
Example (with a console split): 
![image](https://github.com/cmderdev/cmder/assets/11869690/dfb9ba87-231e-456d-a754-5db8526e23d6)

**Comment by DRSDavidSoft** [comment]
Hi, sorry for the late response.

After digging into the [FaqBoldItalic](https://conemu.github.io/en/FaqBoldItalic.html#bold-italic-underlined-cmd-prompt) and [AnsiEscapeCodes](https://conemu.github.io/en/AnsiEscapeCodes.html#SGR_Select_Graphic_Rendition_parameters) pages per ConEmu documentation to make sure that the `ESC [ 3 m` sequence is used to make the text **Italic** I looked into the code that is used to display the prompt.

@noopole Your screenshot helped me understand that the `git prompt` part of the Clink shell must be outputting this italic sequnce somewhere, so I opened the [clink.lua](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua) code to investigate, sure enough the `get_dirty_color()` function has this sequence, it even has a comment!

https://github.com/cmderdev/cmder/blob/a2e4884ea1870245a82e5a8a805f7cc7a14fe609/vendor/clink.lua#L41

In other words, this style is used to indicate `dirty` repositories. Running [`git status`](https://git-scm.com/book/en/Git-Tools-Stashing-and-Cleaning) will give more information about the repository state, and here is [the documentation](https://git-scm.com/book/en/Git-Tools-Stashing-and-Cleaning) in git that describes the "dirty" state.

Under the hood, Cmder uses the following command to detect the "dirty" state:
```
git --no-optional-locks status --porcelain
```

Also, note that you can customize the "yellow" color and the "italics" style by editing the [`cmder_prompt_config.lua`](https://github.com/cmderdev/cmder/blob/master/vendor/cmder_prompt_config.lua.default) config file.

Now here's the part that is bugging my mind, in the screenshot that is shared, it appeared that the "italics" style continues to the next line, and even passes the `λ` symbol.

This should be impossible in the Cmder builds after the #2772, which is a PR I specifically made to fix the "bleeding" issue back in 2022, yet your screenshot appears to be recent.

Please ensure that you are using the latest version of Cmder, in which case, the italic style is used by design to indicate the "dirty" repositories, yet it must **only** be applied to the git repo part, not everything that comes after it. 

### Conclusion

- If you are only curious about why this happens, the reason is to indicate the "dirty" repo state.

- If you want to alter it or disable it, edit the `cmder_prompt_config.lua` file and use your own custom style.

- If everything _after_ the git prompt _also_ becomes Italic, please update the Cmder to the latest version, and if it persists, please open an issue so I can investigate.
