### ISSUE TITLE
Global window shortcut key Printscreen not working

### ISSUE THREAD

**Issue by s0j0urn** [cmderdev/cmder#2336]
Hi

I have registered my printscreen key to invoke a windows screenshot utility. However, whenever cmder is in focus and I press printscreen key it doesn't let that screenshot utility to be invoked. I believe it is capturing the printscreen key somehow but I am unable to find the related setting.

Will you guide me in the right direction?

**Comment by daxgames** [comment]
@s0j0urn I can't find it either but have you tried <kbd>Windows</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> to launch the new `Snip & Sketch` tool.

**Comment by ProoFFie** [comment]
Why is this closed? This is an actual issue, PrtSc shortcut is suppressed and Win+Shift+S is not an option as I use ShareX which is a lot more customizable.
What happens is PrtSc takes a fullscreen snapshot of your desktop (can easily check it by pasting into Paint) instead of relying on software that modifies the PrtSc behavior. No solution found in settings.
