### ISSUE TITLE
Sublime Text Integration 

### ISSUE THREAD

**Issue by LonginKandinsky** [cmderdev/cmder#2365]
Hello

I'm having hard time with integrating sublime text by following guide https://github.com/cmderdev/cmder/wiki/Seamless-Sublime-Text-3-Integration

cmder can't recognize the subl command. I have double checked every step in guide...

Locations:
C:\tools\cmder (version 191012)
C:\tools\cmder\vendor\sublime (build 3221)

I added  to C:\tools\cmder\config\user_aliases.cmd line
alias subl="%CMDER_ROOT%\vendor\sublime\sublime_text.exe" $*
:: alias subl="C:\tools\cmder\vendor\sublime\sublime_text.exe" $*

everytime when cmder is started I got warning message
"Invalid macro definition."
but I'm unable to solve it.

**Comment by daxgames** [comment]
@remove the quotes

**Comment by daxgames** [comment]
I don't like to put things in `%cmder_root%\vendor` because this area is 'owned' by the Cmder project team in that it SHOULD only be updated/added to by us.  The wiki should probably be updated.

I put things I want to add to my Cmder install that I want to follow it around and be portable into `%cmder_root%\bin`.

I did the below and all worked as expected:

1. Downloaded and expanded Sublime Text 3 Portable to `%cmder_root%\bin\sublime_text` 
2. `alias subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $*`
3. `subl`
4. Sublime Text launched in a separate window.

There is a problem with this alias though.  It is not portable, see below:

```
~\Cmder(1.3.16-fixes) $ alias subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* 

~\Cmder(1.3.16-fixes) $ alias subl
subl="C:\Users\dtgam\Cmder\bin\sublime_text\sublime_text.exe" $*
```

If you move Cmder to another folder the `subl` alias will fail.

Below is better:

```
~\Cmder(1.3.16-fixes) $ alias subl="^%CMDER_ROOT^%\bin\sublime_text\sublime_text.exe" $*

~\Cmder(1.3.16-fixes) $ alias subl
subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $*
```

I also manually added Sublime Split Pane aliases to `%cmder_root%\config_user_aliases.cmd`

```
subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $*  
sublv="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50H
subls="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50V
```

Typing `subl`:

![image](https://user-images.githubusercontent.com/7318053/90312495-eaae2080-ded2-11ea-9ce9-f19092d241d7.png)

Typing `sublv`:

![image](https://user-images.githubusercontent.com/7318053/90312420-50e67380-ded2-11ea-8db0-d94e17526e16.png)

Typing `subls`:

![image](https://user-images.githubusercontent.com/7318053/90312464-ade22980-ded2-11ea-8c52-a4ebb2e8ce60.png)

**Comment by daxgames** [comment]
@LonginKandinsky 

I see your issue, you added:

```
alias subl="%CMDER_ROOT%\vendor\sublime\sublime_text.exe" $*
```

Only add:

```
subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $*  
sublv="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50H
subls="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50V
```

**Comment by daxgames** [comment]
I also updated the [Wiki]( https://github.com/cmderdev/cmder/wiki/Seamless-Sublime-Text-3-Integration)
