### ISSUE TITLE
Ctrl+BackSpace Shortcut doesn't work

### ISSUE THREAD

**Issue by BennyAlex** [cmderdev/cmder#2379]
### Purpose of the issue 
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder: 1.3.14.982 & 1.3.16
Windows: 19041.388

### Description of the issue
The shortcut fpr deleting left side of words doesn't work. I know this is a normally a conemu problem, but I tried conemu (latest version) and there it works fine. So either the version cmder is outdated or the bug is introduced by cmder itself.

**Comment by daxgames** [comment]
@BennyAlex 

Works for me in Cmder 1.3.16.

**Comment by BennyAlex** [comment]
@daxgames 

I downloaded latest zip and tried, but still doesnt work.

Maybe its because my language & keyboard using german layout?

But as I said, in conemu it does work...

**Comment by daxgames** [comment]
Try this: https://ci.appveyor.com/project/MartiUK/cmder/builds/34805231/artifacts

**Comment by daxgames** [comment]
The keyboard layout could be causing an issue.  Cmder has config that tries to set locale but not sure of the effects of the German layout.

**Comment by BennyAlex** [comment]
@daxgames 
In this build the word jumping does work, but word-deletion not

**Comment by borup3** [comment]
This hasn't worked for years. A release back in 2017 or 2018 changed it to Alt+Backspace. I've been staying on that version ever since. I just updated because I'd forgotten about it, and now I'm extremely annoyed.
The shortcut still says Ctrl+Backspace. The keyboard manager still says Ctrl+Backspace. But it's Alt+Backspace. It's been like this for years. Using ISO UK layout but it's the same with ANSI layout on my laptop. Ctrl+Backspace is just Backspace. Delete word left of cursor is Alt+Backspace.

**Comment by BennyAlex** [comment]
Ah okay, but in conemu it does work. 
@daxgames maybe the hardcoding can be changed?

**Comment by daxgames** [comment]
As I said Ctrl+Backspace works as specified with fresh download of 1.3.16.  we hard code nothing.  We have a default config file for Conemu but you are free to change any setting and remap any keystrokes after initial install.

**Comment by daxgames** [comment]
@borup 

You should be able to upgrade by following [this](https://github.com/cmderdev/cmder#upgrading)

`Cmder.exe` will recognize that the `%cmder_root%\vendor\comemu-maximus5\conemu.xml` is not there and copy your `%cmder_root%\config\user-conemu.xml` that has your Conemu settings in it and use it to launch Conemu.

**Comment by borup3** [comment]
> As I said Ctrl+Backspace works as specified with fresh download of 1.3.16

Okay. I guess we're oblivious to what keys we're pressing and it's human error.

Time to find a new shell.

**Comment by daxgames** [comment]
@borup3 I am not telling you to find a new shell.  I try to be very responsive to issues on here as time allows.

I tested this when the issue was reported and did not see the issue but I redownloaded 1.3.16 just now and am seeing it now for some reason .  I can't explain why I am seeing it now and not then.

I have figured out the problem is with another component of Cmder that we download and repackage unmodified.  

`clink` is the package responsible for making Cmder more like Linux by adding readline capability.

If Cmder is initialized without `clink` then `ctrl+backspace` works as expected and deletes the word to the left of the cursor.

Unfortunately `clink` is a dead project so this probably will not be fixed.

**Comment by daxgames** [comment]
Cmder 1.3.3+ used a Windows 10 compatible version of Clink so that explains why @borup3 has success with 1.3.2.  @borup3 I assume you are not using Windows 10?  If you are what version are you using?  Unless it if very old other things should be broken like Cmder aliases.

**Comment by borup3** [comment]
I am using the latest version of Windows 10. Ctrl+Backspace has been broken since the aforementioned Cmder release from 2016.

**Comment by daxgames** [comment]
@borup3 Do Cmder aliases work for you?  Open Cmder and type `e.`.  It should open an Explorer window in the current path.

Microsoft created in the Fall Creators Update whenever it came out.  MANY users complained for a long time about aliases not working.  Clink had to be updated in Cmder 1.3.3 to resolve the issue.

**Comment by daxgames** [comment]
The problem appears to be the combination of Clink 0.4.9 and newer Conemu builds than what is included in Cmder 1.3.2.  I can get `Ctrl+Backspace` to work doing the following:

1. Cmder 1.3.16 extracted.
2. Rename `%cmder_root%\vendor\conemu-maximus5` to  `%cmder_root%\vendor\conemu-maximus5-1.3.16`
3. Copy  `vendor\conemu-maximus5` from Cmder 1.3.2 into `%cmder_root%\vendor`
4. Run Cmder.

`Ctrl+Backspace` works as expected.

Cmder includes both of these packages downloaded from their maintained releases and repackages them unaltered for redistribution as part of Cmder.  

Using Conemu update functionality from this modified state to the Conemu Preview 200713 breaks `Ctrl-Backspace`.

**Comment by daxgames** [comment]
Something changed in [this](https://github.com/Maximus5/ConEmu/releases/tag/v17.01.18) release of Conemu that breaks `Ctrl+Backspace` when used with Clink 0.4.9.  the previous[relese](https://conemu.github.io/blog/2016/12/06/Build-161206.html) fwork correctly.

**Comment by borup3** [comment]
Thank you for investigating. I've applied your 4 steps to fix it and that indeed fixes the problem :).

**Comment by daxgames** [comment]
@borup3 thank you for the clues on where to look.
