### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by captain-majid** [cmderdev/cmder#2393]
I want all the line to be in one line, propbably with scrollbars, not to extend to another line this, how to do it please.
https://i.imgur.com/XShBly3.png

**Comment by farreros** [comment]
Hello, any improve about this issue. Because i think is really interesting for comand line tools with text output.

**Comment by chrisant996** [comment]
This is not a Cmder request -- it's a ConEmu request.

But it isn't really a ConEmu request, either -- it's a Windows OS request.  ConEmu can't do anything about this, because ConEmu only paints the console content that the OS gives it, and the OS wraps console output.

For more info see https://github.com/microsoft/terminal/issues/6895 and the various linked issues, and links to similar topics for the gnome terminal emulator (and maybe other terminal emulators, too).  (The Windows Terminal team owns both the basic console subsystem in the Windows OS and _also_ the Windows Terminal app.)
