### ISSUE TITLE
Bug in cmder grep

### ISSUE THREAD

**Issue by vschulz** [cmderdev/cmder#2414]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.16.1035

### Description of the issue

When I use grep with a pattern like ^20, it is ignoring  the ^.  This does not happen on the version of grep in ubuntu 20

cat test.txt
20      should be found 1
1       should not be found     20

grep  ^20 test.txt --color
20      should be found 1
1       should not be found     20

**Comment by daxgames** [comment]
`grep` is not a part of Cmder.  `grep` is a part of Git for Windows that Cmder redistributes.  `grep` behaves exactly the same in a cmd.exe prompt as it does in a cmd.exe based Cmder session so this is not a Cmder issue

See below:

![image](https://user-images.githubusercontent.com/7318053/98369729-68cc2000-2007-11eb-93f6-cadf3c40fbd0.png)

It does hoever work just fine in a Git Bash Cmder Session:

![image](https://user-images.githubusercontent.com/7318053/98370025-e2640e00-2007-11eb-8dbb-670ac5a6eed0.png)

This is probably due to it being a part of Git Bash.

you should report the error to the Git for Windows Team.
