### ISSUE TITLE
Switch to chrissant996's fork of clink

### ISSUE THREAD

**Issue by nikitalita** [cmderdev/cmder#2417]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information
N/A

### Description of the issue
The current version of clink that cmder uses is defunct and hasn't been updated in two years. @mridgers seems to have either abandoned the project or DICE has sentenced him to the Swedish coal mines. Either way, it is now unsupported, and will eventually break with the coming Windows insider builds (see #2403). Even though I have made patches to fix this, these are increasingly fragile, and will likely keep breaking with new Windows builds. It's going to be very difficult moving forward on this version of clink.

@chrisant996 is currently working on a [fork of clink](https://github.com/chrisant996/clink) with new features and improved stability.It has recently changed to use Microsoft Detours for hooking, and this means that it will be compatible with future builds of Windows without the need for constant patching.

I believe that Cmder's best bet going forwards is to switch to this fork, as this will likely be the only fork of clink going forward that is actively supported.  @daxgames has already mentioned this as a possibility [(here)](https://github.com/cmderdev/cmder/issues/2347#issuecomment-703031573). @chrisant996 has said that currently Lua compatibility is about at the same point it will be for release [(here)](https://github.com/chrisant996/clink/pull/14#issuecomment-723728453). I recommend that we start the process of adapting the current scripts to work with it now, and see how extensive the changes needed will be.

**Comment by daxgames** [comment]
I agree completely its just a matter of time.  We looked at clink 1.x.x before @chrisant996 started working on it.  We will move to it most likely as compatibility comes around and as time permits.

**Comment by chrisant996** [comment]
I can help, too.

**Comment by MartiUK** [comment]
Thanks @chrisant996

**Comment by chrisant996** [comment]
Hm:

**The good news** is that Clink 1.1.2 seems to essentially work when dropped on top of cmder/vendor/clink, with only a couple tiny tweaks to Cmder's lua scripts.  There are some minor bugs in the clink-completions scripts, and I'd like to contribute fixes for those but I'm not sure the best way to go about that.  Maybe I can see about fixing the scripts in a version-agnostic way, so that the fixes can just go into the master clink-completions repo.

**The bad news** is that Cmder is eating all output the Clink 1.1.2 writes to stdout.  Output via `WriteConsoleW()` reaches the console screen buffer.  But output via `WriteFile()` to the stdout handle gets eaten and never reaches the console screen buffer.

However, stdout from Clink 0.4.9 works fine in Cmder, and stdout from Clink 1.1.2 works fine in stock ConEmu.

So it seems that Cmder doesn't like something about Clink 1.1.2, but I'm having trouble figuring out what that might be.  I don't see anything obvious in `OnWriteFile()` in src/ConEmuHk/hkStdIO.cpp, but I'll keep looking.

Could someone familiar with Cmder internals share any thoughts about where to investigate?

**Comment by daxgames** [comment]
@chrisant996 thanks for the help it is much appreciated.  

I am not sure how Cmder could cause this.

Cmder provides a set of init scripts for cmd, bash, and powershell sessions that ties together various packages.  We redistribut conemu and other packages in the `vendor` folder unmodified other than some settings differences.

**Comment by MartiUK** [comment]
@chrisant996 There might be some incompatibilities with conemu and clink 1.1.2, have you tried using it without any of cmder's scripts?

**Comment by chrisant996** [comment]
Stock ConEmu seems to be working great with Clink 1.1.2.

I've been reviewing the sources to find where it has special knowledge about Clink, and it does look like it will need some minor adjustments, but overall it seems to be working great (i.e. latest ConEmu hosting latest Clink).

**Comment by chrisant996** [comment]
Clink 1.1.4 is a good version to start integrating into Cmder.  It should be drop-in backwardly compatible with existing Clink *.lua scripts.

The `init.bat` file in Cmder seems to have two problems:
1. It has some inefficiencies that make it very slow. It recursively invokes lib_base.bat 83 times, for example (I used `set /a` to count how many times it gets invoked during init.bat). I don't know yet how much of the slowness is coming from the *.bat files, versus invoking git and other tools, but it looks like some degree of improvement is possible by consolidating *.bat files.
2. Something inside the init.bat file seems to be causing an intermittent problem where stdout output from Clink (and more importantly the Lua engine inside Clink) gets accidentally suppressed. When I get a chance I'll look deeper into that.

Re: suppressed output -- There are a few lines in init.bat where if they get commented out then output seems to works reliably. Clink has no problems running in conhost or ConEmu or Microsoft Terminal. The problem only occurs when invoked as part of Cmder, and only if the init.bat file is used (i.e. launching Clink inside Cmder without the init.bat file works fine). So the problem seems to be specific to Cmder.

**Comment by daxgames** [comment]
@chrisant996 I did a test today where I replaced Clink 0.4.9 with the referrenced Clink version above and it did not work at all.  When I launched Cmder I saw a flash of another window

**Comment by chrisant996** [comment]
Hm. I'll look into it, thanks for trying it and reporting your experience.

**Comment by daxgames** [comment]
Thanks.  I can't explain the 'Invalid macro definition' that I get now.

**Comment by daxgames** [comment]
AND I have `lib_base` calls down from '63' to '10'. 👍

**Comment by chrisant996** [comment]
> @chrisant996 I did a test today where I replaced Clink 0.4.9 with the referrenced Clink version above and it did not work at all. When I launched Cmder I saw a flash of another window. Then the ConEmu Window disapeared. I assume it might have been something to do with anti-virus/malware protection on my system because it removed my init.bat.

Today I downloaded a fresh copy of Cmder, unzipped it to a new directory, and copied Clink 1.1.5 into vendor\clink.  Everything seems to be working great.  I suspect that you may have indeed experienced interference from well-meaning anti-virus/malware protection.  Does the protection suite have an activity log that you can check to see if it lists any recent actions?

> I reverted the change back to Clink 0.4.9, checked out the init.bat from Git and all is back to normal except for an `Invalid macro definition.` when starting Cmder that I have never seen before.

I don't know what that could be.  Maybe the protection suite deleted another file as well?  Can you compare the malfunctioning Cmder installation to a known good copy?  (E.g. using a graphical diff tool to compare the file trees and file contents.)

I've scanned Clink, ConEmu, Cmder, Windows SDK, and \Windows\System32 for any occurrences of ASCII or Unicode "Invalid macro" and could find nothing.  Just a handful of unrelated hits in some system files that have to do with setting up an OS installation and stuff like that.

> AND I have lib_base calls down from '63' to '10'. 👍 Time savings is negligible.

Great!  Nice work, and sorry that it wasn't more fruitful.  So probably the slow launch time is coming primarily from stuff that `fast_init` skips?  Maybe there's a way to optimize (or cache results from) those steps.

**Comment by daxgames** [comment]
@chrisant996 I am sorry I just found the source of the invalid macro.  Somehow a stray 'B' got into my `user_aliases.cmd` file.

`init.bat` optimization speed improvements with Clink 0.4.9:

![image](https://user-images.githubusercontent.com/7318053/101267409-5b997280-3726-11eb-9346-87ff7c009abe.png)

Speed improvements are achieved by replacing the function libs in `%cmder_root%\vendor\lib\*.cmd` with a `%cmder_root%\vendor\[function].cmd` file for each function.  Top is my current dev branch, bottom is master.

I will try the Clink 1.1.5 and report back.

**Comment by daxgames** [comment]
Mainly fast init modifies the path without checking if the new folder is already in the path.  This is where most if not all of the speed gain is for fast init.  It might be possible to optiimize this code but not sure it is worth the effort given the speeds shown above.

It also does not attempt recursive path add inder `%cmder_root%\bin`.  Default is one level anyway so no speed gain there.

**Comment by chrisant996** [comment]
> @chrisant996 I am sorry I just found the source of the invalid macro. Somehow a stray 'B' got into my `user_aliases.cmd` file.

Ah cool, glad to hear you were able to track it down!  (Mysteries are unsettling... 😉)

> `init.bat` optimization speed improvements with Clink 0.4.9:
> ...
> Speed improvements are achieved by ...

Very nice!

> I will try the Clink 1.1.5 and report back.

Sounds good.  I just did some research on code signing certificates for individual developers.  If you don't have a business and business credit file, then although prices appear cheap, there is apparently a hidden cost:  you need to hire an attorney to draw up legal documents to "prove" who you are.  It sounds like it would cost me around $2,000 total to cover code signing for 2 years.  That's a little steep for a not-for-profit side project.  I have some limited attorney benefits/discounts through my day job, and maybe that will be able to reduce the price into an acceptable range, I don't know.

Code signing might not be a realistic option, after all, though.  😕

I'm not sure how to mitigate the interference you encountered.  Any ideas?

**Comment by daxgames** [comment]
Its not uncommon.  We usually tell people it is a false positive and move on.  What is uncommon is the action taken with no notification from the AV program.

My antivirus has gotten more aggressive apparently ans is even doing the same on Clink 0.4.9.  I setup an exception for init.bat and it seems fine.

**Comment by chrisant996** [comment]
> Mainly fast init modifies the path without checking if the new folder is already in the path. This is where most if not all of the speed gain is for fast init. It might be possible to optiimize this code but not sure it is worth the effort given the speeds shown above.

I used `rem` to simply comment out the `%lib_console% debug_output` lines in `lib_path.cmd`.  Doing only that gained a **0.39 sec** reduction in execution time.  The amount of invoking of scripts within scripts might be incurring a higher than anticipated overhead cost.

Invoking any script means a `CreateFile()` call, which isn't cheap.  To find a label in a script, CMD must read and parse the script at least up to the label.  The more script invocations there are (especially e.g. in a recursive loop) the larger the multiplier on that cost.

![image](https://user-images.githubusercontent.com/17440311/101269549-bfbb3700-3724-11eb-83f6-4848f0575d21.png)

On the left is with the lib_console invocations rem'd out.
On the right is an unmodified cmder.

**Comment by chrisant996** [comment]
By the way, there is a significant performance difference between the following two patterns:
<br/>

_Test before calling:_
```bat
if %var% == 1 call some_script
```
<br/>

_Calling unconditionally:_
```bat
call some_script
```
With the test factored to happen inside some_script.bat:
```bat
if not %var% == 1 goto :eof
```

**Comment by daxgames** [comment]
Thanks

**Comment by chrisant996** [comment]
Oh, but I realized it's possible that the 0.39 sec reduction is mostly already covered by the 63->10 calls change, which I don't have in my workspace.

**Comment by nikitalita** [comment]
> Sounds good. I just did some research on code signing certificates for individual developers. If you don't have a business and business credit file, then although prices appear cheap, there is apparently a hidden cost: you need to hire an attorney to draw up legal documents to "prove" who you are. It sounds like it would cost me around $2,000 total to cover code signing for 2 years. That's a little steep for a not-for-profit side project. I have some limited attorney benefits/discounts through my day job, and maybe that will be able to reduce the price into an acceptable range, I don't know. I could maybe register with dnb.com, but it's unclear how much that $229 cost would help with the background checks for an OV code signing certificate, and I don't really want to create a DBA because last time I did that the IRS started wanting a bunch of additional documentation and filings -- which is a pretty undesirable burden for a not-for-profit side project.
> 
> So code signing might not be a realistic option, after all. 😕

Yeah, I had been thinking about this problem for a while and ran into the same issues you have. While you can tell Microsoft to add an exception for you, it's going to be a continuing problem for each new release, and EV code signing is expensive and time consuming to get and mainstain. It's going to continue to bite open source projects like this until we come up with a solution; perhaps a bunch of open source projects on windows could pool their resources and start a shell company?

**Comment by chrisant996** [comment]
I anticipate an official release before Christmas.

Holiday vacation time has been fun.  🙂  v1.1.7 is essentially a release candidate.  I've met all of my original core priorities for an initial release.  I'd hoped to have CUA Selection working, i.e. shift+arrows to select, but that's largely mitigated by `clink-copy-word` <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>W</kbd>.

**Comment by daxgames** [comment]
Testing 1.1.7 on a fresh build of Cmder(master).  Only change is Clink 1.1.7.

Typed `git add ` and got:

![image](https://user-images.githubusercontent.com/7318053/101890426-aecc5480-3b6e-11eb-8cee-01f51c7eccdf.png)

**Comment by chrisant996** [comment]
Oh wow.  Interesting problem, and simple solution:

**The problem:**

- The `modules/matchers.lua` script is calling `clink.find_files()` and passing **two** arguments, but the function only accepted **one** argument.
- `clink.find_files()` got renamed to `os.globfiles()` during the v1.0.0 rewrite a few years ago.
- In v1.1.3-alpha I added back an alias that redirects `clink.find_files()` to `os.globfiles()` to support backward compatibility.
- In v1.1.7 I made a performance improvement that included adding a second argument to `os.globfiles()`, and the new argument changes the scheme of the returned table.
- The matchers.lua script blows up because the second argument it shouldn't have been passing ended up changing the table scheme.

**The fix:**

I just need to change `clink.find_files()` to be a separate function implementation instead of an alias, so that it can accurately behave like v0.4.x did and ignore the second argument.

**Comment by chrisant996** [comment]
[Clink v1.1.8](https://github.com/chrisant996/clink/releases) has been published with fixes to the backward compatibility logic.
A couple other backward compatibility issues were found and fixed as well as a byproduct.

Thank you @daxgames for reporting the issue, and also thank you for your patience!  😁

**Comment by daxgames** [comment]
@chrisant996 I just noticed something in testing Clink 1.1.8.  One of the features of Cmder is loading of user `*.lua` scripts from `%cmder_root%\config`.  This does not appear to happen when using Clink 1.1.8.

This functionality is achieved using the following command line to import CLink in the `init.bat`:

```
if "%CMDER_CLINK%" == "1" (
  %print_verbose% "Injecting Clink!"

  :: Run clink
  if defined CMDER_USER_CONFIG (
    if not exist "%CMDER_USER_CONFIG%\settings" (
      echo Generating clink initial settings in "%CMDER_USER_CONFIG%\settings"
      copy "%CMDER_ROOT%\vendor\clink_settings.default" "%CMDER_USER_CONFIG%\settings"
      echo Additional *.lua files in "%CMDER_USER_CONFIG%" are loaded on startup.\
    )
    "%CMDER_ROOT%\vendor\clink\clink_%clink_architecture%.exe" inject --quiet --profile "%CMDER_USER_CONFIG%" --scripts "%CMDER_ROOT%\vendor"
  ) else (
    if not exist "%CMDER_ROOT%\config\settings" (
      echo Generating clink initial settings in "%CMDER_ROOT%\config\settings"
      copy "%CMDER_ROOT%\vendor\clink_settings.default" "%CMDER_ROOT%\config\settings"
      echo Additional *.lua files in "%CMDER_ROOT%\config" are loaded on startup.
    )
    "%CMDER_ROOT%\vendor\clink\clink_%clink_architecture%.exe" inject --quiet --profile "%CMDER_ROOT%\config" --scripts "%CMDER_ROOT%\vendor"
  )
) else (
  %print_verbose% "WARNING: Incompatible 'ComSpec/Shell' Detetected Skipping Clink Injection!"
)
```

I assume Clink 1.1.8 is ignoring the `--profile ...` part of the command line?

I have the following 2 lua scripts in `%CMDER_ROOT%\config`:

- `prompt.lua`

```
-- Much of the below was 'borrowed' from https://github.com/AmrEldib/cmder-powerline-prompt
-- Symbol displayed for the home dir in the prompt.
if not prompt_homeSymbol then
        prompt_homeSymbol = "~"
end

-- Symbol displayed in the new line below the prompt.
if not prompt_lambSymbol then
        prompt_lambSymbol = "λ"
end

-- Extracts only the folder name from the input Path
-- Ex: Input C:\Windows\System32 returns System32
---
local function get_folder_name(path)
        local reversePath = string.reverse(path)
        local slashIndex = string.find(reversePath, "\\")
        return string.sub(path, string.len(path) - slashIndex + 2)
end

function prompt_filter()
    cwd = clink.get_cwd() .. ' '
    if prompt_useHomeSymbol and string.find(cwd, clink.get_env("HOME")) then
        cwd = string.gsub(cwd, clink.get_env("HOME"), prompt_homeSymbol)
    end

    uah = ''
    if prompt_useUserAtHost then
        uah = clink.get_env("USERNAME") .. "@" .. clink.get_env("COMPUTERNAME") .. ' '
    end

    cr = "\n"
    if prompt_singleLine then
      cr = ' '
    end

    prompt = uah_color .. "{uah}" .. cwd_color .. "{cwd}{git}{hg}{svn}" .. lamb_color .. cr .. "{lamb} \x1b[0m"
    uah_value = string.gsub(prompt, "{uah}", uah)
    new_value = string.gsub(uah_value, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", prompt_lambSymbol)
end

clink.prompt.register_filter(prompt_filter, 1)
```

- ` prompt_config.lua`

```
-- All of the below was 'borrowed' from https://github.com/AmrEldib/cmder-powerline-prompt

--- REQUIRED. config_prompt_type is whether the displayed prompt is the full path or only the folder name
 -- Use:
 -- "full" for full path like C:\Windows\System32
 -- "folder" for folder name only like System32
 -- "smart" to switch in git repo to folder name instead of full path
 -- default is full
prompt_type = "smart"
--- REQUIRED. config_prompt_useHomeSymbol is whether to show ~ instead of the full path to the user's home folder
 -- Use true or false
 -- default is true
prompt_useHomeSymbol = true

-- Symbols
-- REQUIRED. Prompt displayed instead of user's home folder e.g. C:\Users\username
prompt_homeSymbol = "~"

-- REQUIRED. Symbol displayed in the new line below the prompt.
prompt_lambSymbol = "λ"

-- REQUIRED. Adds [user]@[host] to the beginning of the prompt like bash
prompt_useUserAtHost = true

-- Prompt Attributes
--
-- Colors
-- Green:      "\x1b[1;33;40m"
-- Yellow:     "\x1b[1;32;40m"
-- Light Grey: "\x1b[1;30;40m"

-- Prompt Element Colors
cwd_color = "\x1b[1;33;40m" -- Green
uah_color = "\x1b[1;32;40m" -- Yellow
lamb_color = "\x1b[1;30;40m" -- Light Grey

prompt_singleLine = true
```

These combine to provide a custom prompt:

![image](https://user-images.githubusercontent.com/7318053/102224167-9b452480-3eb3-11eb-9b35-8888b2d63fd0.png)

instead of the Cmder default Prompt:

![image](https://user-images.githubusercontent.com/7318053/102224407-ea8b5500-3eb3-11eb-9750-4df7e5778476.png)

This is a core feature of Cmder that I know many users use and I know there will be complaints if it is removed.

**Comment by chrisant996** [comment]
Thanks, I'll figure out what's going on.

Also:
- I'm fixing some bugs in the clink-completions scripts. One PR has been merged already (fixing git stash completions West of GMT). Will have a few more soon.
- I'm adding compatibility support for `match_display_filter`, after all. Plus improvements such as being able to include ANSI color escape codes in the filtered matches (since they're display only, and not actual inserted matches).
- I'm even adding compatibility support for a generator contextually overriding an argmatcher. (It's a nuanced behavior that appears very rare, but I did find one script that does it.)

**Comment by chrisant996** [comment]
>     "%CMDER_ROOT%\vendor\clink\clink_%clink_architecture%.exe" inject --quiet
>             --profile "%CMDER_USER_CONFIG%" --scripts "%CMDER_ROOT%\vendor"
> 
> I assume Clink 1.1.8 is ignoring the `--profile ...` part of the command line?

Clink v1.0.0 intentionally stopped loading scripts directly from the profile directory, and instead uses the `clink.path` setting and `%CLINK_PATH%`.

**Here is what I think makes sense to do:**
1. If `--scripts` is used, first load scripts from those paths (all script paths are interpreted as semicolon delimited lists of paths, by the way).
2. Load scripts from the `clink.path` setting (since it's a setting it's dependent on the profile directory).
3. If `clink.path` isn't set, then load scripts from the profile directory (which is either `--profile` or `%USERPROFILE%\AppData\Local\clink`).
4. If `%CLINK_PATH%` is set, then load scripts from there last.

FWIW, Cmder already has enormous control over how Clink operates.  Cmder can use `--scripts` to force where Clink looks for scripts.  For example, I think `--scripts "%CMDER_ROOT%\vendor;%CMDER_USER_CONFIG%"` would yield exactly the behavior from Cmder + Clink v0.4.8.  **But** please don't do that now -- it would conflict with the loading logic described above that I'm implementing, and would load scripts _twice_ from the profile directory, which may cause malfunctions.

**Comment by daxgames** [comment]
@chrisant996 1.1.10 seems to have resolved my last issue reported.  I was not against changing Cmder's init.bat if that would have fixed hopefully you didn't think I was trying to force a change on your end.  Thanks for fixing it.

**Comment by chrisant996** [comment]
> @chrisant996 1.1.10 seems to have resolved my last issue reported. I was not against changing Cmder's init.bat if that would have fixed hopefully you didn't think I was trying to force a change on your end. Thanks for fixing it.

Not at all.  I appreciate your help with identifying backward compatibility challenges, and your patience as I navigate that little maze.  😄  To accommodate [z.lua](https://github.com/skywind3000/z.lua), I also made Clink load scripts from the binary directory if `clink.path` isn't set (at step 3 in the preceding list).

While it's _possible_ for Cmder to make changes, my goal is for Clink to function "sensibly" in the bigger picture.  If the better fit for that is a change in Clink then by all means the change should be in Clink.  Sometimes it takes a bit of mental gymnastics to figure out what "sensible" looks like in a given scenario.  🤪

**Comment by daxgames** [comment]
Mergs a pr to master that makes the switch.

**Comment by chrisant996** [comment]
> **The bad news** is that Cmder is eating all output the Clink 1.1.2 writes to stdout. Output via `WriteConsoleW()` reaches the console screen buffer. But output via `WriteFile()` to the stdout handle gets eaten and never reaches the console screen buffer.
> 
> However, stdout from Clink 0.4.9 works fine in Cmder, and stdout from Clink 1.1.2 works fine in stock ConEmu.
> 
> So it seems that Cmder doesn't like something about Clink 1.1.2, but I'm having trouble figuring out what that might be. I don't see anything obvious in `OnWriteFile()` in src/ConEmuHk/hkStdIO.cpp, but I'll keep looking.

I was finally able to track down and fix the missing output!

Details are in [#93](https://github.com/chrisant996/clink/issues/93) in the chrisant996/clink repo.

All versions of Clink lower than 1.1.45 were affected by the issue, including Clink 0.4.9 and earlier.
The new release of Cmder a few days ago picked up Clink 1.1.45, so the missing output should be a thing of the past.
