### ISSUE TITLE
Midnight Commander

### ISSUE THREAD

**Issue by Makurisan** [cmderdev/cmder#2435]
I see more than one issue regarding linux midnight commander.
Please install "sudo apt-get install mc" and see what happens. 
1. The mouse can not be used 
2. MC is in an endless loop.

I hope you look at this and do not close the issue without any response like the others.

**Comment by daxgames** [comment]
Are you using WSL or are you SSH connected to a Linux system?  Either way it is probably not a Cmder issue.  Cmder has no integration with WSL and does not affect SSH sessions to remote hosts.

If you have issues with Midnight Commander in Linux via WSL or SSH then you should try the same from a Conemu session.  Conemu is the terminal emulator for Cmder and is thus more likely responsible for the issue you are experiencing.

**Comment by Makurisan** [comment]
It is not an Midnight Commander problem and don't try to put the issue to an other product. 
Test it with cmder and you will see that problem.

**Comment by daxgames** [comment]
Answer my questions and I will.  You should do the same and try what I recommended instead of insisting it is Cmder.

The entire GUI for Cmder is an unmodified redistribution of Conemu and the ony difference is some configuration settings that we have documentented in our Wiki.  If you are using WSL you are not using Cmder at all you are using WSL in Conemu.  If you are using SSH to connect to Linux you are using Conemu to run SSH to connect to SSH server on Linux.

Cmder is just configuration that ties several different 3rd party products, Clink, Clink Completions, Git for Windows, and Conemu, together that makes the `cmd.exe` shell more like Linux.  It has nothing to do with programs running on Linux.

**Comment by daxgames** [comment]
Or maybe look at this: https://github.com/Maximus5/ConEmu/issues/648

**Comment by Makurisan** [comment]
It is not relevant for me what kind of emulator cmder use. This is a thing of cmder. Sure I use ssh.
If I use cmd, powershell 7, 6 and older all works fine with ssh but not with cmder. 

What should I say if you say we use conemu and cmder have problem with it and you mean that is a problem of Conemu. In my eyes this is not a problem of ConEmu. It is a problem that cmder use ConEmu and that the product can not handle the above situation. 
I tried "Windows Termin Preview" and here all works as expected.

**Comment by daxgames** [comment]
I just need to know what you want me to test because as of yet it is unclear.

_Note: Put an 'X' in the spaces '[ ]' provided below_

To be clear you are:

Opening cmder and ssh to a linux host that has mc in stalled and the mouse does not work and there are some other issues?

[ ]Yes [ ]No

Opening cmder running WSL that has mc in stalled and the mouse does not work and there are some other issues?

[ ]Yes [ ]No

Tried windows terminal preview with or without cmder integrated?

[ ]With Cmder [ ] Without Cmder

And please remember I trying to answer your question as you requested and not ignoring you.  Also we cannot magically fix issues with other products just because we are consumers of those products.

**Comment by Makurisan** [comment]
I have one question. Did you test it?

**Comment by daxgames** [comment]
I tested it with both Cmder and ConEmu(no cmder code) using both `c:\windows\system32\openssh\ssh.exe` that comes embedded with Windows 10 with similar results that you described.

Type `where ssh -a` to see which ssh.exe you are running.

- Cmder with `c:\windows\system32\openssh\ssh.exe`: Rapidly flickering `mc` bright blue mc color graphics.
- ConEmu(no cmder code) with `c:\windows\system32\openssh\ssh.exe`: Very slowly flickering `mc` grayscale-ish graphics. 

Both above were completely unuseable.

I then tested both with Cmder embedded SSH from path `"%cmder_root%\vendor\git-for-windows\usr\bin\ssh.exe"

- Cmder with c:\windows\system32\openssh\ssh.exe: Stable bright blue mc color like last test but no flicker.
- ConEmu(no cmder code) with c:\windows\system32\openssh\ssh.exe: Stable grayscale-ish graphics color like last test but no flicker.

Both of the above were perfectly useable but with no mouse.

Seems the flickering issue is the Windows embedded `ssh.exe`, mouse input/feedback is the responsibility of the terminal emulator, ConEmu.

I suggest you use a different ssh client and contact ConEmu Dev if you want to use the mouse with `mc` while using ConEmu.
