### ISSUE TITLE
"MSVCP120.dll is missing from your computer."

### ISSUE THREAD

**Issue by hourback** [cmderdev/cmder#246]
Hi there.

Also using Windows 7 Professional SP1.

I downloaded and extracted mini, double-clicked on Cmdr.exe, and got an error dialog:

"System error.  The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem."

Update:

Hmm.  I downloaded full, tried again, and got the same error.

**Comment by luongs3** [comment]
I have the same problem. Need more help

**Comment by kissingsdw** [comment]
Downloading vcredist_x64 AND x86! even if you dont have 32 bit system fixed it from me. Just google it, you download it from microsoft website

**Comment by WFRlomo** [comment]
@kissingsdw 

Thank you! Your inputs saved our day.

We have a connector application that is getting its data from SQL DB Browser and sends real-time stream to one of our servers which suddenly stopped sending data.

I can't forgive myself if we decided to get help from professional services which would have cost us around 200 bucks per hour.

Although it may be cheap, but will just hope that I will not be reading this thread right after it is fixed by the professional service for maybe at least 4 hours.

Again, thank you!

**Comment by koenstorm** [comment]
@kissingsdw

Dear,
Having the same problem, I downloaded the vcredist_x64 and x86. After downloading and running the x86, I got a warning saying that already a newer version was installed (I guess x64 2015. 
Have you also had this and what did you do?

Best Regards

**Comment by jackadision** [comment]
Thanks for this great conversation

**Comment by dockyguy56** [comment]
Dear,

I can confirm. Dowloading the the vcredist_x64 and x86 fix the problem. Find it in Microsoft web page http://www.microsoft.com/en-us/download/details.aspx?id=40784.

Problem solved.
Thanks for your help.
