### ISSUE TITLE
Command history not saved when shutting down

### ISSUE THREAD

**Issue by cocowalla** [cmderdev/cmder#2476]
### Purpose of the issue
- [ x ] Bug report (encountered problems/errors)
- [ x ] Feature request (request for new functionality)
- [ ] Question

### Version Information
ConEmu 210206
Windows 10 Enterprise 1909

### Description of the issue
I noticed that cmder is often missing command history lines, which is a constant nuisance 😅   I think this happens when the Windows is shutdown (as in Start -> Shutdown, not a power off 😄) without first manually closing cmder.

So I guess there are possibly 2 parts to this issue:
1. Is there any way to get cmder to flush the history file before closing, even if it is closed by Windows? (I believe Windows sends `WM_ENDSESSION` and `WM_QUIT` to apps to ask them to close)
2. If the answer to (1) is "no", I notice there is a `history_io` settings, which sounds *almost* perfect. According to the comments in the `settings` file:

    > history will be read from disk before editing a new line and written to disk afterwards

    I have a large history buffer (50k lines) - writing new commands to the end of the history buffer every time is good, but I don't really want to reload a 2MB file after every single command. What I'd really like is something like `history_io = 2`, which only writes after every command

Thanks for Cmder, and thanks for your consideration 👍

**Comment by chrisant996** [comment]
Ah.  That's a great question, and thank you for sharing details about the issue!
I'll try to answer it here, although it's about Clink, not about Cmder per se.

CMD is a console application, and as such doesn't receive any WM_QUERYENDSESSION or WM_ENDSESSION or WM_QUIT.  So Clink isn't able to respond to those messages.

The mention of `history_io` suggests that this is with Clink v0.4.9, right?

Clink v1.1.x from [chrisant996/clink](https://github.com/chrisant996/clink) shouldn't lose history when Windows (or a console window) is shut down, because it uses a redesigned history system.

It does load the history on every prompt, though.  There's not really a way around that, other than to turn off `history.save` (but then history is not saved between sessions at all).  At least not when the storage is just a simple text file; with a more complex file format (such as a database) it could be possible to avoid reading the whole file, but that has other tradeoffs.

However, it's possible to set `history.max_lines` to limit how many lines of history are saved, and that should help avoid a situation where 2MB is loaded on every prompt.

**Comment by cocowalla** [comment]
That makes sense, thanks for explaining!

I checked, and Clink is still at v0.4.9 on all three machines where I use Cmder (Cmder is updated tho, on preview versions even). Is a newer Click distributed with Cmder, or is it something I should download myself and drop into `vendor\click`?

I do want to keep a big history, so I guess I need to find some kind of workaround, perhaps somehow archiving older history periodically.

**Comment by chrisant996** [comment]
> I checked, and Clink is still at v0.4.9 on all three machines where I use Cmder (Cmder is updated tho, on preview versions even). Is a newer Click distributed with Cmder, or is it something I should download myself and drop into `vendor\click`?

Not sure what version of Clink is included with which versions of Cmder.

Yes, you can copy new versions of Clink into `vendor\clink`.

> I do want to keep a big history, so I guess I need to find some kind of workaround, perhaps somehow archiving older history periodically.

Is it actually being noticably slow?  How slow?

I could maybe add a history mode that doesn't reload.  Of course then it won't notice history changes from other sessions.

**Comment by cocowalla** [comment]
> Is it actually being noticably slow? How slow?

A very good question - I haven't actually tried enabling `history_io = 1` 😄 I read the docs and didn't like the sound of all that wasted CPU and disk IO every time I hit Enter, _assuming_ it's going to be slow.

I think what I'll do is swap in a new version of Click, and assuming it doesn't lose history when shutting down anymore, I'm all good. Otherwise, I'll enable `history_io = 1` and come back if it's actually an issue.
