### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by WickedWizard3588** [cmderdev/cmder#2489]
```
@echo off
echo Applying Cmder VSCode settings from '%~0'...

if defined CMDER_CONFIGURED (
    :: Set Cmder settings here for when VSCode is launched inside Cmder.
    :: The below causes Cmder to not rerun userprofile.d\*.cmd and user_profile.cmd scripts becasue Cmder already ran them.
    set CMDER_CONFIGURED=2
) else (
    :: Set Cmder settings here for when VSCode is launched from outside Cmder.
    :: Do NOT add optional Unix tools to the path the same as `init.bat /nix_tools=0`
    set nix_tools=0
    :: Enable Cmder `fast_init` same as `init.bat /f`
    set fast_init=1

    :: Enable Cmder User config same as `Cmder.exe /c c:\Users\$USERNAME\.cmder"
    set cmder_user_bin=c:\Users\$USERNAME\.cmder\bin
    set cmder_user_config=c:\Users\$USERNAME\.cmder\config
)

set verbose_output=1

:: Set all required Cmder VSCode terminal environment settings above this line.
echo Applying Cmder VSCode settings is complete!
```

Hey, after shifting to that in my `vscode_init_args.cmd` file, it always throws an error
```
Applying Cmder VSCode settings from 'D:\MyName\Cmder\bin\vscode_init_args.cmd'...
The system cannot find the drive specified.
Applying Cmder VSCode settings is complete!
File Not Found
```

Why is this happening and how can I fix it?

I have added them in my ENV Variables too. 

Thanks

**Comment by chrisant996** [comment]
The `$USERNAME` looks like the Unix (e.g. bash) way of referencing environment variables.
In CMD it would be `%USERNAME%` to reference the environment variable.

**Comment by WickedWizard3588** [comment]
```
Applying Cmder VSCode settings from 'D:\Myself\Cmder\bin\vscode_init_args.cmd'...
The system cannot find the drive specified.
Applying Cmder VSCode settings is complete!
```

I did as you said, and this is occuring now.

Thanks for the quick reply!!

**Comment by chrisant996** [comment]
> EDIT:- C Drive exists in my computer

Does `D:` exist?  The first line of output cites drive `D:`.

Also, what is `vscode_init_args.cmd` and where did it come from?

The error is happening due to using `::` instead of `rem`.
`:` declares a `goto` label; it is not a comment character.

I know that there is a convention of using `::` as a way to trick CMD into behaving sort of like it's a comment (by declaring a label that is never used), but there are syntax problems that can happen, especially depending on punctuation used later on in the line, or when there are adjacent `::` lines, and other edge cases.

Use `rem` not `::`.

**Comment by WickedWizard3588** [comment]
Hey,

Thanks for the patient reply. I switched to the portable version, and it works perfectly now. But, whenever I use it, I can just randomly change my zoom. Is there any way I can lock the zoom to something like 100%?
