### ISSUE TITLE
Any way to refresh environment variables / aliases like in Linux? (i.e.: "source" or "." commands)

### ISSUE THREAD

**Issue by eriegz** [cmderdev/cmder#2491]
Hi there, after adding a new, custom alias inside cmder's **Settings > Startup > Environment** window (_for which there's surprisingly little documentation, FYI_), is there a way to then "refresh" the current terminal window so that we can use the new alias?

![image](https://user-images.githubusercontent.com/10801672/109890196-1a8cfd80-7c44-11eb-9e0c-519526194e5f.png)

I'm well aware that I could simply restart cmder or create a new console window / tab and close the previous one.

But in Linux bash, one could achieve this in a much more elegant way by doing either:

- `source ~/.bashrc`, or
- `. ~/.bashrc`

...to reload the environment variables / aliases inside of the current terminal session, **_without having to open a new window_**.

Is there any way to achieve this in cmder?

**Comment by daxgames** [comment]
Dont add aliases there.  Use Cmder `alias` cmd or edit `%CMDER_ROOT%\config\user_aliases.cmd`

To refressh just afeter manual edit just run `%CMDER_ROOT%\config\user_aliases.cmd`

**Comment by eriegz** [comment]
Thanks for the reply.

> Don't add aliases there. Use Cmder `alias` cmd or edit `%CMDER_ROOT%\config\user_aliases.cmd`

I mean, the settings page literally says "Set up environment variables, **_cmd.exe aliases_**, codepage"... 🙂

It's also more convenient to add aliases via the cmder settings, rather than manually going into the computer's filesystem to edit "user_aliases.cmd" each time.

> To refressh just after manual edit just run `%CMDER_ROOT%\config\user_aliases.cmd`

In any case, the above line does work if I follow your alternate method. But I still prefer a solution that works for when storing aliases in _the cmder settings_ instead.

**Comment by chrisant996** [comment]
Cmder is a bundle of 4 other products, plus some scripts to glue them together.

The settings UI referred to above is part of ConEmu.

The init.bat file is part of the Cmder across that glue together the other 4 products (ConEmu is the console window, Clink is an extension to CMD, clink-completions is a set of scripts to enhance Clink, and git for Windows is the fourth product).

That's why changing the settings UI doesn't affect the init.bat script.  Cmder is not a single unified product, it's a bundle of products installed together.

**Comment by daxgames** [comment]
Thanks @chrisant996 for the additional explanation.

To expand on your response the `init.bat` is merely the starting point.  This file is owned and managed by the Cmder team and should not be edited since it is a part of the Cmder distribution.

Portable user config is stored in `%cmder_root%\config these files are yours and will not be overwritten on Cmder updates.  See: `%cmder_root%\README.md` for more details on configuring Cmder.

@eriegz I apologize for the brevity of my response I am usually doing this from my phone and I try to provide quick answers ASAP.

You asked about Linux and the `.bashrc` where a manual edit and a `. ~/.bashrc` is required to save aliases across sessions.

Cmder makes it even more convenient by providing the `%cmder_root%\vendor\bin\alias.cmd`.

MOST aliases can simply be added by typing `alias grep=grep --color always $*`.  This creates the alias and adds it to `%CMDER_ROOT%\config\user_aliases.cmd` so it is automatically reloaded by future sessions.

More complicated aliases probably involve a manual edit of `%CMDER_ROOT%\config\user_aliases.cmd` due to parsing and variable expansion limitations in `%cmder_root%\vendor\bin\alias.cmd`.  The WIKI has an examples of advanced aliases.

**Comment by daxgames** [comment]
Can we close this?

**Comment by eriegz** [comment]
@daxgames Sorry for the delay. Thank you for the detailed response.

Your suggestion of simply typing in `alias <nickname>=<command>` works even better than editing the "Environment" section like in my screenshot above! And it also solves the original problem in this ticket, so I will close it now.

Thanks again!

**Comment by daxgames** [comment]
Glad to help.
