### ISSUE TITLE
Stucked on startup: clink_x64.exe

### ISSUE THREAD

**Issue by Suniron** [cmderdev/cmder#2492]
Hey there!

On my pro computer, i'm frequentely stucked on cmder startup like this screen:
![image](https://user-images.githubusercontent.com/36677774/109937515-4903ea80-7ccf-11eb-9c4d-0356d7115fec.png)
This problem appear nearly one out of two launches.

I've tried to launch it as admin but the problem is here too.
Note: i use the default task (`*cmd /k ""%ConEmuDir%\..\init.bat" "`)

Any idea to fix it ? What is this **clink_64.exe**:)

**Comment by chrisant996** [comment]
Clink is [this](https://github.com/chrisant996/clink).

The first thing to try is probably to make sure the latest Clink is copied into the `cmder\vendor\clink` directory.

**Comment by daxgames** [comment]
Can we close this?

**Comment by Suniron** [comment]
Sorry, i'm late to answer here.. I have updated with latest clink_64 but the problem is the same.. Other idea ?

**Comment by chrisant996** [comment]
Can you share more information?
The "latest clink" is ambiguous because there are two forks of Clink -- one is v0.4.9 and the other is v1.1.48 -- which one is being used?
What does `clink info` report?
Can you capture a minidump of the cmd.exe process?
Can you think of anything that might be unusual about the configuration or usage on that computer?

This isn't a widespread problem, so it isn't possible to get information about it from other sources. The more diagnostic information that can be shared, the more likely that the situation can be understood and resolved somehow.
