### ISSUE TITLE
Press UP key get history commands will lost blankspace after "λ"

### ISSUE THREAD

**Issue by gotounix** [cmderdev/cmder#2533]
### Purpose of the issue
- Bug report (encountered problems/errors)

### Version Information
Version 1.3.18.1106

Version 1.3.18.1114

Windows 10 19042.928

### Description of the issue
Press UP key will lost blankspace after "λ"

![111](https://user-images.githubusercontent.com/18606632/116490974-57374700-a8cb-11eb-88b6-105899b5bbfa.png)

**Comment by gotounix** [comment]
![222](https://user-images.githubusercontent.com/18606632/116497363-bd2acb00-a8d9-11eb-9ca4-203dcca5d565.png)

I fixed it by change `Environment` setting.

**Comment by chrisant996** [comment]
It happens when using certain code pages, when the font used by ConEmu is different from the font the OS thinks is being used (the font the OS is actually using in the hidden terminal window via the ConPty APIs, etc).

To solve the problem either change the font, change the code page, or configure Cmder to not use a lambda character.
