### ISSUE TITLE
pasting "i" problem

### ISSUE THREAD

**Issue by dervistalha** [cmderdev/cmder#2535]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question

### Version Information

1.3.18

win 10 pro 1909
### Description of the issue

powershell within Cmder doesn't paste i sign although powershell can paste properly.

![no-i-problem](https://user-images.githubusercontent.com/71238946/116787226-b5228500-aaab-11eb-8555-fb201a968dcd.png)

**Comment by dervistalha** [comment]
nobody has any idea guys?  
That problem causes me not be able to use cmder.

**Comment by chrisant996** [comment]
It looks like the implication is that the repro steps are:
1. Type `i<i<i<i<i<i` into Notepad or Notepad++ or some text editor like that.
2. Select the `i<i<i<i<i<i` and Copy to clipboard.
3. Launch Cmder as Administrator and create a {Powershell::Powershell as Admin} tab.
4. Press Ctrl+V to Paste from clipboard.
EXPECTED:  `i<i<i<i<i<i` appears.
ACTUAL:  `<<<<<` appears.

Following those steps, I get the EXPECTED behavior.

It sounds like there is more involved; maybe there are additional steps or configuration that are necessary?
Is there any more information that can be provided about the problem?
Is a particular language or codepage involved?
Is it a normal lowercase `i`, or does "i sign" have some special meaning?  (I've not heard the phrase "i sign" before, so I'm checking just in case it has special meaning that I've misunderstood.)
Are you able to reproduce it in a fresh Cmder install with no customizations?

![image](https://user-images.githubusercontent.com/17440311/117034992-b2e14600-acb8-11eb-8994-8184f538513e.png)

**Comment by daxgames** [comment]
Same here no issues following those steps.
