### ISSUE TITLE
Clink will always run on Cmder startup.

### ISSUE THREAD

**Issue by szyszak** [cmderdev/cmder#2540]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder version: 1.3.18.1106
ConEmu version: 21.3.4

OS: Windows 10 Home 2004

### Description of the issue

I want to use the default CMD tab autocompletion, but Clink will run every time I start Cmder, even after unchecking "Use Clink in prompt" in Setting -> Features.
The problem goes away when I remove "clink" folder in "cmder/vendor", but then every time I start Cmder I see "path not found" error in the terminal.

**Comment by daxgames** [comment]
It's not a bug its a feature.  The main difference between Cmder and the normal windows shell is `clink`.

`Cmder` is a project comprising several tools glued together by configuration.  Part of that configuration as the `cmd::cmder` Conemu task that runs `init.bat`.  Since this script IS Cmder's init script it injects `clink` it is COMPLETLY separate from the checkbox you referred to in the UI.

If you don't want `clink` you can manually create a new `cmd.exe` based task or you can restore Conemu's default tasks using the UI, just becarefuk to read the popups to avoid overwriting the `Cmder`tasks.
