### ISSUE TITLE
Cmder acting slow when rendering content

### ISSUE THREAD

**Issue by egeres** [cmderdev/cmder#2568]
I'm sorry for posting such an unspecific question, but I'm stuck and can't find any helpful information. When using a fresh Cmder installation (with the default configuration), the retrieval of the outputs seems very slow. In the .gif below the "Enter" key is being hold constantly, but the command prompts appear laggy. I don't remember such behaviors in my previous experience with Cmder in other environments.

![cmnder_is_slow](https://user-images.githubusercontent.com/8045792/125090563-c1404980-e0cf-11eb-8402-865a2ba935cc.gif)

**Comment by nomis51** [comment]
I also experienced some lag. Having Cmder opened for a long period of time or run stuff in it that prints a lot of thing tend to make it lag over time (e.g. training a model with tensorflow for a couple hundred epochs). 

Also, on a fresh Cmder instance, sometime if I just spam the Enter key multiple times, the first couple line returns works fine, then it starts to have a delay between prints and it increase the more Enter key press I send.

**Comment by chrisant996** [comment]
Does it happen in ConEmu?

**Comment by egeres** [comment]
I'm not sure about how to test this only in ConEmu, I couldn't find a guide on this, but if you can point me towards any resources maybe I can provide more useful feedback!

The standard cmd and powershell seem to work without lag, and using the [windows terminal](https://github.com/microsoft/terminal) as the renderer it also causes the same issue. For me, this evidence points towards the issue being in some short of conflict with some part of the `init.bat` file, not Cmder as a whole.

Would it be a good idea to comment all of the `init.bat` file and then re-enable the code section by section until I narrow down the root cause? 🤔

**Comment by daxgames** [comment]
@egeres just create a new task in the conemu setup tasks and run cmd.exe without running init.bat after will essentially do what @chrisant996 is asking.

**Comment by nomis51** [comment]
@chrisant996 No, ConEmu (version 210627 preview) works fine, I can spam it non-stop with scripts, the Enter key or simple commands andno lag at all. It's also fine in Windows Terminal.

**Comment by chrisant996** [comment]
The first thing to do is test whether the slowness is coming from the prompt filter function.
You can do that by:

1. Open the file at `%CMDER_ROOT%\vendor\clink.lua`
2. Find the line `local function set_prompt_filter()` (around line 29 or so)
3. Add the following line immediately after it: `if os.getenv("CMDER_DISABLE_PROMPT") then return end`
4. Save the file
5. In Cmder, press <kbd>Ctrl</kbd>+<kbd>x</kbd>, <kbd>Ctrl</kbd>+<kbd>r</kbd> to reload the scripts
6. In Cmder, type `set CMDER_DISABLE_PROMPT=1` and press <kbd>Enter</kbd>

Now try holding down the <kbd>Enter</kbd> key.
Is there still lag between prompts?

If yes: that would be surprising and offhand I'm not sure what troubleshooting to do next.

If no: the slowness is coming from something in the prompt filter, and additional troubleshooting can dig into that.
- What is the `PATH` env var set to?  If it's very long then launching programs might be slow in general due to needing to search many directories.
- For me there is no lag in a directory like C:\ so offhand I'm not sure what you could be experiencing, other than the `PATH` env var possibility above.  I only experience noticeable lag in git directories with Cmder 1.3.18.  But when Cmder accepts a recent pull request from me and also updates to a more recent version of Clink, then even the lag in git directories will be eliminated.
- Is there anything about your system you can think of that might be interesting?

**Comment by nomis51** [comment]
Seems to work fine after doing the steps, no major lag with Enter key. But, I noticed that when I send a command (e.g. `ls`), if I try `arrow up` to bring back that previous command, most of the time it doesn't work, I need to tap `arrow up` a couple time or tap `arrow down` followed by `arrow up`, which work like 50% of the time.

Also, `PATH` is basically empty, not much paths in it (~ 400 chars / 11 paths).
The lag tend to happen more (and be wortt) in Git folders indeed, but also in normal folders.
Nothing special with the system, standard Windows 10 Pro. I usually use Cmder along with JetBrains PyCharm (doing Tensorflow stuff) or JetBrains Rider, if that makes any difference.

**Comment by chrisant996** [comment]
The arrow key problem is separate.  It sounds like it might be this ConEmu problem:  https://github.com/Maximus5/ConEmu/issues/2302 (also mentioned here https://github.com/Maximus5/ConEmu/issues/2316).  You can try the steps listed [here](https://github.com/chrisant996/clink/issues/112#issuecomment-835550390) to confirm whether that's the issue.  Also, upgrading the ConEmu version might fix that issue.

It sounds like when Cmder accepts [my PR](https://github.com/cmderdev/cmder/pull/2556) and upgrades to the latest Clink the lag may go away (Cmder is currently including a pre-release Clink v1.1.45 from several months ago, and a little over a month ago Clink introduced a way for prompt filters to do their expensive work in the background).

**Comment by daxgames** [comment]
Try [this](https://ci.appveyor.com/project/MartiUK/cmder/builds/40113574/artifacts) build of Cmder it has the latest ConEmu and Clink.

**Comment by chrisant996** [comment]
@daxgames I think you can close this as fixed by [PR 2556](https://github.com/cmderdev/cmder/pull/2556).

**Comment by daxgames** [comment]
See latest unreleased [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)
