### ISSUE TITLE
Neovim not working properly in cmder

### ISSUE THREAD

**Issue by 17Swagat** [cmderdev/cmder#2583]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder Version: 1.3.18.1106

Windows Version: Windows 10 Pro Version: 10.0.19043 Build 19043

### Description of the issue

I'm using Neovim as my text-editor and it is not working properly in cmder. All the visual aspects (from plugins and basic neovim configuration) are not appearing. For example: The colorscheme, syntax highlighting. Also sometimes texts seems to broken like in the given images. Even though features of plugins that do not involve visuals seems to be working fine, like coc-explorer, coc- code completion, floaterm are working fine (not visually).

On the other everything is working fine when I run neovim from cmd. 

* **Neovim in cmder (Things that are not working fine or behaving abnormally)**:
<img width="960" alt="cmder_nvim_1" src="https://user-images.githubusercontent.com/72545910/129208407-485dd929-320e-4290-a125-c990e78698b5.PNG">
<img width="986" alt="cmder_nvim_2" src="https://user-images.githubusercontent.com/72545910/129208439-1c645f23-5419-4a90-9f0a-5d7f5f44cbf0.PNG">
<img width="960" alt="cmder_nvim_3" src="https://user-images.githubusercontent.com/72545910/129208774-93972794-f526-481f-acea-d332a6074102.PNG">

* **Neovim in cmder (Things that are working fine)**:
<img width="960" alt="cmd_nvim_3" src="https://user-images.githubusercontent.com/72545910/129209441-892a7768-995b-4f94-bbf9-339482d4bdfa.PNG">
<img width="964" alt="cmd_nvim_4" src="https://user-images.githubusercontent.com/72545910/129209457-242ac758-42b4-44b2-a8fa-928c0a00d978.PNG">
<img width="960" alt="cmder_nvim_4" src="https://user-images.githubusercontent.com/72545910/129209708-c73c8bb3-2929-441f-85e6-acf998e7c5ae.PNG">

* **Neovim in cmd**: 
<img width="943" alt="cmd_nvim_1" src="https://user-images.githubusercontent.com/72545910/129208249-69547428-05c1-48a2-a270-879cbba801ae.PNG">
 
<img width="950" alt="cmd_nvim_2" src="https://user-images.githubusercontent.com/72545910/129208290-d321be51-60e6-4e60-868c-f0f44f8a7763.PNG">

<img width="960" alt="1" src="https://user-images.githubusercontent.com/72545910/129216554-2704b1ef-7ccc-4b75-8271-6850c9ce6520.PNG">

<img width="960" alt="2" src="https://user-images.githubusercontent.com/72545910/129216576-2611278b-4fe0-48d7-906f-ecfa35b80ef9.PNG">

**_Although vim that comes with Cmder is working normally. (Following Exactly what I've written in its .vimrc file)_**
<img width="960" alt="vi" src="https://user-images.githubusercontent.com/72545910/129217391-79012d5a-84e7-41d1-af83-b97de3e27d4d.PNG">

**Comment by chrisant996** [comment]
Probably it's a matter of setting the terminal info environment variables correctly.

The issue is between ConEmu and neovim, so search on the internet for "ConEmu neovim" to find information about using them together.

ConEmu is the terminal program used by Cmder.

**Comment by NarrowCode** [comment]
If anyone else is having similar issues, and until the new build referenced [here](https://github.com/cmderdev/cmder/issues/2563#issuecomment-1100858370) is released - I resolved the issue by adding the following into my Settings > Startup > Environment:

`set TERM=conemu`

**Comment by ggrzybow** [comment]
@NarrowCode It has caused folded lines in Neovim to have a gray background, so I guess some rendering problem got fixed.
Unfortunately I still have corruptions when for example, folding and unfolding functions. For example, before folding the function line says:
```C++
225 #endif
```
After folding the entire function, the line should be empty (showing an empty line between some other folded functions), but it shows:
```C++
2       if
```
An additional side effect is that previously, scrolling up or down (so that some new line goes into view) would solve the rendering artifacts. Presumably, the whole screen was redrawn. But after changing `TERM` from default `cygwin` to `conemu`, scrolling does not fix all artifacts, for example corrupted line numbers remain corrupted.

**Comment by ggrzybow** [comment]
@NarrowCode It has caused folded lines in Neovim to have a gray background, so I guess some rendering problem got fixed.
Unfortunately I still have corruptions when for example, folding and unfolding functions. For example, before folding the function line says:
```C++
225 #endif
```
After folding the entire function, the line should be empty (showing an empty line between some other folded functions), but it shows:
```C++
2       if
```
An additional side effect is that previously, scrolling up or down (so that some new line goes into view) would solve the rendering artifacts. Presumably, the whole screen was redrawn. But after changing `TERM` from default `cygwin` to `conemu`, scrolling does not fix artifacts, only lines that go out of the view and come back (and thus get fully redrawn) are fixed.

EDIT: Additionally, that envvar change causes [delta](https://github.com/dandavison/delta) to print `WARNING: terminal is not fully functional` and scrolling long diffs (with latest `less` as a pager) with arrows is not possible (escape codes are inputted as text instead).

**Comment by ggrzybow** [comment]
I just tried a fresh Cmder v1.3.20 and the issues described in my previous comment don't happen anymore, probably because TERM is now unset. As a bonus, it seems that Neovim now supports more than 16 colors.
