### ISSUE TITLE
Open the cmder with bat and execute the command

### ISSUE THREAD

**Issue by ljynfo** [cmderdev/cmder#2585]
I'm sorry to bother you. I encountered a problem and did not find the answer in the wiki. I hope you can help me.

My computer is Windows, and I hope that after opening cmder by command, it can automatically execute some scripts. I can save this command into multiple BAT files to ensure that I can use it in different scenarios.

Now I don't know how to do, hope to get help

**Comment by daxgames** [comment]
Cmder is an terminal enhancement that provides a better terminal experience  for user interraction and is not normally used nor required for batch processing.

I also don't know what or why you are trying to do this so I can't give specific examples but here are some options.

1. Edit `%cmder_root%\config\user_profile.cmd`. Runs every time for every `cmd.exe` based session.

2. Execute any number of scripts by placing them in the `%cmder_root%\config\profile.d` folder.  Runs every time for every `cmd.exe` based session.

3. Create specific tasks using `/cexec` or `/ccall` arguments of Cmder's `init.bat` to make that task to startup and do something specific after initialization.  Search the issues/wiki for examples.

4.  Use `cmder.exe -- [conemu args]` to pass arguments directly to conemu and take advantave of whatever it supports.

If you are trying to run several long running processes in multiple tabs/panes for convenience I would not use a Cmder enhanced session.  I would create one/many Conemu task[s] using straight `cmd.exe /c [batch file]` commands and Conemu arguments to build the tabs/panes the way you want since the sessions are not user interractive and do not require Cmders enhancements

**Comment by ljynfo** [comment]
Thank you very much for your answer. Your help is very useful to me.

Can you tell me about the document you mentioned in article 4 (Use cmder.exe -- [conemu args]),

I guess I need to know what arguments it supports and how to write these commands on the terminal

**Comment by daxgames** [comment]
Google 'conemu command line arguments'.

When launching `cmder.exe` with `--` as an argument any argument to the right of the `--` will pass directly to Conemu.

That is all I can give you.

**Comment by ljynfo** [comment]
When I log in to the remote server, I hope to open cmder and log in directly (no no-secret setting is allowed).

I run ConEmu. exe -run ssh  -p 22 jjb_pub@172.16.101.101

The CMder window opens, but you still need to enter your password again and press Enter to complete the connection

How to do excuse me I only enter a command complete connection directly, such as the following command (wrong) : 
ConEmu. exe - run ssh -p 22 jjb_pub@172.16.101.101 | command password

**Comment by ljynfo** [comment]
I am very sorry that my question may be stupid, I am a computer beginner, it bothers me and disturbs you

**Comment by daxgames** [comment]
Google `ssh key authentication`

**Comment by daxgames** [comment]
And you question is not stupid but you.are probably trying to use the wrong tool formthe desired outcome as I said before.

**Comment by ljynfo** [comment]
Thank you very much for your answer and help. I have achieved what I want through other forms. Thank you again!

If you agree, I will close this comment. Thank you.

**Comment by daxgames** [comment]
Thats fine.  How did you solve it so others can benefit from your experience.
