### ISSUE TITLE
Run bash scripts using alise

### ISSUE THREAD

**Issue by morpheuslord** [cmderdev/cmder#2588]
Hello 
I wanted to run a bash script through an aliase but it didn't work how can I run a bash script using the aliase while I am using a CMD shell is there a way I can use git bash to run just one script inside a another shell

**Comment by daxgames** [comment]
What does your alias look like?

**Comment by morpheuslord** [comment]
It's like 
Searchsploit=%CMDER_ROOT%\info_gathering\searchsploit.sh

**Comment by daxgames** [comment]
Have you tried Searchsploit=bash %CMDER_ROOT%\info_gathering\searchsploit.sh

**Comment by morpheuslord** [comment]
No I think it won't work as I tried it previously but it didn't work

**Comment by chrisant996** [comment]
> No I think it won't work as I tried it previously but it didn't work

But what did happen?
What error message was reported?
Maybe bash isn't on the PATH, and maybe you need to use a fully qualified path to invoke bash.

CMD.exe can't run bash scripts directly.

So typically one invokes bash, to have bash run the script.

So the questions to ask yourself are,
- What is the path to my bash program?
- What is the command syntax in bash, for invoking a bash script.

For the first one, find your copy of bash.
For the second one, consult bash documentation.

(The issue here is actually about bash, not about Cmder, so the Cmder forum might not be an ideal place to find answers.)

**Comment by daxgames** [comment]
I created a simple bash script and created an alias exactly as I suggested and it does work if bash is in the path.  If you are using Cmder Full `bash` is in the path.

**Comment by morpheuslord** [comment]
I believe I have done some mistake in its installation I will reinstall and do it again

**Comment by daxgames** [comment]
In what installation.  Cmder has no installation.

**Comment by morpheuslord** [comment]
Like I have done some alterations in the files and created a custom installer with cmder for backups and I had to delete the already installed cmder so I reinstalled from the installer I made

**Comment by morpheuslord** [comment]
Ya it worked
