### ISSUE TITLE
λ symbol is missing in lastest full version

### ISSUE THREAD

**Issue by mianxiangdahai** [cmderdev/cmder#2603]
**I download the full version from the release page and run Cmder.exe, but it seems some feature I liked before is missing**
- the character color is white, not green
- the λ symbol is also missing
![2021-09-16_222403](https://user-images.githubusercontent.com/38887739/133630547-f3910986-2d87-4589-8261-4a66e19069e6.png)
### Version Information
![2021-09-16_223129](https://user-images.githubusercontent.com/38887739/133631145-1623f823-7226-4a06-98b5-2cc718dcc7dc.png)
windows 11
### How to reproduce the problem:
The first step is to download the compressed package directly on the cmder official website
The second step, unzip directly
The third step, click to run, cmder.exe
As a result, this problem will appear, the result is exactly the same, I have tried no less than ten times, and this problem occurs every time

**Comment by daxgames** [comment]
I do not have this problem.  If you do it is something on your system causing it.

Do you have an older cerson on `clink` installed globally.  Type `clink info` and post the output.

**Comment by mianxiangdahai** [comment]
![2021-09-16_225030](https://user-images.githubusercontent.com/38887739/133634451-0802975b-03c6-4330-b083-4c7c5f55dede.png)

**Comment by mianxiangdahai** [comment]
![2021-09-16_225409](https://user-images.githubusercontent.com/38887739/133635051-18cd3999-aafc-499e-8162-755c2f5f550b.png)

**Comment by mianxiangdahai** [comment]
Under exactly the same conditions,
Switch to powershell.exe and it will display normally,
Directly use the default cmd as soon as the cmder is opened, and the exe is not normal. Why is this?
How can it be displayed normally when using cmd.exe?

**Comment by daxgames** [comment]
Powershell is a COMPLETLY different shell and configuration so the fact that it works and cmd does not is COMPLETELY irrelevant.

As I said earlier the issue is on your system.  It might be antivirus/malware software blocking injection of clink or a globally installed older version of clink.

Try looking at antivirus logs to see if itnis blocking something or disabling antivirus and see if that fixes it.  If it does add an exclusion to your antivirus.

Search the issues asnsugfested earlier you may find the solution there.

**Comment by mianxiangdahai** [comment]
I checked the log of my computer's antivirus program, and it didn't show that clink was blocked.
Moreover, the antivirus log has no records in the last few days, and the latest record shows that it was on August 6.
I also looked at the same question and answer that I asked before.One of them mentioned that he deleted clink and re-run the software repair. These methods solved the problem, but I don't know how to do it.

**Comment by mianxiangdahai** [comment]
I have tried, and all the methods I can find can not solve the problem. Can this problem be solved, if there is a way, please tell me directly.

**Comment by chrisant996** [comment]
You've got two (or more) versions of Clink trying to operate at the same time.

What steps have been taken, to get into this situation?

Did you run the setup.exe for Clink v1.2.32, while using a different version of Clink included in Cmder?

Uninstall the setup version of Clink.
Download the .zip file for Clink v1.2.32.
Extract the files from the zip file, and use them to replace the Cmder `vendor\clink` files.

**Comment by daxgames** [comment]
@mianxiangdahai You have clink installed outside Cmder as I suggested earlier.  You need to uninstall the external version[s].

**Comment by mianxiangdahai** [comment]
Now I open cmder to choose cmd.exe or this display:
![2021-09-17_201501](https://user-images.githubusercontent.com/38887739/133782345-16e05a86-e932-43c7-ae9a-ff01c5b756ad.png)
这是相关文件夹里面的情况:
![2021-09-17_202242](https://user-images.githubusercontent.com/38887739/133782426-c8f793d9-c66d-4653-b9d3-f8bb85200e3c.png)
![2021-09-17_202332](https://user-images.githubusercontent.com/38887739/133782461-7f34c82e-acf1-4934-80fa-25648e4ac485.png)

![2021-09-17_202436](https://user-images.githubusercontent.com/38887739/133782472-8021bd3c-9c8b-450c-91ee-0d70fc5ab966.png)

**Comment by mianxiangdahai** [comment]
What should I do to make it display normally?

**Comment by mianxiangdahai** [comment]
> @mianxiangdahai You have clink installed outside Cmder as I suggested earlier. You need to uninstall the external version[s].

What should I do to make it display normally?

**Comment by chrisant996** [comment]
I just said what to do in my previous reply.

https://github.com/cmderdev/cmder/issues/2603#issuecomment-921468591

**Comment by mianxiangdahai** [comment]
> 我在之前的回复中只是说该怎么做。
> 
> [第2603章（评论）](https://github.com/cmderdev/cmder/issues/2603#issuecomment-921468591)

When I checked today, I did find a globally installed clink. I have uninstalled it. The current clink is to download the complete cmder package. After decompressing it, it comes with clink.

**Comment by mianxiangdahai** [comment]
> 我在之前的回复中只是说该怎么做。
> 
> [第2603章（评论）](https://github.com/cmderdev/cmder/issues/2603#issuecomment-921468591)
![2021-09-17_205524](https://user-images.githubusercontent.com/38887739/133786077-788c376c-cfcb-4691-a603-9389f0b27306.png)
it shows:
'clink' is not an internal or external command, nor is it an executable program
Or batch file.

**Comment by chrisant996** [comment]
You've done step 1 of what I suggested.

Next, do the rest:

- Download the .zip file for Clink v1.2.32.
- Extract the files from the zip file, and use them to replace the Cmder `vendor\clink` files.

Also, send the `clink.log` file, so we can see what's happening when Cmder tries to run Clink.

The reason you're not seeing the expected prompt is because when Cmder runs Clink, something is going wrong. We're trying to help you track down and fix whatever that problem is. It seems that there are configuration problems on the computer, but we have very little information about the computer, so trying to help is difficult.

**Comment by daxgames** [comment]
You could try running `diag_cmd` after running `cmder` and post the output.

Make sure you check thenoutput for private info before posting.

**Comment by mianxiangdahai** [comment]
> 你已经完成了我建议的第 1 步。
> 
> 接下来，做剩下的：
> 
> * 下载 Clink v1.2.32 的 .zip 文件。
> * 从 zip 文件中提取文件，并使用它们替换 Cmder`vendor\clink`文件。
> 
> 另外，发送`clink.log`文件（`clink info`输出显示在哪里可以找到它），这样我们就可以看到当 Cmder 尝试运行 Clink 时发生了什么。
> 
> 您没有看到预期提示的原因是，当 Cmder 运行 Clink 时，出现了问题。我们正在努力帮助您追踪并解决该问题。看来是电脑配置有问题，但是我们对电脑的了解很少，所以很难尝试帮助。



> * Clink v1.2.32

The clink I use now is the version that comes with cmder. If you replace it with Clink v1.2.32 as you said, clink will report an error

**Comment by mianxiangdahai** [comment]
> You've done step 1 of what I suggested.
> 
> Next, do the rest:
> 
> * Download the .zip file for Clink v1.2.32.
> * Extract the files from the zip file, and use them to replace the Cmder `vendor\clink` files.
> 
> Also, send the `clink.log` file (the `clink info` output shows where to find it), so we can see what's happening when Cmder tries to run Clink.
> 
> The reason you're not seeing the expected prompt is because when Cmder runs Clink, something is going wrong. We're trying to help you track down and fix whatever that problem is. It seems that there are configuration problems on the computer, but we have very little information about the computer, so trying to help is difficult.

The clink I use now is the version that comes with cmder. If you replace it with Clink v1.2.32 as you said, clink will report an error:
![2021-09-17_213212](https://user-images.githubusercontent.com/38887739/133790976-b6cce2ca-df92-493c-8b79-bc0f06c6887f.png)
![2021-09-17_213042](https://user-images.githubusercontent.com/38887739/133790998-400c8c55-081b-4a6c-8f61-8a74338a8add.png)

**Comment by mianxiangdahai** [comment]
If it can't be solved, I can only continue to use it under this kind of error display.

**Comment by mianxiangdahai** [comment]
> You've done step 1 of what I suggested.
> 
> Next, do the rest:
> 
> * Download the .zip file for Clink v1.2.32.
> * Extract the files from the zip file, and use them to replace the Cmder `vendor\clink` files.
> 
> Also, send the `clink.log` file (the `clink info` output shows where to find it), so we can see what's happening when Cmder tries to run Clink.
> 
> The reason you're not seeing the expected prompt is because when Cmder runs Clink, something is going wrong. We're trying to help you track down and fix whatever that problem is. It seems that there are configuration problems on the computer, but we have very little information about the computer, so trying to help is difficult.

Brother, what do you think I should do? Hahaha

**Comment by daxgames** [comment]
We need MORE information than you are providing.

Try running `cmder_diag` after running Cmder and post the output.  Make sure you check the output for private info before posting.

You could also add some args to your Cmder task to provide output of the init process. 

Also type `where clink` and post the output.

**Comment by chrisant996** [comment]
I see several things:

1. A screen shot shows you have an old copy of Clink in `E:\Cmder\vendor\conemu-maximus5\ConEmu\clink`.  **Delete that copy**.  You must leave that directory empty.
2. The above point suggests that you may have checked the "Use clink in prompt" box in ConEmu.  **Uncheck that box**.  You must not use that with Cmder.  Cmder has its own separate Clink, and Cmder does extra work to use its Clink.  Checking that box fights with Cmder and breaks it.  
![image](https://user-images.githubusercontent.com/17440311/133800810-0f1a812c-5c5a-4c0b-9597-812d1506f9f0.png)
3. The screenshot of the log file shows that the EXE version is 1.2.32 (0x00010002 0x00200000), but it is missing any mention of the DLL version.  That means there was a failure trying to retrieve the version info from the DLL file.  Unfortunately, that is an unusual error in an unusual place, and Clink didn't log the error code for it.  I'll add logging for that case.  But it may be related to points 1 and 2 above.
4. The reason `clink info` says it can't find the program is because normally the `clink` there is actually a DOSKEY alias:  when Clink successfully initializes, it sets a DOSKEY alias so that `clink` will launch the correct clink.exe.  In your case, Clink is not successfully initializing, and so the alias is not set.

Let's start with that.

Again, **you must remove all of the extra copies of Clink that you have manually installed**.  They are creating the problems.  We don't know all of the extra copies you have installed, or where you have installed them, so we can't tell you the exact steps to follow.  You must find and remove all of the extra copies of Clink.

Make it so the **only** copy of Clink is the one in `E:\Cmder\vendor\clink`, and make it be the v1.2.32 version.

**Comment by mianxiangdahai** [comment]
> I see several things:
> 
> 1. A screen shot shows you have an old copy of Clink in `E:\Cmder\vendor\conemu-maximus5\ConEmu\clink`.  **Delete that copy**.  You must leave that directory empty.
> 2. The above point suggests that you may have checked the "Use clink in prompt" box in ConEmu.  **Uncheck that box**.  You must not use that with Cmder.  Cmder has its own separate Clink, and Cmder does extra work to use its Clink.  Checking that box fights with Cmder and breaks it.
>    ![image](https://user-images.githubusercontent.com/17440311/133800810-0f1a812c-5c5a-4c0b-9597-812d1506f9f0.png)
> 3. The screenshot of the log file shows that the EXE version is 1.2.32 (0x00010002 0x00200000), but it is missing any mention of the DLL version.  That means there was a failure trying to retrieve the version info from the DLL file.  Unfortunately, that is an unusual error in an unusual place, and Clink didn't log the error code for it.  I'll add logging for that case.  But it may be related to points 1 and 2 above.
> 4. The reason `clink info` says it can't find the program is because normally the `clink` there is actually a DOSKEY alias:  when Clink successfully initializes, it sets a DOSKEY alias so that `clink` will launch the correct clink.exe.  In your case, Clink is not successfully initializing, and so the alias is not set.
> 
> Let's start with that.
> 
> Again, **you must remove all of the extra copies of Clink that you have manually installed**. They are creating the problems. We don't know all of the extra copies you have installed, or where you have installed them, so we can't tell you the exact steps to follow. You must find and remove all of the extra copies of Clink.
> 
> Make it so the **only** copy of Clink is the one in `E:\Cmder\vendor\clink`, and make it be the v1.2.32 version.

I have completed the 1 and 2 in your this, and now it is displayed like this

**Comment by mianxiangdahai** [comment]
> We need MORE information than you are providing.
> 
> Try running `cmder_diag` after running Cmder and post the output as suggested earlier. Make sure you check the output for private info before posting.
> 
> You could also add some args to your Cmder task to provide output of the init process.
> 
> ![image](https://user-images.githubusercontent.com/7318053/133800618-d90eacc0-d832-4e38-a3c9-ffe92d295b9e.png)
> 
> Example: `cmd /k ""%ConEmuDir%\..\init.bat" /d /t "`
> 
> Also type `where clink` and post the output.

你说的命令我也运行了,结果如下
![2021-09-17_231048](https://user-images.githubusercontent.com/38887739/133807897-f9e16d5b-c4dc-4a85-89d6-062c3c96198e.png)
:

**Comment by chrisant996** [comment]
> I have completed the 1 and 2 in your this, and now it is displayed like this:

Clink is unable to access its DLL to check the version, and so it aborts.
That probably means either there is a configuration problem, or interference from an antivirus program.

I've added logging to report the error that it encounters, so that we can get more information about what is going wrong.
Here is a pre-release version that includes the additional logging:
[clink.1.2.33.fd526c.zip](https://github.com/cmderdev/cmder/files/7187126/clink.1.2.33.fd526c.zip)

Try extracting the files from there, into the `E:\cmder\vendor\clink` directory.

**Comment by mianxiangdahai** [comment]
> > I have completed the 1 and 2 in your this, and now it is displayed like this:
> 
> Clink is unable to access its DLL to check the version, and so it aborts.
> That probably means either there is a configuration problem, or interference from an antivirus program.
> 
> I've added logging to report the error that it encounters, so that we can get more information about what is going wrong.
> Here is a pre-release version that includes the additional logging:
> [clink.1.2.33.fd526c.zip](https://github.com/cmderdev/cmder/files/7187126/clink.1.2.33.fd526c.zip)
> 
> Try extracting the files from there, into the `E:\cmder\vendor\clink` directory.

I have replaced your version of clink, the following is the display in clink.log:

![2021-09-18_083120](https://user-images.githubusercontent.com/38887739/133866002-deb1272a-8b5e-487d-ad6e-2aa6fc103e8e.png)

**Comment by chrisant996** [comment]
Error code 2 is "file not found".
Clink successfully created and copied the file.
And then a moment later the file is gone.

99+% probability this is an antivirus suite interfering.

There's nothing I can do about that.
You'll have to find a way to add an exception to the antivirus suite, or something.

**Comment by mianxiangdahai** [comment]
> Error code 2 is "file not found".
> Clink successfully created and copied the file.
> And then a moment later the file is gone.
> 
> 99+% probability this is an antivirus suite interfering.
> 
> There's nothing I can do about that.
> You'll have to find a way to add an exception to the antivirus suite, or something.

Okay, thank you for your answers all the time, let me take a look at the protection configuration of my computer's system.

**Comment by chrisant996** [comment]
I think I figured it out:

Your user account name is redacted. But maybe it is using Chinese or other Unicode characters? And maybe the computer is not set to use UTF8 as the system code page?

It turns out that a mistake was introduced during the big Clink rewrite (around 2016, but not released until a year ago), and one spot accidentally used UTF8 in an API call that expects system code page.

The latest [Clink v1.2.42](https://github.com/chrisant996/clink/releases) should fix that issue.

Or you could try setting UTF8 as the system code page.

Sorry it took so long to uncover what was happening. If I had seen that the user account name was not ASCII characters then I might have been able to realize on my own. Instead @leo1217 figured it out in #2619.

**Comment by chrisant996** [comment]
Oh, _interesting_:

**Questions:**
1. Are the default %TMP% or %TEMP% environment variables overridden?
2. Are 8.3 aliases disabled on this computer/volume?

It seems that by default the OS does magic to work around exactly this kind of problem in older programs, but either of the above can circumvent the OS magic.

You can query the current 8.3 alias setting on the volume by doing the following:
1. Start a new CMD window as Administrator.
2. Run `fsutil 8dot3name query c:`, and it will report the current setting.

**Here's what I tried on my computer:**

I created a user account "ашкуадн".  The name comes from switching the input language to Russian and typing "firefly" on my physical US keyboard.

The file system creates a `c:\Users\ашкуадн` directory.
The file system also creates an 8.3 alias `c:\Users\B9DA~1` for that.
The `%TMP%` and `%TEMP%` environment variables are by default set to `c:\Users\B9DA~1\AppData\Local\Temp`.

Thus, even though the user account uses Unicode characters and the Clink code was mishandling that, nevertheless it still ended up working fine, because the OS sets %TMP% and %TEMP% using the 8.3 alias for compatibility purposes.

Only when I override the default %TMP% and %TEMP%, or turn off 8.3 short name alias generation before creating the user account, then the following error occurs:

```cmd
C:\Users\ашкуадн>\tmp\clink1237\clink inject
DLL version mismatch.
Unable to inject Clink.
See log file for details (C:\Users\???????\AppData\Local\clink\clink.log).
```

Notice the "???????" portion -- that's the actual error message.  If that part of the error message had not been blanked out when reporting the issue, then it would have been much faster to figure this out.

**Comment by chrisant996** [comment]
Ah, and unfortunately it turns out there are a **LOT** of other things that go wrong past the inject point:

The GNU Readline and GNU History libraries used by Clink only support UTF8.  So if the system code page is not UTF8, then they're not going to work reliably when the user name uses non-ASCII characters.

I'm looking further into that, but this may just be a situation where the best solution is to either make sure the TEMP directory uses ASCII characters, or to set the system code page to UTF8 (though not all programs support the latter).

**Comment by chrisant996** [comment]
@daxgames, this and 2514 can probably be closed, unless you're waiting until the next Cmder ships. The underlying issue in Clink has been resolved. Also, a workaround was to set the code page to UTF8.

We may be very close to having a solution for the lambda width problems in East Asian locales, so if you aren't planning to release Cmder before next week then I would encourage picking up Clink v1.2.51 when it becomes available. (Actually I'm considering bumping the version to v1.3 to reflect the volume of significant changes that have taken place since v1.2.)

**Comment by daxgames** [comment]
@chrisant996 we will wait.

**Comment by chrisant996** [comment]
FWIW, it turns out there is no realistic way for Clink to solve the lambda width problems.  They occur because ConEmu mis-draws the lambda.  ConEmu makes it pretty and take only 1 column, but the OS and font and console APIs all think the lambda takes 2 characters.  For simple printed output that might work out fine.  But if a program needs to be able to reposition the cursor (which bash and Clink and any shell must) then it's not possible to work around ConEmu's behavior without introducing other problems.
