### ISSUE TITLE
When I opened cmder for the first time, the window below popped up.

### ISSUE THREAD

**Issue by lydlovezjr** [cmderdev/cmder#2604]
<img width="916" alt="微信截图_20210917173226" src="https://user-images.githubusercontent.com/19246347/133761194-36f86750-30f3-45b7-8691-8f815dc11dfb.png">

**Comment by daxgames** [comment]
That is a side effect of a conemu setting.  Open the conemu settins dialog and go to the updat page as the warning message suggests.  You will see the setting.

I have never seen this before because we use 7zip to package cmder so we always have it installed.  Not sure how long it has been this way would need to look.

**Comment by lydlovezjr** [comment]
So what should i do?

**Comment by daxgames** [comment]
Install 7zip or live with the warning.

**Comment by kouqhar** [comment]
Install either WinRar or 7zip and extract your file using either. Then after the extraction, you should run cmder again, you won't see the issue come up.

**Comment by jiahui92** [comment]
![image](https://user-images.githubusercontent.com/12184974/167647151-c0623a67-b84d-40ed-a94c-7418bd2898a9.png)
1. open the setting page
2. replace the default 7zip command（like the pic）
