### ISSUE TITLE
Bracket the lambda character to avoid the command line editing issue

### ISSUE THREAD

**Issue by carlzhc** [cmderdev/cmder#2632]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder: v1.3.18
ConEmu: 210912

### Description of the issue

For the task {bash:bash}, the lambda character actually is an Unicode character, it may confuse the command line editing functions, like the 'Ctrl-a' won't go to the beginning of the user input.

After I manually replace the line in `/etc/profile.d/git-prompt.sh` with below:

`PS1="$PS1"'\[λ\] '                 # prompt: always λ`

the issue is fixed.

Details can be found at my blog: https://carl.idv.hk/cmder-default-prompt-issue/

**Comment by chrisant996** [comment]
That tells Readline that the lambda _is an ANSI escape code_ and is not actually visible.

It's a hack, and it may cause problems at the end of the line, because Readline will count it as 0 characters, which is not correct.

**Comment by carlzhc** [comment]
Anyway, by adding the brackets around the lambda character, the issue is gone in my case.

Perhaps, to avoid the issue, using the traditional '$' as prompt would be better.

**Comment by chrisant996** [comment]
> Anyway, by adding the brackets around the lambda character, the issue is gone in my case.
> 
> Perhaps, to avoid the issue, using the traditional '$' as prompt would be better.

You will find that if you type an input line that extends to the right side of the screen and wraps, then the brackets are going to cause a different kind of problem.  It may seem like a solution at first, but it is not.  Try it and you will see.  Good luck!

**Comment by carlzhc** [comment]
Thanks for the reply.

My case is, without brackets, Ctrl-a goes to the wrong spot.
Since this is caused by readline,  I'll close this issue for the moment.

**Comment by chrisant996** [comment]
> My case is, without brackets, Ctrl-a goes to the wrong spot. 

Yes, I know.  I'm only saying that you will find the brackets do not fix the problem.

Instead they _change_ the problem.  In some cases it will appear fixed.  And in some cases it will be more broken than ever, and garble the input line anywhere from a little bit to quite a lot.  It all depends on what has been typed, whether the line is long enough to wrap, and what changed on the line.

Readline does a lot of math and analysis, relying on accurate character widths to figure out the minimum set of characters and cursor movement escape codes it can emit to update the displayed input line.  The brackets mess up the character width arithmetic even more than not using brackets -- but the effects show up under different conditions.

Testing it more thoroughly will unfortunately find the brackets help certain simple cases, but overall create a worse problem.

I'm only trying to help, because I have quite a lot of experience with this, as someone who has spent hundreds of hours reading/debugging/changing the Readline source code as part of making [Clink](https://github.com/chrisant996/clink) use the Readline library just like bash does.

Good luck!
