### ISSUE TITLE
Asks for passphrase everytime I push to github

### ISSUE THREAD

**Issue by sethdcd** [cmderdev/cmder#2669]
Title pretty much explains my problem. I saw that there was a ticket opened for this but it didn't supply an actual answer. 

How can I setup cmder so it doesn't ask for my passphrase every time? I'm using Windows 10. 

Thanks!

**Comment by 296951** [comment]
I don't understand the issue.  Cmder will not ask for a passphrase on open.

**Comment by 296951** [comment]
If you are pushing to Github and it asks for a passphrase you have configured your SSH Private Key to require a passphrase.

1. Recreate your private key using `ssh-keygen`.
2. Do not supply a passphrase when prompted. 
3. Replace your public key in Github user settings.
4. Github `git push` will not prompt for passphrase.

Not really a Cmder issue.

**Comment by sethdcd** [comment]
Hmm, so the only way to get it to not ask every time is to get rid of the passphrase? I'll double check but I believe I have a similar passphrase on my linux laptop and the terminal doesn't seem to ask me over and over after I've entered it once. On my Windows computer it does. That's why I was wondering if it had something to do with cmder itself since linux is using bash.

**Comment by chrisant996** [comment]
Windows git stores credentials differently than on *nix.

This is a git issue, not a Cmder issue.

**Comment by daxgames** [comment]
I do not usually ise ssh keys with git.  I use git personal access tokes and I use git credential caching or storage configured by the git command.

**Comment by daxgames** [comment]
> You could look at enabling the ssh agent in cmder as well.  I do not typically use it but you are probably using it in bash  to reduce the number of password prompts.  I lt is just an extra step to enable it in the user_profile.cmd by uncommenting it.

**Comment by sethdcd** [comment]
Cool alright. Thanks again for the info! I'll go ahead and close this out and look into the solutions you provided.

**Comment by sania924** [comment]
Admin@Salman-Laptop MINGW64 /d/Repo/dropella (salman-dev)
$     git push --set-upstream origin salman-dev
Enter passphrase for key '/c/Users/Admin/.ssh/id_ed25519': 
Enter passphrase for key '/c/Users/Admin/.ssh/id_ed25519': 
Enter passphrase for key '/c/Users/Admin/.ssh/id_ed25519': 
To github.com:AhsanSarwar45/dropella.git
 ! [rejected]          salman-dev -> salman-dev (fetch first)
error: failed to push some refs to 'github.com:AhsanSarwar45/dropella.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Admin@Salman-Laptop MINGW64 /d/Repo/dropella (salman-dev)
$ git pull
Enter passphrase for key '/c/Users/Admin/.ssh/id_ed25519':
Enter passphrase for key '/c/Users/Admin/.ssh/id_ed25519':
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Admin@Salman-Laptop MINGW64 /d/Repo/dropella (salman-dev)
$

**Comment by sania924** [comment]
![git](https://github.com/cmderdev/cmder/assets/129292136/c8678112-31aa-4c71-a35f-4074d2995a99)
how to solve thiss erro

**Comment by daxgames** [comment]
This has nothing to do with Cmder you need to create a key that doesn't have a passphrase and enter it in the GitHub

**Comment by sania924** [comment]
how can i do this

**Comment by daxgames** [comment]
> If you are pushing to Github and it asks for a passphrase you have configured your SSH Private Key to require a passphrase.
> 
> 1. Recreate your private key using `ssh-keygen`.
> 2. Do not supply a passphrase when prompted. 
> 3. Replace your public key in Github user settings.
> 4. Github `git push` will not prompt for passphrase.
> 
> Not really a Cmder issue.

From above
