### ISSUE TITLE
在“VIM”中粘贴出现缩进和“#”注释错乱问题

### ISSUE THREAD

**Issue by Meng-Xin** [cmderdev/cmder#2671]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue

![cmder1](https://user-images.githubusercontent.com/48438967/155252958-083358dd-4e1e-454c-b22a-389af5c0a1de.png)

![cmder-error](https://user-images.githubusercontent.com/48438967/155253027-de9f20c7-ccb1-4be9-b9c6-88ffd00626de.png)
![Uploading cmder-error.png…]()

**Comment by daxgames** [comment]
Translation: "Hope to solve the problem of pasting into vim"

I don't think this is related to Cmder.  I use vim every day on Linux with no Cmder and I see this issue depending on how I paste into vim.  Usually happens if I go into insert mode by hitting 'i' then pasting with mouse 'right-click + paste' or 'Ctrl+v'.  Works correctly if I have the text in the correct clipboard and from vim command mode hit 'p' to paste.
