### ISSUE TITLE
Autocompletion for python scripts or any files

### ISSUE THREAD

**Issue by bumbaras** [cmderdev/cmder#2686]
I have read #1980, #508, #826.
My PATHEXT is `PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC,.PY`
but it doesn't change the behaviour and python scripts are not autocompleted (with .\ or without).

Next is `exec_match_style = -1`. Don't know where I should put it. It doesn't work (-1 or 2 value) in user_profile.cmd or in clink_settings.

The only way i found to return with full autocompletion for aything is `exec.files = True` but i need only python scripts ...

**Comment by chrisant996** [comment]
> I have read #1980, #508, #826. My PATHEXT is `PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC,.PY` but it doesn't change the behaviour and python scripts are not autocompleted (with .\ or without).

Those issues all reference the old Clink v0.4.9.

But the problem is you made a mistake when adding .PY to the PATHEXT variable.
You used `,` as a delimiter but the variable requires `;` as the delimiter.

If you fix the definition of PATHEXT then CMD and Clink will work how you expected.

> Next is `exec_match_style = -1`. Don't know where I should put it. It doesn't work (-1 or 2 value) in user_profile.cmd or in clink_settings.

That is how the old Clink v0.4.9 used to store the setting in its settings file.
Clink is up to v1.3.13 currently, and Cmder is using v1.1.45 currently.
(If you want to upgrade Clink in Cmder you can download the latest Clink release .zip file and extract its contents into the `cmder\vendor\clink` directory.)

> The only way i found to return with full autocompletion for aything is `exec.files = True` but i need only python scripts ...

Then you won't want to use `clink set exec.files true`.
By the way, using the `clink set` command is the best way to interact with Clink settings, rather than hand-editing the settings file.

**Comment by bumbaras** [comment]
Yep, this way it works. I took delimiter for PATHEXE from example in mentioned links and didn't notice that originally there are ; instead of ,
Thank You.

**Comment by daxgames** [comment]
@bumbaras See latest unreleased [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)
