### ISSUE TITLE
Colorful icons cannot be displayed on cmder cli

### ISSUE THREAD

**Issue by j-c17** [cmderdev/cmder#2717]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.14.982

Windows 10Pro 10.0.19043
### Description of the issue

When running nestJS command `nest new new-project` , cmder doesn't show the colourful icon 

![image](https://user-images.githubusercontent.com/28582666/178414181-34a011b9-cf8c-4767-a155-304f30bff650.png)

Expected to be like this 
![image](https://user-images.githubusercontent.com/28582666/178414470-6dd12605-82be-41c9-ae34-2e2a192a5811.png)

**Comment by chrisant996** [comment]
Color emoji is not possible with the GDI rendering technology that ConEmu uses. Color emoji are only possible with the DirectX based DirectWrite API. One would have to rewrite the rendering engine to use a different technology stack, in order to be able to draw color emoji. It's possible, but it's a fairly large (expensive) work item, with many downstream ramifications (some benefits, and some drawbacks).

Anyway, it is a ConEmu issue, and needs to be opened in the ConEmu repo rather than the Cmder repo. Cmder can't do anything about it.

**Comment by j-c17** [comment]
Thank you. 

Apparently this issue has been raised in #https://github.com/Maximus5/ConEmu/issues/2226  

Closing this issue and will continue the discussion in https://github.com/Maximus5/ConEmu/issues/2226

**Comment by DRSDavidSoft** [comment]
@j-c17 as an alternative you can use other Terminals with Cmder

https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration

![emoji1](https://user-images.githubusercontent.com/4673812/184639458-a52569f6-e9a5-45f8-abd8-340eafda45bd.png)
