### ISSUE TITLE
[Bug] $CMDER_ROOT/config/user_profile.sh not sourced

### ISSUE THREAD

**Issue by thomasWos** [cmderdev/cmder#2771]
### Version Information

```markdown
Cmder version: v1.3.20
Operating system: Microsoft Windows 10 Enterprise - Version 10.0.19044 Build 19044
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

Wanted to use the lastest release, 
but I noticed that with bash sessions, $CMDER_ROOT/config/user_profile.sh is not sourced.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by daxgames** [comment]
I see it too.  Oddly not seeing it on code in master.  Try this unreleased build: https://ci.appveyor.com/api/buildjobs/lr56ti1hv4qpopyv/artifacts/build%2Fcmder.zip

**Comment by daxgames** [comment]
The issue here is that the `scripts/build.ps1` script does not appear to be copying `%CMDER_ROOT%\vendor\cmder.sh` to `%CMDER_ROOT%\vendor\git-for-windows\etc\profile.d\cmder.sh`

Looking at it now.

**Comment by DRSDavidSoft** [comment]
@daxgames I can see it too, I think the blame's on me.

The script is actually doing its job, the problem is that (I think) the file is being ignored when packing into `7z`, since I made a change that the [packignore](https://github.com/cmderdev/cmder/blob/master/packignore) file is now being performed recursively -- though, I don't see why `vendor\cmder.sh` is matching against `vendor\git-for-windows\etc\profile.d\cmder.sh` as well.  Yikes, sorry about that! 😬

If you look closely, the `git-prompt.sh` is also being ignored in the `vendor\git-for-windows\etc\profile.d` as well.  I'm super sorry and embarrassed that such a thing happened, I needed to perform more tests.

Well now I need to find a solution that would ignore the specified files in the correct directory, without removing the rescursive flag as it'll break building the packages if not `pushd`'d into the right directory.

Will update soon.

**Comment by daxgames** [comment]
@DRSDavidSoft no biggee.  I am sure we have all introduced bugs.

**Comment by thomasWos** [comment]
Thanks guys for the fix.
Do you plan to do a new release?
Cheers

**Comment by DRSDavidSoft** [comment]
@thomasWos There are a couple of other fixes that still need to be done in order to make a new release, but in the meantime, you can download the most recent build (including these fixes) directly from AppVeyor here:

https://ci.appveyor.com/project/cmderdev/cmder/builds/45293395/artifacts
