### ISSUE TITLE
Question: Replace `conhost.exe` by ConEmu in Cmder (Set as default terminal)

### ISSUE THREAD

**Issue by Jacellen** [cmderdev/cmder#2823]
### Question

Why doesn't Cmder replace conhost.exe the same way cmd does?

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by chrisant996** [comment]
The question is about ConEmu, not Cmder.  ConEmu is what Cmder uses for the terminal hosting.

To learn about how ConEmu works, visit its repo and wiki, and consider opening a discussion there.

**Comment by DRSDavidSoft** [comment]
The official **[default terminal](https://conemu.github.io/en/DefaultTerminal.html)** documentation states:

> In fact, Windows does not provide **official** way to change the default terminal application. That is because console subsystem is a part of Windows kernel (`csrss.exe` up to Vista and `conhost.exe` in Windows 7 and higher).
> Only use of hacking methods can ‘change’ default Windows terminal application. And ConEmu can do it!

Please visit the official documentation of ConEmu in order to learn more about it:  
https://conemu.github.io/en/DefaultTerminal.html

For the ConEmu-related questions, you can ask @Maximus5, the developer of the project

**Note:** Other than that, you can achieve this alternatively using **[Windows Terminal](https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration#default-terminal-application)** instead of the default ConEmu emulator.  It won't actually replace `conhost.exe` in the sense that you can open it directly from the run menu, but if you typed `cmd.exe` then Windows Terminal would launch instead of conemu.exe.
