### ISSUE TITLE
[Bug] Cursor Bug in Bash with λ in prompt (CJK)

### ISSUE THREAD

**Issue by lawweiliang** [cmderdev/cmder#2824]
### Version Information

```markdown
Cmder version: Version 1.3.18.1106
Operating system:
Window 10
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

The command that I type was automatically changed by cmder.

Before that,
![image](https://user-images.githubusercontent.com/34936929/218033960-d4ce5b01-94a5-423c-8c99-6ead42b5a955.png)

After that, press "up key" over keyboard
![image](https://user-images.githubusercontent.com/34936929/218033733-5ec0dff8-8d76-4b24-ad53-5528985bc0c7.png)

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment]
Read other recent issues.  There are many about this.

If you run `clink update` it should get some changes that compensate for CJK ambiguous width characters.  This is a CJK problem, which happens depending on the combination of font and code page and terminal program and characters in the prompt.

It should make the problem go away.  But after updating Clink and restarting Cmder, if it still occurs, then press `Ctrl-X` `Ctrl-Z` and read the diagnostic report and further steps it suggests.

**Comment by lawweiliang** [comment]
> 

Thanks for your reply @chrisant996 . I did't use `clink` for my usecase. 

I am using bash in cmder using this method. 
https://gist.github.com/nickautomatic/02ccb76292f7f8d9767e

>

**Comment by chrisant996** [comment]
> > 
> 
> Thanks for your reply @chrisant996 . I did't use `clink` for my usecase. 
> 
> I am using bash in cmder using this method. 
> https://gist.github.com/nickautomatic/02ccb76292f7f8d9767e

Oh. 😞 Sorry, then you can either run `chcp 65001` to use UTF8 and disable CJK code pages, or change the prompt character to an ASCII character instead of the lambda. There are some other issues with directions on how to do that.

**Comment by daxgames** [comment]
@lawweiliang Not sure why you would want to run bash this way since it is supported natively with the `Cmder - Full` you say you are using.  You could simply make the `Cmder` included task `{bash::bash}` your default task as shown below:

![image](https://user-images.githubusercontent.com/7318053/218233252-9c02877f-63bf-49e5-8220-0b4e8393be9f.png)

Also I do not believe you are using the config you think you are using because you would not have the `λ` in the prompt if you were.

Running `bash` according to the link provided is not using Cmder configuration at all.  It is simply using `ConEmu` and external component distributed as a part of `Cmder` to run your external install of Git Bash.  I am running the config detailed [here](https://gist.github.com/nickautomatic/02ccb76292f7f8d9767e) below:

![image](https://user-images.githubusercontent.com/7318053/218233123-afca29c7-687f-46b3-920d-63197a5bc7f8.png)

Notice the difference between mine, `$` instead of `λ`, where yours has the `λ`:

![image](https://user-images.githubusercontent.com/7318053/218233164-aa11a105-a98f-4034-8e83-eb31707c1986.png)

**Comment by lawweiliang** [comment]
@daxgames , oh man. This literally solved my problem. Thanks bro.

**Comment by daxgames** [comment]
@lawweiliang glad to help!
