### ISSUE TITLE
[Feature request] To be able to change the UI window color ?

### ISSUE THREAD

**Issue by seba9999** [cmderdev/cmder#2828]
### Suggestion

I would like to change that "white" background in the consoles list bottom bar. 

![image](https://user-images.githubusercontent.com/14869447/221020844-50acba55-026a-4d44-b0ab-cb5df67b4bbf.png)

Is it even possible ?
Is there already some conf to do it ?

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by daxgames** [comment]
This is not the place for that feature request.

Cmder user Conemu as its terminal emulator.  You should ask over there.

**Comment by DRSDavidSoft** [comment]
For reference, this issue is reliant on this: 

https://github.com/Maximus5/ConEmu/issues/1661

Author links to an issue in the bottom that explains dark theme / drawing is on the TODO list. After it is implemented in upstream, we will be able to address it here.

In the meantime you may also use one of the several other Terminal emulators that Cmder run with, including Windows Terminal if you are on Windows 10 and 11.

Links in the wiki:

https://github.com/cmderdev/cmder/wiki
