### ISSUE TITLE
[Bug] background color

### ISSUE THREAD

**Issue by kkm** [cmderdev/cmder#2872]
### Version Information

```markdown
Cmder version: latest
Operating system: windows

nodejs:
console.log("color background".yellow.inverse) doesnt work on cmder.
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

color problem doesnt show background.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by DRSDavidSoft** [comment]
@kkm Hi there, sorry for the delayed response.

Cmder is a pre-configured bundle that consists of a terminal emulator (ConEmu in this case) and some shells. Once you run `node.js`, Cmder is no longer in control of the output or how it is displayed, which means if there are any issues, it is related to ConEmu.

However, I have personally verified that `npm` packages work well with ConEmu and Cmder, since all that packages like this are doing is generating some [escape code](https://stackoverflow.com/a/33206814/1454514) sequences, which will make the text appear in different styles and colors universally in all VT100-like terminals (like ConEmu), regardless of the runtime and software package that generates it. This means that `colors.js` works as intended in Cmder, too.

Please add some screenshots and tests in other terminals to see if your code is only breaking on Cmder, otherwise we might not be able to help you.

P.S. I strongly suggest switching to a better and sane alternative to the abandoned `colors.js` package, such as **[chalk](https://github.com/chalk/chalk)**. This is because the Marak, who is the original author of `colors.js` went ballistic last year and decided to vandalize their own package: https://github.com/Marak/colors.js/issues/285 which means, the latest "official" release from them contains an intentional "bug" that causes an infinite loop and the rest of your code not running at all. It's a great troll effort, but unfortunately the side effect is that you'll be unable to use the latest release in your project.

Either revert back to an un-ruined version of `colors.js`, or switch to `chalk.js` which has a different syntax, thus requiring a re-factoring, but it works well and as intended. `chalk` is what I use in my own projects and it works without any issues.

**Comment by kkm** [comment]
cmder:
![image](https://github.com/cmderdev/cmder/assets/134290/7cd6d170-2793-4940-bdd2-7f646a6a5a1e)

Windows Terminal via Powershell:
![image](https://github.com/cmderdev/cmder/assets/134290/beee0b1b-070e-44fa-b062-bead922d40cd)

```
const colors = require('colors');
console.log("Text Green Only".green);
console.log("Green Text with Background".green.inverse);
```

@DRSDavidSoft okay thanks for recommend chalk and I didnt know before.
