### ISSUE TITLE
Question: Cmder keeps printing "y", is it a bug?

### ISSUE THREAD

**Issue by wkxjc** [cmderdev/cmder#2884]
### Question

One look is worth a thousand words:
![cmder_keeps_printing_y](https://github.com/cmderdev/cmder/assets/25922127/5980d8ab-36a4-4d0c-a595-65edc2b29356)

Reproduce steps:
1. Run command "echo off && echo", verify the "ECHO is off." printed.
2. Enter "yes", verify Cmder keeps printing "y".

The printing can be exited by "Ctrl + C" and the echo can be opened again by running command "echo on".

I think it's weird but I'm not sure if it's a bug.

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by chrisant996** [comment]
Cmder isn't doing that.

You launched the `yes.exe` program, which is part of git.

The purpose of the `yes.exe` program is to print `y` over and over, so that it can be used to pipe "yes" answers repeatedly into programs doing bulk operations (like deleting files or copying files or etc).

You can find out more about the `yes.exe` program with internet searches.

(Why did you launch the `yes.exe` program?)

**Comment by wkxjc** [comment]
@chrisant996 Thanks for the reply, I launch the `yes.exe` without intention, I've never heard of it before. An interesting knowledge learned.
