### ISSUE TITLE
CD in root not working..

### ISSUE THREAD

**Issue by jovvybersamin** [cmderdev/cmder#289]
When i am in the one of the directory of my root directory and i want to go back to the root directory using this command "cd ~" it is not working however when i am using git bash its running fine.

its said the system cant find the path specified..

**Comment by Battlegriffin** [comment]
**Hello everybody , may you all be having an amazing day when you read this.

I just started to learn Git and I downloaded Cmder.

When I want to find anything in it ,  I get this message that says:

 "The system cannot find the path specified"

Can anybody help me to fix this problem , please ?

As a consequence of this I can not find any project because my
Cmder is not finding the location of the folder it is at in the first place.

Thank you everybody!

This a picture of my actual cmder acting up:**

![cmder](https://user-images.githubusercontent.com/55010120/67721290-60242100-f993-11e9-8601-b309c4f6845a.JPG)

**Comment by daxgames** [comment]
You need to specify the correct paths for those folders there is no desktop folder or documents folder inside cmder

**Comment by daxgames** [comment]
Try 

```
Cd ..\desktop
```

Or 

```
Cd "..\my documents"
```

**Comment by Battlegriffin** [comment]
Thank you very much for your response daxgames , I really appreaciate it.

I tried : 
cd %userprofile%/documents and it worked.

But I still don't know how to access my files , check this out:

I have a folder called PROT inside a folder called HTML , in Documents , 
both with capitals.

I want to access the contents of PROT , but when I get there and type "1st",
I get an error , any light on this , man ? , here is the picture of it:

![cmder1](https://user-images.githubusercontent.com/55010120/67724266-bc8b3e80-f99b-11e9-94e1-f546e76fa6a6.JPG)

**Comment by daxgames** [comment]
I dont know what 1st is.  Type `dir` and post the output

**Comment by Battlegriffin** [comment]
Dude , I can see the contents !

I do want to say thank you because I did not know how to do that before you
told me , thanks a lot for that man.

On the other hand , what I want to do is to run the javascript file "prot.js" in the
Cmder , would you please give me your thoughts on how to do that?

Thanks a lot , man , here is the output of the command you gave me to try : 

![cmder2](https://user-images.githubusercontent.com/55010120/67726537-63bfa400-f9a3-11e9-95eb-2a3456ca1e9a.JPG)

**Comment by daxgames** [comment]
No idea not my area of expertise.
