### ISSUE TITLE
[Bug] cmder gets stuck on git reflog

### ISSUE THREAD

**Issue by Marco-Sulla** [cmderdev/cmder#2902]
### Version Information

```markdown
Cmder version: 230724 x64 stable
Operating system: Windows 11 22H2
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

cmder can't quit git reflog. This happens also to other less-like commands.

### How to reproduce

1. run `git reflog`
3. press `q`

Actual behaviour:
cmder does not exit the reflog. It gets stuck, and you have to restart the console.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by DRSDavidSoft** [comment]
Can you please share a recording of this behavior, and the behavior of plain ConEmu or `conhost.exe`?

If you are certain you can narrow it down to `less`, please use a command like `cat longfile.txt | less` instead of `git reflog` to produce the issue for tests.

Additionally, please run Cmder without ConEmu and attempt to repro the issue:
https://github.com/cmderdev/cmder/wiki/Cmder's-shell-in-other-terminals

**Comment by Marco-Sulla** [comment]
The problem is present in `ConEmu`, *but* it's different. In `ConEmu`, `git log` stucks and `git reflog` prints the output under the console, and it also stucks.

On `cmder`, `git log` works. `git reflog` shows as expected but does not quit.

`cat file | less` works. The problem arise with some `git` less-like commands.

I'll try to run `Cmder` without `ConEmu`.

**Comment by Marco-Sulla** [comment]
> Additionally, please run Cmder without ConEmu and attempt to repro the issue:
> https://github.com/cmderdev/cmder/wiki/Cmder's-shell-in-other-terminals

I run it and the problem still remains. After `q` is pressed, the control is not returned to the console and the console is stucked; I have to close it and relaunch.

**Comment by DRSDavidSoft** [comment]
@Marco-Sulla Can you also please test Cmder's PowerShell profile? Thanks

**Comment by Marco-Sulla** [comment]
git integration in the prompt is much slower, but `git reflog` work as expected in a cmder's powershell console.

**Comment by chrisant996** [comment]
@Marco-Sulla I wonder if you might be running into a variation of the MSYS issue described in #2670 and https://github.com/Maximus5/ConEmu/issues/2520.

Some things to try:
- Does the problem go away if you disable ConEmuHk injection?
- If you run `locale.exe` in a different tab in ConEmu, does that un-stick the tab that got stuck?

The issue is most likely a problem either in ConEmu or in git for Windows (or more specifically, the MSYS library used by git for Windows).

**Comment by Marco-Sulla** [comment]
> * Does the problem go away if you disable ConEmuHk injection?
> * If you run `locale.exe` in a different tab in ConEmu, does that un-stick the tab that got stuck?

How can I do that?

Notice anyway that the behavior of the issue under ConEmu and cmder is different.

**Comment by chrisant996** [comment]
[disable conemuhk injection](https://www.google.com/search?q=disable+conemuhk+injection)

Also [ConEmu issue 1510](https://github.com/Maximus5/ConEmu/issues/1510) describes the same kind of hanging and suggests that turning it off may help.

And one of the comments says that [another issue](https://github.com/Maximus5/ConEmu/issues/1736#issuecomment-533988575) suggested turning off "long console output" may resolve the hang (and has a screen shot for how to do so).

**Comment by Marco-Sulla** [comment]
I can't reproduce it anymore. WFM.
