### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by brunowego** [cmderdev/cmder#295]
I really like comder, this software saves much of my time, but I wish the full screen function, this feature exists or need develop this. 

Thanks :+1:

**Comment by WesternGun** [comment]
Now it is by default `Win+Ctrl+Alt+Enter` on Windows. Check `hotkey` part to confirm.

**Comment by eriegz** [comment]
@sc0tt or @WesternGun, thanks for the info. But now, how does one *exit* fullscreen mode after that?

The closest thing I can find is the "Maximize window" button that appears once you're in fullscreen mode:

![image](https://user-images.githubusercontent.com/10801672/109856862-38903900-7c17-11eb-8b03-22d865bec9af.png)

**Comment by chrisant996** [comment]
<kbd>Win</kbd>+<kbd>Down</kbd> (see documentation on Windows shortcut keys)

**Comment by eriegz** [comment]
> Win+Down (see documentation on Windows shortcut keys)

@chrisant996 Thank you kindly! Works like a charm. Although I'm not finding this documentation that you're referring to...

- [cmder's homepage](https://cmder.net/) and [the cmder README](https://github.com/cmderdev/cmder/blob/master/README.md) both show the shortcut for _entering_ Fullscreen (and the **_old_** shortcut, at that!), but not the shortcut for _exiting_ Fullscreen
- the [cmder wiki](https://github.com/cmderdev/cmder/wiki) doesn't seem to contain anything relating to keyboard shortcuts at all
- the only page I can find that even mentions <kbd>Win</kbd>+<kbd>Down</kbd> is this [ConEmu page](https://conemu.github.io/en/KeyboardShortcuts.html), but the description essentially just says "resize window", which is both confusing and ambiguous 
- and finally, in cmder's "Keys & Macros" settings, the actual entry for <kbd>Win</kbd>+<kbd>Down</kbd> has the description "[Disabled] Increase window height", which is both confusing and also **_contradictory_**, as if anything this action makes the window _smaller_!

Thus, I think a little touch-up on the ol' documentation might be in order. 🙂

**Comment by chrisant996** [comment]
I mean it's a Windows feature. Not Cmder or etc. It's part of the Windows operating system.

**Comment by eriegz** [comment]
Right, I didn't actually realize that's what <kbd>Win</kbd>+<kbd>Down</kbd> did! I use the Windows key all the time but never knew about that shortcut. Its use also seems pretty limited...

In any case, the key press sequence listed in cmder's docs for entering fullscreen mode (<kbd>Alt</kbd>+<kbd>Enter</kbd>) is still wrong, so that could get polished up.

Lastly, overall I feel that cmder's fullscreen feature is not very intuitive. For contrast, in Chrome it's <kbd>F11</kbd> to enter fullscreen, <kbd>F11</kbd> to exit. In YouTube—<kbd>F</kbd> to enter fullscreen, <kbd>F</kbd> to exit. Most people are used to this kind of "toggle" fullscreen behaviour.

I don't see why cmder a) has separate keyboard shortcuts for each direction, and b) specifically chooses NOT to document only one of them.

**Comment by xander-marjoram** [comment]
`Alt+Enter` worked a charm for me. My cat walked on my keyboard and I didn't know what he pressed so didn't know how to undo it!
