### ISSUE TITLE
[Bug] Wired caraters on the output when using `eza` command on cmder only

### ISSUE THREAD

**Issue by DrissBoumlik** [cmderdev/cmder#2951]
### Version Information

```markdown
Cmder version: 1.6.16.c5eaf9
Operating system: windows
```
![image](https://github.com/cmderdev/cmder/assets/3955809/0066b34e-8a1b-4d77-ba65-7458b025866f)

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

I installed eza which is a nice alternative for `ls`, 

* so when I type this command `eza --tree --level=2` on cmder I get this :

![image](https://github.com/cmderdev/cmder/assets/3955809/7c7a396a-fc44-46a0-931c-f7b603731144)

* and here is the result on cmd : 

![image](https://github.com/cmderdev/cmder/assets/3955809/d103c601-de25-4e42-80eb-414c253306f4)

### How to reproduce

Install eza and type `eza --tree --level=2`

### Checklist

- [ ] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [ ] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment]
> `Cmder version: 1.6.16.c5eaf9`

That's the Clink version, not the Cmder version. 

But Clink isn't related to this issue.

The ConEmu version could be related to this issue, though.

**Comment by DrissBoumlik** [comment]
@chrisant996 here is the conemu version 

![image](https://github.com/cmderdev/cmder/assets/3955809/41d6d261-d792-4dfc-84e4-bc4a7aad8eca)

**Comment by chrisant996** [comment]
It looks as though "ANSI X.364 / xterm 256 colors" might be turned off.  See [ConEmu documentation](https://conemu.github.io/en/AnsiEscapeCodes.html#ANSI_sequences_processing_requirements) for info about that setting.

The characters you're seeing are ANSI escape codes.  Normally ConEmu handles them and changes colors and etc. 

If that setting is on (checked) in the Features page, then I don't know why the escape codes are not being handled.  You'll need to do some troubleshooting in ConEmu.

I was only responding to say this isn't related to Clink (since the Clink version was cited).

**Comment by DrissBoumlik** [comment]
So appearently, `Inject ConEmuHk` was off, I set it to on and it worked 

![image](https://github.com/cmderdev/cmder/assets/3955809/e4776d33-d4a9-49a7-982a-22c5e2b4a776)

![image](https://github.com/cmderdev/cmder/assets/3955809/deaa4eae-8514-49a1-bc76-e3e5fef7fb78)
