### ISSUE TITLE
Question: yaquake

### ISSUE THREAD

**Issue by buckelieg** [cmderdev/cmder#2957]
### Question

Any plans to make it resemble a yaquake like style? I.e. could it be implemented as dropdown console from the top of the screen?
Thanks. 

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Don't know whayt yaquake is.  Cmder is configuration gluing together several off the shelf packages.  Currently the default terminal emulator is a package called ConEmu.  This is probably a better question for @Maximus5 the developer of ConEmu

**Comment by DRSDavidSoft** [comment]
@buckelieg I don't know about Yakuake per se, but ConEmu (the terminal emulator that Cmder by default uses) has a quake mode:

https://conemu.github.io/en/SettingsQuake.html

In any case you should ask questions like this on each individual terminal emulator repo, which as for ConEmu is this link:

https://github.com/Maximus5/ConEmu/issues

Since this issue is unrelated to Cmder, I'm going to close it.
