### ISSUE TITLE
Question: Proxy Setting v2ray

### ISSUE THREAD

**Issue by lolminerxmrig** [cmderdev/cmder#2967]
### Question

Hi
I need using cmder through proxy (because of some restriction on my network and failed to get some github libraries from repos)
I had lots of search, nothing found about proxy setting in cmder v2ray.
Any solution?
Tnx

![image](https://github.com/user-attachments/assets/7f481fa4-9176-40c3-a966-00a683bb76d1)

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
Hi there @lolminerxmrig 

Cmder doesn't interfere with any environment variable, including the proxy settings. They are still handled by Windows.

In your screenshot, you are setting the proxy variables to `127.0.0.1:2080`. Then you are invoking the `curl` command, which uses this setting to connect to `ip.gs` domain.

Now curl is exactly doing this, and reporting it in the terminal too:

```
curl: (7) Failed to connect to 127.0.0.1 port 2080 after 2040 ms: Couldn't connect to server
```

It's saying that Curl _did_ try to connect to your proxy server in order to send the request and then failed to do so.

This means that this is not an issue related to Cmder; this I will now close the issue.

Now, in order to help you a bit more. You need to debug and investigate your proxy server. Is it indeed a HTTP proxy server? Can you open this link?

http://127.0.0.1:2030/

Maybe V2Ray isn't http proxy. Maybe it's socks, in which case you need to set the proxy type of socks, not http.

```
socks5://127.0.0.1:2030/
```

You need to set the appropriate proxy settings. Cmder doesn't change the variables. It's handled by the operating system and applications themselves.

Good luck.

**Comment by lolminerxmrig** [comment]
set socks5://127.0.0.1:2080/
Environment variable socks5://127.0.0.1:2080/ not defined

**Comment by DRSDavidSoft** [comment]
That's not how it works, you need to pass the value to a  variable name like this:

```
set http_proxy=socks5://127.0.0.1:2080
set HTTPS_PROXY=socks5://127.0.0.1:2080
```
