### ISSUE TITLE
[Bug] When I search in Arabic doesn't get result

### ISSUE THREAD

**Issue by mohseenjamall** [cmderdev/cmder#2972]
### Version Information

```markdown
Cmder version: 230724 stable
Operating system: Win 11 x64
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

When I search in Arabic like this
.
![Screenshot 2024-09-28 144501](https://github.com/user-attachments/assets/cd940dd2-e441-47cd-babb-93ea8e7c4d2f)

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by DRSDavidSoft** [comment]
Hi there, 

The علوم شرعیة seems to be a directory. What are you trying to do?

If you are trying to cd into it, `cd 'علوم شرعیة'` should do the job. If you need to open the folder in explorer, simply change the `cd` command to `explorer`.

Alternatively, you are looking at the auto complete or auto suggest functionality of the shell, which is provided by tab or Ctrl + space.

Please note that all of this is provided by Clink, which is the shell that Cmder uses, this we can't really help with that:

https://github.com/chrisant996/clink

If you would like, please fill the information below so that I can understand what you're trying to do.


**Steps to reproduce*"
E.g.:
1. Type ...
2. Press ...

**Desired behavior**
What you want to see. Provide an example of what happens with non-Arabic characters.

**Actual Behavior**
What is happening that is not correct? Is something not working? Post a screenshot of what _should_ happen instead, if it worked correctly.

**Comment by chrisant996** [comment]
@mohseenjamall It looks like you are trying to use single quotes `'` around the path with spaces.

Cmd.exe only support double quotes `"`.

This has nothing to do with Cmder or Clink, this is just a misunderstanding about the difference between how cmd.exe works on Windows, versus how Linux shells work on Linux.

**Comment by mohseenjamall** [comment]
@chrisant996 It's work thanks bro.
