### ISSUE TITLE
[Feature request] Language FR

### ISSUE THREAD

**Issue by GitHubGregory** [cmderdev/cmder#2973]
### Suggestion

 would like to integrate my translation file into your repository (however, it's not loading correctly, there's a small bug). Could you take a look?"
[ConEmu_fr_no_accents.json](https://github.com/user-attachments/files/17249230/ConEmu_fr_no_accents.json)

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by DRSDavidSoft** [comment]
Hi there @GitHubGregory 

As the Cmder team, we simply include **ConEmu** in this GitHub repository without any additional modifications, including translations.

You will need to submit your translations for ConEmu directly in the owner's repo, so that we can include it in Cmder:
https://github.com/Maximus5/ConEmu

Please open a **new issue** over the aforementioned repository to get started. As such, this issue will be closed.

Please be aware that the original author for ConEmu has been inactive for a while, so responses over there might be slow, however we are not able to help in that regard.

Thanks for your interest and using Cmder and ConEmu!
