### ISSUE TITLE
Setting Cmder as default term opens ConEmu instead

### ISSUE THREAD

**Issue by wheelerlaw** [cmderdev/cmder#307]
If you open the settings for Cmder and set it to be the default terminal, and then go open cmd.exe, it will open ConEmu, not Cmder.

**Comment by ticklemynausea** [comment]
+1

Wish I had any valuable input. I'd really like this fixed.

**Comment by djds4rce** [comment]
I have found a workaround, At Least a non irritation. Add cmdr folder to your PATH and in run type 'cmder'. Two extra characters.

**Comment by ticklemynausea** [comment]
Nice tip!

Just a thought: maybe I can add a symlink named cmd.exe to a PATH with
higher precedence than C:\Windows\System32 (or wherever cmd.exe is located)
?

On Tue, Jan 6, 2015 at 10:37 AM, Dayanand Prabhu <notifications@github.com>
wrote:

> I have found a workaround, At Least a non irritation. Add cmdr folder to
> your PATH and in run type 'cmder'. Two extra characters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bliker/cmder/issues/307#issuecomment-68850326>.
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by bertrandriche** [comment]
That workaround works for manually opening a cmd window, but it won't for any other software opening console windows (for example .bat or .sh files, or any other software starting the process through their code, that we can't change...).

**Comment by danijar** [comment]
+1

**Comment by babhishek21** [comment]
The settings you are talking about are actually settings for __ConEMU.__ ConEMU is the *emulation layer*, not the terminal itself. So when you are doing in reality is setting ConEMU as default (with its default terminal/FAR Manager setup).

The correct way to do this is to create a hard link to **Cmder.exe** file (or do some very clever hacks). That's possible only through the Windows registry. [Look here](http://superuser.com/questions/810550/how-to-replace-the-cmd-alias-in-windows) for a good way to achieve this.

**Comment by Gedankenleser** [comment]
+1

**Comment by wheelerlaw** [comment]
"The settings you are talking about are actually settings for ConEMU. ConEMU is the emulation layer, not the terminal itself. So when you are doing in reality is setting ConEMU as default (with its default terminal/FAR Manager setup).

The correct way to do this is to create a hard link to Cmder.exe file (or do some very clever hacks). That's possible only through the Windows registry. Look here for a good way to achieve this."

It would be nice if instead of having to the the hacks myself, it was integrated into cmder itself.

**Comment by babhishek21** [comment]
@wheelerlaw Even though Cmder is just great at what it does, I still wouldn't recommend linking/replacing `cmd.exe` with Cmder. A lot of things still don't work well with Cmder and terminal emulation. Permissions are another sore point. You wouldn't want `cmd.exe` missing from your toolbox in those circumstances.

**Comment by Maximus5** [comment]
cmder is neither terminal nor shell. So when you start cmder, it just starts ConEmu in turn (which is terminal). So, it's absolutely unclear what you are complaining for.

The wrong xml file location, used by cmder before, raised more problems than you think, and it was fixed. Proper xml file location is inside ConEmu subfolder.

**Comment by Maxmaxmaximus** [comment]
@Maximus5 so wat we do do???? help man.
cmder has pretty interface then..

короче у кон ему графон лучше чем у тебя раз в 20, жалко автор рукожоп и не смог нормально скопипиздить твой терминал, скажи куда жать чтобы его прописать как замену cmd?

**Comment by babhishek21** [comment]
@Maxmaxmaximus What do you really need to replace `cmd.exe` with **Cmder**? Applying to specific scenarios is much better, than messing with the registry or doing deep-linked changes.

**Comment by Maxmaxmaximus** [comment]
![image](https://cloud.githubusercontent.com/assets/3730167/11018556/ea052670-85df-11e5-96db-bb659c253384.png)

this is way when i open terminal. righr click in start button and click then.
need to be open cmder but not cmd)

**Comment by Jackbennett** [comment]
We can probably just register to that menu at the same time we register the folder r-click handler I'm sure.

**Comment by MartiUK** [comment]
I believe it's something to do with `C:\Users\$USER\AppData\Local\Microsoft\Windows\WinX`, I'm not too sure since I'm not using a Win 10 machine at the moment.

**Comment by Jackbennett** [comment]
All the shortcuts in win+X are here `C:\Users\jbennett\AppData\Local\Microsoft\Windows\WinX`

They have registry entries here for some reason `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\ShellCompatibility\InboxApp`

You can't add your own shortcut here as windows check the hash of these files before displaying them on the start menu. Same goes for just targeting an existing one.

Someone needs to find out how to add new hashes to this wherever the check list is because cmder won't be disabling the hash checking as [described here to add new items](http://www.askvg.com/exclusive-how-to-add-new-shortcuts-in-quick-access-menu-win-x-menu-of-windows-8/). I personally won't be disabling that myself ever.

I suspect if anyone does disable the hash checking you should disable windows defender or whatever it's called from scanning that file. Just like when editing your hosts file windows my try changing it back in future.

**Comment by Jackbennett** [comment]
And the answer would be [described here](http://www.instantfundas.com/2012/04/customize-or-add-new-shortcuts-to-winx.html) tho it looks like Rafael Rivera redesigned the blog and I can't find any of this information anymore.

We could probably just do this directly instead of having to pull in hashlink for what I assume is a rarely used command.

**Comment by MartiUK** [comment]
@Jackbennett The blog link worked fine for me, I can see the instructions there.

If a user wants to change it, they can do it themselves, we shouldn't go any further than what's sensible. Conemu can 'replace' conhost (i.e. hook whenever cmd is launched) but it's a global change, it doesn't change the default windows shell shortcuts that a lot of people use (and it shouldn't).

**Comment by Maximus5** [comment]
cmder is sort of ‘boot loader’ for ConEmu.
But due to selected architecture users just can't use several ConEmu functions,
I've already written about them.

So, to solve problems...

1. No need to pass icon as `/icon` switch. Just put proper `ConEmu.ico` into `conemu-maximus5` folder.
2. `CMDER_ROOT` variable. Of course it's not set on `ConEmu.exe` startup, but there is `ConEmuDir` and `ConEmuBaseDir`, and it would be better to use relative paths with it. For example, `/icon "%ConEmuDir%\..\..\cmder.exe"` for {cmd} task.

**Comment by bitbonk** [comment]
@Maximus5 
> 1. No need to pass icon as /icon switch. Just put proper ConEmu.ico into conemu-maximus5 folder.

This does not change the icon in the taskbar only in the window.
> 2. CMDER_ROOT variable. Of course it's not set on ConEmu.exe startup, but there is ConEmuDir and ConEmuBaseDir, and it would be better to use relative paths with it. For example, /icon "%ConEmuDir%\..\..\cmder.exe" for {cmd} task.

This does not work for me at all:
The cmder below was started with `Win+S->"cmd"`
![image](https://cloud.githubusercontent.com/assets/418030/22165633/3a08b38a-df5d-11e6-9ab4-f41aa5990635.png)

**Comment by Maximus5** [comment]
@bitbonk 

> This does not change the icon in the taskbar, only in the window.

False.

![2017-01-23_12-46-06](https://cloud.githubusercontent.com/assets/1222388/22198968/edf5fcd2-e169-11e6-8266-2d8b34f297ad.png)

> the cmder below was started with Win+S->"cmd":

And why do you think, that ConEmu/cmder/whatever should start `init.bat` if you asked to run `cmd.exe`?
Run ConEmu if you want to run the **Task** you have specified.

**Comment by Jackbennett** [comment]
I don't know why this is still getting traction,

To round off the discussion;

1. Cmder is a separate program, not cmd.exe and will not replace it.
1. Cmder by default wraps cmd.exe so replacing cmd.exe is a terrible idea.
1. Cmder wraps ConEmu that glues everything together. Hence the icon shenanigans.
1. There's some extra shortcuts in win+X that could exist but it's more invasive that we choose to be with cmder so it won't get added.

2.5 years I think we'll put this one to bed. Make new issues for things other than the topic of "Setting Cmder as default term opens ConEmu instead"

Thank you @Maximus5 and everyone you're very patient.

**Comment by aplocher** [comment]
I realize this is an old closed issue, but if you're like me, hitting WINKEY+R -> CMD.EXE ->[ENTER] is like a reflex to you.  There is a registry key that takes precedence over the %PATH% variable for certain things executed through Windows such as through the Run dialog (or any Windows Address bar, i.e., IE and Windows Explorer).  This is why several apps in Windows "just work" without needing to be in the %PATH%.

I've been using this method for years, it's only caused problems once for a small insignificant Visual Studio extension (see below for details).

Whenever I load up a new Windows box, I always add the following keys (add with Regedit or add this to a .reg file and run):

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\cmd.exe]
@="C:\\TEMP\\CMDER\\CMDER.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\np.exe]
@="C:\\Program Files\\Notepad++\\notepad++.exe"

```

![image](https://cloud.githubusercontent.com/assets/1132447/22723062/3bd2326a-ed70-11e6-98e9-e4822de6b859.png)


(note, the "np" one is insignificant to this post, but it's just a cool way to alias notepad++ that I thought I would share)

That reg key registers a virtual "cmd.exe" command that takes precedence over C:\Windows\System32\cmd.exe and redirects to cmder.

The ONLY time I ever saw it have a problem was when a Visual Studio extension was launching "cmd.exe" and tried passing in standard Windows cmd.exe arguments, such as "/k" to run a command but leave the window open.  It would be nice if cmder.exe and/or conemu.exe had the same args available (or a small proxy app that mapped them over), because then it would truly be a flawless method (from my experience).

So this method should fix anything that uses the Address bar/Run dialog/whatever-internal-windows'y-way-of-resolving-a-command.  As far as the Start Menu icon, you can easily just create your own shortcut and replace the included one.  

![image](https://cloud.githubusercontent.com/assets/1132447/22723130/bf3c4212-ed70-11e6-9d4b-6301780610c3.png)

The only other thing would be adding it to the beginning of your %PATH% so any bat files and commands from the console get mapped over, but THAT I haven't tested.  Probably dangerous if a bat file is using cmd.exe with any arguments.

**Comment by murad-alm** [comment]
> 
> 
> I realize this is an old closed issue, but if you're like me, hitting WINKEY+R -> CMD.EXE ->[ENTER] is like a reflex to you. There is a registry key that takes precedence over the %PATH% variable for certain things executed through Windows such as through the Run dialog (or any Windows Address bar, i.e., IE and Windows Explorer). This is why several apps in Windows "just work" without needing to be in the %PATH%.
> 
> I've been using this method for years, it's only caused problems once for a small insignificant Visual Studio extension (see below for details).
> 
> Whenever I load up a new Windows box, I always add the following keys (add with Regedit or add this to a .reg file and run):
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\cmd.exe]
> @="C:\\TEMP\\CMDER\\CMDER.EXE"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\np.exe]
> @="C:\\Program Files\\Notepad++\\notepad++.exe"
> ```
> 
> ![image](https://cloud.githubusercontent.com/assets/1132447/22723062/3bd2326a-ed70-11e6-98e9-e4822de6b859.png)
> 
> (note, the "np" one is insignificant to this post, but it's just a cool way to alias notepad++ that I thought I would share)
> 
> That reg key registers a virtual "cmd.exe" command that takes precedence over C:\Windows\System32\cmd.exe and redirects to cmder.
> 
> The ONLY time I ever saw it have a problem was when a Visual Studio extension was launching "cmd.exe" and tried passing in standard Windows cmd.exe arguments, such as "/k" to run a command but leave the window open. It would be nice if cmder.exe and/or conemu.exe had the same args available (or a small proxy app that mapped them over), because then it would truly be a flawless method (from my experience).
> 
> So this method should fix anything that uses the Address bar/Run dialog/whatever-internal-windows'y-way-of-resolving-a-command. As far as the Start Menu icon, you can easily just create your own shortcut and replace the included one.
> 
> ![image](https://cloud.githubusercontent.com/assets/1132447/22723130/bf3c4212-ed70-11e6-9d4b-6301780610c3.png)
> 
> The only other thing would be adding it to the beginning of your %PATH% so any bat files and commands from the console get mapped over, but THAT I haven't tested. Probably dangerous if a bat file is using cmd.exe with any arguments.


**This is literally the ONLY method that worked for me.
Thank you @aplocher!!!**
