### ISSUE TITLE
Can't type in SSH mode after a certain time

### ISSUE THREAD

**Issue by kfirba** [cmderdev/cmder#347]
I noticed that whenever I'm going into SSH mode after a certain amount of time that I keep it logged in and not doing anything and then I come back and try to execute a command, the cursor is stuck. I can type as much as I want but it simply won't show anything.

I've also tried to paste some text, or type `exit` but it simply doesn't work. However, the cursor is still blinking. If I want to make it work, I have to exit `cmder` and open a new instance or a tab and re-connect. 

As you can imagine, it gets pretty annoying that for every task I want to do I have to open a new tab/instance, especially when writing tests.

An image to describe how it looks after it gets stuck:
![capture](https://cloud.githubusercontent.com/assets/8510486/5408635/0d62ca62-81e7-11e4-91e6-a38f3379997c.PNG)

**Comment by RDeluxe** [comment]
Same here.

**Comment by MartiUK** [comment]
Have you tried running ssh with `ssh -v` or `ssh -vvv` and seeing the output?

**Comment by mabasic** [comment]
I have not tried, but lately I am not having this problem as far as I can tell.

**Comment by notflip** [comment]
Same issue here, any news on this?

**Comment by RDeluxe** [comment]
This still happens every once in a while. I just can't type anything when it happens

**Comment by MartiUK** [comment]
_All Hosts_

Add the following lines to the %HOME%/.ssh/config file (create if it doesn’t exist)

```
Host *
    ServerAliveInterval 60
```

Make sure you indent the second line.

_Per-Host_

If you only want to enable keep alive for a single server, you can add that into the %HOME%/.ssh/config file with the following syntax:

```
Host *hostname.com
    ServerAliveInterval 60
```

**Comment by Fed03** [comment]
@MartiUK not working sadly, also it happens to after 20-30 seconds of inactivity

**Comment by necenzurat** [comment]
The issue is not only on SSH, it's everywhere!

**Comment by Rjs37** [comment]
I'm also experiencing this issue, using Windows 8.1. Only when connected via SSH. I also get the same issue in Git Bash too but I've tried the fix suggested above (in my user directory/.ssh) but it's still not working.

It's timing out while I'm trying to run composer install on a directory, I can't even tell whether it completes or not. Also happens if I leave it whilst awaiting a command. 

If I kill the process it then kicks me out of the ssh and lets me reconnect without even re-opening cmder. I'm connecting via ssh to a virtual box on my PC if that makes any difference.

**Comment by iamfreee** [comment]
Also getting this :(

**Comment by Arcovion** [comment]
Type `<Enter>~.`, this is the escape sequence to terminate SSH.

**Comment by iamfreee** [comment]
@Arcovion that works to close the connection. But the problem is there yet.

**Comment by qeatzy** [comment]
come into this issue too. no ssh.

**Comment by UberGruber** [comment]
Hey there same problem, not only that I can't type anything also with `ssh-keygen` at _Enter Passphrase_: blink cursor and that's it, no way to type. Though using `ctrl+c` I can sucessfully exit the prompt and get back to normal console.

**Comment by Arcasss** [comment]
Same problem for me, it happens using different consoles (cmd, bash, ssh, ...). Cursor is stucked, nothing else is happening. Must wait around 15 seconds to get unstuck.

**Comment by Rjs37** [comment]
I didn't realize people were still having this issue. I found a fix a few months after I first commented.

I had to use the vagrant commands rather than homestead.  I needed to re-create my box (using vagrant up) but since then I'm having no timeout issues using vagrant ssh.

This article helped me realize the issue: http://stagerightlabs.com/blog/running-homestead-2-on-windows
