### ISSUE TITLE
Start cmder with different conemu.xml?

### ISSUE THREAD

**Issue by CumpsD** [cmderdev/cmder#357]
How do I start Cmder with a different conemu.xml?

I tried added /config after cmder.exe but that was not allowed as an option to the wrapper

Reason:
I share cmder via dropbox accross multiple machines, one being a high dpi machine which requires Cmder to use a much higher font to be readable (eg 23 px) while on my normal machine I have it at 16px.

I open Cmder via pinned to taskbar shortcuts, which allows me to configure different cmdline options on the different pcs, so I wanted to let them use a different config file depending on machine, but didnt find a clean way to do this.

**Comment by vladimir-kotikov** [comment]
My proposal is to update Cmder launcher to support per-machine/per-user configuration by setting a %CMDER_CONFIG% environment variable. I'm working now on prototype for this...
@MartiUK Your thoughts?

**Comment by CumpsD** [comment]
That would be a very nice solution, and identical to much of the tools I currently have set up. I'd very much love that :+1:

**Comment by MartiUK** [comment]
@vladimir-kotikov As long as cmder remains portable and has the current default, I don't see why not.

**Comment by vladimir-kotikov** [comment]
Yep. Could you pls assign this issue to me then...

**Comment by vladimir-kotikov** [comment]
Ooops... You can't because i'm not a repo member :(

**Comment by Jackbennett** [comment]
I guess just closing pending further discussion on a new PR as referenced at the end of #368.

Might I suggest doing this would need some kind of inheritance to be worked out. Cmder would already be user specific and added more user customisations since this. So you'll have to figure out a way of slotting in machine settings between user and vendor that cmder ships. Then decide if it's a different default user overrides or machine settings take priority. 

Maybe if you're changing a lot just fork cmder and change you own org settings in the vendor area and install your version. I don't think keeping up to date with cmder should have many problems. And if it does maybe that would expose better answers to above questions. First thing I can think of be careful with conemu.xml as it changes a load of date.time stamps on settings even though settings don't change. It makes diffs super noisy.

**Comment by daxgames** [comment]
This is possible today using the comoitername specific conemu.xml.  Just copy 'vendor/maximus5-conemu/conemu.xml' to 'config/conemu-%COMPUTERNAME%.xml'.  Any change from this point forward done using the conemu fui will also be backed up in the file you copied.
