### ISSUE TITLE
Quake-style window opens every time when desktop gets empty

### ISSUE THREAD

**Issue by twasilczyk** [cmderdev/cmder#393]
Steps to reproduce:
 1. Close all running programs and windows (workspace should be totally empty)
 2. Settings -> Main -> Appearance -> Quake style slide down
 3. Hide cmder (by default, Ctrl + `)
 4. Open start menu, close it (desktop gains focus)
 5. Cmder is visible again

**Comment by fibric** [comment]
does not happen on my corporate machine. but when i open cmder and hide it via ctrl+` then its window is opening again. this issue isn't always reproducible.

using v1.2.9 in windows7-64 enterprise

**Comment by Jackbennett** [comment]
I suspect if this is even fixable it's conemu. Just because conemu is what's dealing with the display.

I have had a number of windows get stuck on top of things or under each other that can only be rectified by emptying the desktop. It might just be a quirk of how it's being hidden.

Maybe you can work around it toggling the options to minimize to taskbar or similar.

**Comment by pavelkouril** [comment]
Can confirm, this bug has been in ConEmu for a loong time (I've been using ConEmu ever since like ... 2012?).

**Comment by Jackbennett** [comment]
Afraid all we can do it hopefully point some help towards conemu about it.
