### ISSUE TITLE
How to update bash

### ISSUE THREAD

**Issue by amrdraz** [cmderdev/cmder#399]
I'm trying to install rvm using cmder and I get
Bash 3.2.25 required (you have 3.1.0(1)-release)

how do I upgrade bash?

**Comment by WEREMSOFT** [comment]
HOW?!?! HOOOOW!?!?!?!?

**Comment by denolfe** [comment]
Someone can correct me if I'm wrong, but I believe since cmder uses [Git for Windows](https://msysgit.github.io/) for its bash implementation. Therefore, for releases Cmder is tied to whatever bash version that uses (3.1.23 is the latest). You can run the installer for that and replace your entire `msysgit` folder in `cmder\vendor`.

However, if you wanted to some fiddling, the `bash.exe` being used is located in `cmder\vendor\msysgit\bin`.
