### ISSUE TITLE
Not scaling on Windows 8.1 with High-DPI Monitor

### ISSUE THREAD

**Issue by LondonAppDev** [cmderdev/cmder#437]
The application is not scaling to support a High-DPI monitor on Windows 8.1. I am using a Dell XPS 15 with a 4k screen. 

When doing a Google search I found this issue: https://github.com/bliker/cmder/issues/182. It says that the issue is resolved and the post is closed, however for me it still looks like this (I have GitHub open next to it to gauge the difference):

https://dl.dropboxusercontent.com/u/22916128/GitHub_Cmder_Scaling.png
(GitHub wouldn't let me upload the image even after saving it as a PNG or JPG)

**Comment by markwint** [comment]
OK, I just re-read issue #182 and now I understand how to fix it.

For anyone else with the issue here is how you can solve it manually:

1. Visit http://www.fosshub.com/ConEmu.html and download the latest portable version
2. Extract all the files downloaded. You need 7zip (http://www.7-zip.org/) for this
3. Copy all the extracted files to \vendor\conemu-maximus5 (assuming you are starting at the root cmder directory). I recommend just renaming the old `conemu-maximus5` directory to `old_maximus5` first in-case you need to revert.

Then when you start cmder it will scale nicely.

**Comment by MartiUK** [comment]
This will be fixed in the next version, as we are using the latest version of conemu.

**Comment by bwlv** [comment]
Can confirm following markwint's steps as a solution to scaling issues on Windows 8.1

**Comment by MartiUK** [comment]
This has been fixed upstream for a long time now.
