### ISSUE TITLE
Ctrl+click to open local file paths?

### ISSUE THREAD

**Issue by UltCombo** [cmderdev/cmder#446]
Currently, <kbd>ctrl</kbd>+left click opens URLs.
Would it be possible to open local file paths with the same logic?

Running Zsh through Cygwin's mintty.exe supports ctrl+left click to open both URLs and local file paths as well.

**Comment by afffsdd** [comment]
if this would possible that would be sick as hell

**Comment by Jackbennett** [comment]
I Think you'll have to ask the conemu project about this one. It's not something our cmder parts specifically are doing anyway

**Comment by UltCombo** [comment]
Hey @Jackbennett, thanks for replying. I previously thought cmder was a fork of ConEmu, but from your comment I presume it is an extension/wrapper of some kind? Is there documentation about the scope of this project and what issues should filed here? Just curious.

**Comment by Jackbennett** [comment]
Hi @UltCombo cmder isn't a fork, it's a project that's the front of our set of programs we've found make a nice console, one of those programs being conEmu. I find conemu quite thick on documentation (because it con do tons of stuff) so have a look on [their site](https://conemu.github.io/) for all kinds of help. If you still can't get this feature I'm sure they wouldn't mind the request on [github](https://github.com/Maximus5/ConEmu)

It's not uncommon for it's author Maximus5 to be around our issue queue which is why we tag things about that project. 

Perhaps start [here](http://conemu.github.io/en/FileLineDetector.html)

If you work something cool out show us! we might add it.

**Comment by TONYHOKAN** [comment]
i found that we could go setting->Keys & Macro->Highlight to config, just update the command action like change `far.exe /e%1:%2 "%3"` to  `#notepad++.exe -n%1 "%3"`

screen shot of official doc 
https://conemu.github.io/en/SettingsHighlight.html

**Comment by Arefalhaj** [comment]
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder]
@="Open Cmder Here"
"Icon"=hex(2):45,00,3a,00,5c,00,6c,00,61,00,72,00,61,00,67,00,6f,00,6e,00,5c,\
  00,62,00,69,00,6e,00,5c,00,63,00,6d,00,64,00,65,00,72,00,5c,00,69,00,63,00,\
  6f,00,6e,00,73,00,5c,00,63,00,6d,00,64,00,65,00,72,00,2e,00,69,00,63,00,6f,\
  00,00,00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command]
@=hex(2):22,00,45,00,3a,00,5c,00,6c,00,61,00,72,00,61,00,67,00,6f,00,6e,00,5c,\
  00,62,00,69,00,6e,00,5c,00,63,00,6d,00,64,00,65,00,72,00,5c,00,43,00,6d,00,\
  64,00,65,00,72,00,2e,00,65,00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,22,\
  00,00,00

**Comment by Arefalhaj** [comment]
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder]
@="Open Cmder Here"
"Icon"=C:\laragon\bin\cmder\Cmder.exe

[HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command]
@=C:\laragon\bin\cmder\Cmder.exe
