### ISSUE TITLE
Notifications about composer.json and CRLF

### ISSUE THREAD

**Issue by Deele** [cmderdev/cmder#472]
I just downloaded full version of cmder and ran it.

After executing any command, I get notification at the end of executed command real output:

```
warning: LF will be replaced by CRLF in composer.json.
The file will have its original line endings in your working directory.
```

For example:

```
C:\Users\Deele
λ cd /d M:\WebDev\projects\eilc\tests\

warning: LF will be replaced by CRLF in composer.json.
The file will have its original line endings in your working directory.
M:\WebDev\projects\eilc\tests (master)
λ ls -la
total 9
drwxr-xr-x    1 Deele     Administ     4096 May 10 02:29 .
drwxr-xr-x    1 Deele     Administ     4096 May 10 01:53 ..
-rw-r--r--    1 Deele     Administ     3752 May  9 22:10 README.md
drwxr-xr-x    1 Deele     Administ     4096 May 10 02:17 codeception
-rw-r--r--    1 Deele     Administ      987 May 10 02:29 codeception.yml

warning: LF will be replaced by CRLF in composer.json.
The file will have its original line endings in your working directory.
```

I don't understand that warning: what "composer.json" file is it talking about? what is my working directory? why is it warning every time I do something? did I do something wrong?

**Comment by Jackbennett** [comment]
Its git warning about line endings your file uses. This is a problem when using files between linux and windows. Have a read of [githubs advice](https://help.github.com/articles/dealing-with-line-endings/).

What is gits current setting if you run `git config --get-all core.autocrlf`? Mine is set to true but I use my own installed git not cmders full verison.

**Comment by Deele** [comment]
What are you talking about? Is cmder conflicting with git that is installed on my system?

The output of `git config --get-all core.autocrlf` command:

```
λ git config --get-all core.autocrlf
true
true

warning: LF will be replaced by CRLF in composer.json.
The file will have its original line endings in your working directory.
```

**Comment by Jackbennett** [comment]
Git is just telling you that when you commit the file to the repo it's going to fix the line endings to be consistent across any operating system that would view the file. The output is from cmder running `git status` each time to keep the notification up to date.

I guess it's because whatever made composer.json was a windows program and didn't use the most appropriate line endings in the file.

If you have git installed yourself you just needed to get the minimal download. It shouldn't matter I think whatever version of git will still use your configuration.
