### ISSUE TITLE
update msysgit

### ISSUE THREAD

**Issue by dotnetCarpenter** [cmderdev/cmder#473]
Seems the [msysgit](https://github.com/msysgit/msysgit) bundle with `cmder` is outdated. A lot of security patches are in - not sure what else. https://github.com/msysgit/msysgit/releases

    λ where git
    C:\Users\dotnet\src\cmder\vendor\msysgit\bin\git.exe
    C:\Users\dotnet\src\cmder\vendor\msysgit\cmd\git.exe
    C:\Program Files (x86)\Git\cmd\git.exe

I have both `cmder` and *git bash* installed.

    λ C:\Users\dotnet\src\cmder\vendor\msysgit\bin\git.exe --version
    git version 1.9.4.msysgit.0

    λ "C:\Program Files (x86)\Git\cmd\git.exe" --version
    git version 1.9.5.msysgit.1

**Comment by nhudacin** [comment]
Don't know if this will help you, but it worked for me. The vendor/init batch file injects msysgit bundled with commander to the beginning of your path https://github.com/bliker/cmder/blob/master/vendor/init.bat. I modified it to inject everything at the end so that my git bash installation was used.

λ where git
C:\Program Files (x86)\Git\cmd\git.exe
C:\_Utilities\Cmder\vendor\msysgit\bin\git.exe
C:\_Utilities\Cmder\vendor\msysgit\cmd\git.exe

λ which git
C:\Program Files (x86)\Git\cmd\git.EXE

This is what my init.bat file looks like: 

:: Enhance Path
@set git_install_root=%CMDER_ROOT%\vendor\msysgit
@set PATH=%PATH%;%CMDER_ROOT%\bin;%git_install_root%\bin;%git_install_root%\mingw\bin;%git_install_root%\cmd;%git_install_root%\share\vim\vim74;%CMDER_ROOT%

Is there any value in leaving this in or should we just remove msysgit from the cmder path/init file altogether?

**Comment by dotnetCarpenter** [comment]
Hmm I wonder if msysgit is the only difference between full and mini.
@nhudacin thanks for your input. I did what you suggested.
But the issue remains - msysgit should be updated

**Comment by strebl** [comment]
I'm using cmder with the new msysgit (https://github.com/git-for-windows/git) for a while. No problems so far. Just altered the init.bat because the paths are slightly different.

**Comment by dotnetCarpenter** [comment]
@strebl Do you mind making a PR with your changes?

**Comment by strebl** [comment]
@dotnetCarpenter Sure, I would do that. But before I'll start it would be nice to know what @MartiUK thinks about that change. Maybe there is a good reason to stay on the older versions.

**Comment by Stanzilla** [comment]
@strebl @dotnetCarpenter should probably wait until the new git for windows is final (it's release candidate now) but considering how busy @MartiUK currently is, it's not going to be merged anytime soon anyway.

**Comment by arcanedev-maroc** [comment]
Hi @Stanzilla, git for windows is released and most of tools are using it (Github desktop & Docker toolbox...).

**Comment by MartiUK** [comment]
@arcanedev-maroc We're already using it, see the development branch.

**Comment by arcanedev-maroc** [comment]
Tnx @MartiUK

I'm using cmder v1.2.9, so i don't know how to install the development branch (especially the vendors).
Is it stable enough to do crazy stuff ?? how to install/update the development branch ?

**Comment by MartiUK** [comment]
@arcanedev-maroc 1.2.9 has git-for-windows. You can find some builds on appveyor, see here https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.119-development/artifacts for example but don't expect them to be fully functional and they may have bugs

**Comment by arcanedev-maroc** [comment]
Great, tanks @MartiUK :+1:
