### ISSUE TITLE
Incorrect home folder in cygwin

### ISSUE THREAD

**Issue by trzecieu** [cmderdev/cmder#504]
Hi, 
This issue is related with `init.bat` file what sets %HOME% path.

Side effect is that, when I run cygwin session: `c:\cygwin\Cygwin.bat` or `c:\cygwin\bin\bash --login -i`
then user home folder is the same like in windows, what is wrong.

in init.bat we have:

``` bat
:: Set home path
@if not defined HOME set HOME=%USERPROFILE%
```

I commented out this line. 
What was the reason of adding it? 

Possible solutions:
- Always run cygwin using conemu task directive: `conemu /cmd {cygwin}`
- unset %HOME% in `Cygwin.bat` (or create own one)

**Comment by Jackbennett** [comment]
I don't know if HOME is required here but the powershell side doesn't define it and for users on a network roaming profile (me) userprofile is not the correct path to my actual files. You have to smush together `HOMEDRIVE` and `HOMEPATH`

**Comment by DRSDavidSoft** [comment]
@asRIA I had the same issue, then I realized that `%HOME%` should only be set to `%USERPROFILE%` when both of these conditions are met:

* `init.bat` should be called from the _user_'s account, not as a system.
* In _Enviroment Variables_, `%HOME%` should be set to `%USERPROFILE%` in the **User** variables. If it's set from **System** variables, then `%HOME%` will be set to the Windows directory.

Still, could you check if the recent changes to `init.bat` fix this problem?

**Comment by daxgames** [comment]
`init.bat`should not be running when starting `cygwin.bat` unless you are calling `cygwin.bat` from a Cmder session started by `init.bat`.  That being said I see no reason to set `%HOME%` to `%USERPROFILE%` other than to make the whole shell more Unix/Linux like.  However I am reluctant to change it since the feature has been this way for so long and there are plenty of workarounds for it.

Possible solutions:

* Unset it in the `user_profile.cmd`
* Always run cygwin using conemu task directive: conemu /cmd {cygwin}
* Unset %HOME% in Cygwin.bat (or create own one)

Won't fix.  Closing
