### ISSUE TITLE
(B showing when connected via ssh to linux server and running 'top'

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#514]
I love cmder, but one small annoyance is that LeftArrow(B shows up when looking at the top command on any linux server I'm sshd to in this console through plink.

![bshowing](https://cloud.githubusercontent.com/assets/3045164/7976146/78ab45d0-0a34-11e5-945a-0255323b76d0.png)

This seems to be plink specific but I wonder if cmder should be parsing these (B characters?

**Comment by MartiUK** [comment]
Cmder, (specifically ConEmu) is a windows terminal emulator, when you use putty it deals with the POSIX command sequences correctly because it's designed to be used to ssh into a POSIX system.

What I would suggest is, to save a configuration with all the correct settings in putty and load that like this:
```plink.exe -load $session -l $user_name -pw $password``` 
replacing the parameters as needed

**Comment by coreyman** [comment]
What do you mean 'save a configuration with all the correct settings' ? What settings should I be using?

**Comment by MartiUK** [comment]
@coreyman the defaults, if they work for you.
