### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by Muzical84** [cmderdev/cmder#579]
![capture2](https://cloud.githubusercontent.com/assets/775601/9070054/ceae33c6-3ab2-11e5-8268-160719ddc14f.PNG)

**Comment by Muzical84** [comment]
This is with the mini installer, the current "pre-release."

**Comment by krisdante** [comment]
Install https://www.microsoft.com/en-us/download/confirmation.aspx?id=46881 (VC Runtime). This solves the problem.

**Comment by bhaveshgohel** [comment]
@krisdante Getting 404!  - "We are sorry, the page you requested cannot be found!"

**Comment by Stefku** [comment]
I solved this problem with this article: https://www.smartftp.com/support/kb/the-program-cant-start-because-api-ms-win-crt-runtime-l1-1-0dll-is-missing-f2702.html

**Comment by bhaveshgohel** [comment]
Thanks @Stefku  :+1:

**Comment by Stanzilla** [comment]
If someone feels adventurous, you can test this https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

It should work without any DLLs as is.

**Comment by shunia** [comment]
@Stanzilla The DLL problem does not exist-by a installation of VC Runtime, or override with the v1.2.1 version,but I got another error-not caused by your forked v1.2.1,the original v1.2 has the same problem(The chinese character says "Join-Path : can not bind parameter to parameter(?) "Path", because the parameter has a null value") :
![image](https://cloud.githubusercontent.com/assets/779430/9768967/b9d2eb86-5759-11e5-93e0-133cfb044279.png)
