### ISSUE TITLE
ls parameters error in Windows 10

### ISSUE THREAD

**Issue by luisangelsm** [cmderdev/cmder#597]
I have installed 1.2 version in Windows 10. Now I am getting this error when I use parameters in ls

```
Get-ChildItem : A parameter cannot be found that matches parameter name 'al'.
At line:1 char:4
+ ls -al
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
``` 

Any ideas about what is going on?

**Comment by luisangelsm** [comment]
It seems that the path is not set properly and it is using the `ls` command from `PowerShell`.  I have changed the startup to `{cmd}` by now, but loosing (obviously) all the new PS prompt :(

**Comment by Jackbennett** [comment]
PS adds some aliases to its way of doing things so that nix and cmd people aren't punished outright for trying PS. 

As such `dir` and `ls` are just aliased to `get-childItem` which if I read from bash correctly; `-a, List all entries including those starting with a dot .` and `-l, Use a long listing format` powershell just does that all the time anyway.

You might find common nix commands aliased to powershell but using parameters is where that helpfulness breaks down. 

see: `get-alias`, even more info with `help alias`.

Either get used to some powershell, stick to cmd, or in your PS profile if you really want you can remove defined aliases like they're files mapped to the alias drive. `rm alias:\ls`. I think that will keep looking down your path for `ls`.

Just do `rm alias:\rm` last ;)

**Comment by Nabeel-Niaz** [comment]
Get-ChildItem : Parameter cannot be processed because the parameter name 'a' is ambiguous. Possible matches include: -Attributes 
-Directory -File -Hidden -ReadOnly -System.
At line:1 char:4
+ ls -a
+    ~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by Nabeel-Niaz** [comment]
Get-ChildItem : Parameter cannot be processed because the parameter name 'a' is ambiguous. Possible matches include: -Attributes 
-Directory -File -Hidden -ReadOnly -System.
At line:1 char:4
+ ls -a
+    ~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.GetChildItemCommand

I have this error what is the solution for this error.

**Comment by chrisant996** [comment]
@Nabeel-Niaz  The question is already answered here, and in the linked issue.

This is how PowerShell works.  If you don't want the cmdlets PowerShell defines by default, then you can either undefine them or use a different shell than PowerShell.  PowerShell is not Linux, nor bash, nor etc.
