### ISSUE TITLE
SFTP commands

### ISSUE THREAD

**Issue by marcelo2605** [cmderdev/cmder#670]
What I need to do to use SFTP commands (get, put, etc..) in cmder?

When I try, the following message appear: 'sftp' is not recognized as an internal command
or external , operable program or batch file.

Thanks folks!

**Comment by Centril** [comment]
`cmder` is a terminal emulator package that uses Conemu2 - as such, it can use any commands that the underlying terminal can use. So in order to use a command `sftp` you need to have it on your `PATH`.

An easy way to get `sftp` for windows is to install https://github.com/bmatzelle/gow which bundles puttys `psftp` program. If you need a GUI, there's always WinSCP.

**Comment by MartiUK** [comment]
Yep, make sure your sftp application is on your `PATH`.

**Comment by marcelo2605** [comment]
Thanks guy. Just a little help: I downloaded the gow files. So I need to put .exe files that I need in cmder/vendor folder and run it using init.bat?

**Comment by Stanzilla** [comment]
Please don't use Gow, it's outdated and breaks the Unix tools that come with Git for Windows

**Comment by Stanzilla** [comment]
sftp.exe comes with our package via Git for Windows so I guess your installation is broken, please get the latest pre-release.

**Comment by marcelo2605** [comment]
I download version 1.2.9 (I'm using 1.1.4.1) and now I can use SFTP. Thanks!

**Comment by Centril** [comment]
@Stanzilla Regarding `Gow` vs `/usr/bin` of Git for windows: Gow has the benefit that it doesn't use mingw or cygwin which is very nice. Calling `which` gives you for example the correct windows path instead of `/usr/bin/which` when you call `which which`.

Also, it includes niceties such as `nano` for us that detest `vim` with burning passion.

The downside is of course that it hasn't been updated since April, but these utilities are hardly so critical to update since they've been around for so long.
