### ISSUE TITLE
Use tab to cycle through auto complete, like the original cmd does?

### ISSUE THREAD

**Issue by dofine** [cmderdev/cmder#681]
Cmder is great, but I'm missing one feature of the original cmd in Windows.
Use <tab> to cycle through all auto complete candidates, not just list them below.
Could that be achieved?

**Comment by Nidre** [comment]
+1 that!

**Comment by Jackbennett** [comment]
This is a clink thing that's injected into CMD.

If you use the powershell console, tab behaves like you want.
If you want to also see a list use `ctrl + space` and you will get a table of candidates. You can use the arrow keys to pick a candidate in the table as well as just type it in.

That auto-complete table feature is because of PSReadLine.
