### ISSUE TITLE
Win + Alt + P does not bring up Cmder settings

### ISSUE THREAD

**Issue by DanielGGordon** [cmderdev/cmder#730]
`Win + Alt + P` does not bring up the setting menu when using the Mintty Task. It works with all other tasks.

I don't know if this is something that can be changed, as I think Mintty grabs the command before it can reach Cmder/Conemu.

This issue was found on the current development branch.

This also means that other Conemu/Cmder commands do not work as well. For example `ctrl + w` does not close the current tab.

**Comment by daxgames** [comment]
This is probably one of the normal differences when using Mintty vs the Windows Console API.  These differences are briefly called out in the development branch README.md.  I doubt it will be addressed.

I personally like that Ctrl+W does not close a tab when using mintty because Ctrl+W in vim is how you access vim splits/panes.

**Comment by DanielGGordon** [comment]
Is there a way to un-map some of these commands from Mintty? Maybe it wouldn't be part of the Cmder build, but it would be nice to know how to do. I think `Win + Alt + P` would be a good one to not have go to Mintty. All it does is put `^[p` in your terminal.

**Comment by daxgames** [comment]
I don't know.  I'd say the best solution is to not use the mintty tasks and stick with the others if Cider/ConEmu key bindings are important to you.
