### ISSUE TITLE
Unable to install cmder using Install-Package in Windows 10

### ISSUE THREAD

**Issue by russellseymour** [cmderdev/cmder#762]
Hello,

I have setup Chocolatey as a trusted source in Windows 10 and am attempting to install cmder using ```Install-Package cmder.portable```.  The package is found and it is downloaded but it fails to install with the following error.

![cmder_install_failure](https://cloud.githubusercontent.com/assets/791658/11697044/9a34dde6-9eaf-11e5-83bf-3452d609eaf0.PNG)

I have tried this with elevated permissions as well and I get the same error.

Any help on how to get this installed using this method would be very much appreciated.

**Comment by russellseymour** [comment]
I apologise, I have put this on the wrong issues board as I know you do not maintain the chocolatey package.  Will close the issue.

**Comment by MartiUK** [comment]
Thanks, you're the first to recognise that :+1:

**Comment by DRSDavidSoft** [comment]
For future visitors: this older Chocolatey support thread explains why package-manager questions were often redirected away from this repo.

Chocolatey packages for Cmder and cmdermini exist, but they are community-maintained rather than owned by `cmderdev`. The current coordination point is:

Master package-manager tracker: https://github.com/cmderdev/cmder/issues/3094
Wiki status page: https://github.com/cmderdev/cmder/wiki/Package-Manager-Status
