### ISSUE TITLE
Cmder v1.2.9 hangs then crashes when using SSH randomly

### ISSUE THREAD

**Issue by predatorian3** [cmderdev/cmder#783]
I'm using Windows 7 Ent. Edition and have the program registered so I can use the right click 'Open Cmder Here' function. Sometimes while using SSH, the tab will crash on me, and close. This seems to be on the cmd tabs, I haven't tried on PowerShell, and using Cygwin in Cmder works just fine.

**Comment by ittayd** [comment]
This is happening to me as well, doing ssh under PowerShell. For me it seems to happen when I do 'vi' or 'less' in the remote console (on small text files). 
It just started recently when I switched to a newer laptop, running Windows 7. 
Since I do a lot of ssh, this is very annoying. Would appreciate any tips
