### ISSUE TITLE
how to add the environment variable to the cmder?

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#792]
![82](https://cloud.githubusercontent.com/assets/11295355/12191498/a2a81a10-b610-11e5-9a44-6391de644d05.png)

Just like it shows in the picture, left is the `cmder` , and right is my `windows cmd`
two questions here: 
1. I already add the `mysql` path to the environment in the environment why cmder still can't find it?
2. every time I start the cmder it shows that `mysql is not a internal or external command` why's that ?

**Comment by MartiUK** [comment]
Try adding double quotes `"` before and after mysql in path.

**Comment by woshichuanqilz** [comment]
![82](https://cloud.githubusercontent.com/assets/11295355/12213322/09d6c826-b6b1-11e5-87e4-f741a9abf106.png)
you mean like this? It worked, but I can't type the whole path every time.
![82](https://cloud.githubusercontent.com/assets/11295355/12213334/41bd89c8-b6b1-11e5-8df3-31b39aee7eca.png)
And the path is already added in the environment variable.

**Comment by JanSchulz** [comment]
I use this in config/user-startup.cmd (needs the changes in the development branch -> see the appveyor artifacts)

```
:: add my own scripts
@set "PATH=%PATH%;%CMDER_ROOT%\vendor\heimdall"
@set "PATH=%PATH%;C:\portabel\sdk\platform-tools"

:: add unix commands from existing git -> last to get the right gpg from above and not from git...
@set "PATH=%PATH%;%GIT_INSTALL_ROOT%\usr\bin\"
```

But this shouldn't be needed if msql is included in the path (-> if it is useable in a plain cmd, it should be useable in cmd, as we only add to the path).

Can you give the output of `path` in both cmd and cmder? 

In your case something more seems to be broken as `{lamb}` and `{git}` is not replaced with the right values.

**Comment by woshichuanqilz** [comment]
Tnx a lot for your help, the problem is solved.

**Comment by JanSchulz** [comment]
Close?

**Comment by woshichuanqilz** [comment]
tnx

**Comment by BWBuchanan7** [comment]
I seemed to be having this same problem and on looking further into is the issue may be on Cmder's end:

![2016_03_08_21_35_54_cmder](https://cloud.githubusercontent.com/assets/9372264/13625528/e6b5e6a8-e575-11e5-8923-c1332bd6e4a1.png)

I realized that my %PATH% was being cut short in Cmder:
![2016-03-08 21_47_42-cmder](https://cloud.githubusercontent.com/assets/9372264/13625689/78925880-e577-11e5-8d21-fcf19845a761.png)

It would appear that a default MySQL installation adds this to %PATH%: 

`C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 **&** MySQL Utilities 1.5\Doctrine extensions for PHP\;`

Any and all characters following that ampersand are then ignored by Cmder for some reason. This effectively was ignoring a large amount of my %PATH% as MySQL sat about halfway through the list of the various directories inside %PATH%.

There may be need to 'escape' the ampersand so that %PATH% doesn't get incorrectly cut short.

For the time being I have removed MySQL from my %PATH% and Cmder is working as expected, however in the long term I wonder if there is a better solution for this?

**Comment by PhillipMwaniki** [comment]
This issue is resolved once you remove the auto inserted MySQL paths from the system variables path. Nodejs wasn't working for me but now is. Does anyone know how to start up using a command e.g.
 `cmder .` 
to open _cmder_ in a particular folder without right clicking. I'm using [listary ](http://www.listary.com/)and I think this would be helpful

**Comment by jtcotton63** [comment]
I've got the same problem, except that it's for java.exe.

Java is installed in the default location: C:\Program Files\Java\jdk-10.0.2.

As part of the installation, I defined the following new variable:

`JAVA_HOME=C:\Program Files\Java\jdk-10.0.2`

I then added this to the path variable, like so:

`%JAVA_HOME%\bin`

I tested it by running `where java` from cmd.exe. I get the following:

`C:\Program Files\Java\jdk10.0.2\bin\java.exe`

But when I run `where java` from cmder, I get the following:

`INFO: Could not find files for the given pattern(s).`

**Comment by dav0** [comment]
I was able to get JAVA_HOME working for Cmder by using the old PROGRA~1 trick to work around the issues caused by the silly space character in "Program Files".

Try placing the following into your user_profile.cmd:

@set JAVA_HOME=C:\PROGRA~1\Java\jdk1.8.0_152
@set PATH=%JAVA_HOME%\bin;%PATH%
