### ISSUE TITLE
Emacs keyboard shortcuts do not work

### ISSUE THREAD

**Issue by scarolan** [cmderdev/cmder#827]
I have this in my $PROFILE settings:

```
# Set Emacs-like prompt navigation
Set-PSReadlineOption -EditMode Emacs
```

But when I use CTRL-A and CTRL-E to move around, it just outputs literal ^A and ^E characters

Plain ConEMU does not exhibit this behavior.  So there is something unique to cmder that is making it happen.

**Comment by MartiUK** [comment]
This is somewhat fixed by the addition of cmder user profiles in the current dev branch, although my concern here is that $Profile is pretty much ignored.

I think a change is required to dot-source $profile at some point in vendor/profile.ps1 although more issues may arise. posh-git already sources an example profile on install which will definitely break the default cmder prompt.

For now since (I assume) you're using 1.2.9 you can add that to vendor/profile.ps1 or (not recommended) dot source $profile on startup.

**Comment by gaving** [comment]
Seems to work fine here after:-

`Set-PSReadlineOption -EditMode Emacs`

In Cmder 161022

**Comment by Jackbennett** [comment]
Could certainly document this better but;

The .ps1 files in `"$ENV:CMDER_ROOT\config\profile.d"` will be dot sourced into your session each powershell process start. [Code](https://github.com/cmderdev/cmder/blob/9d6e5c12a2fb7f0fcd6b5eaa42100605c3314895/vendor/profile.ps1#L127) and the [next bit](https://github.com/cmderdev/cmder/blob/9d6e5c12a2fb7f0fcd6b5eaa42100605c3314895/vendor/profile.ps1#L134).

`"$env:CMDER_ROOT\config\user-profile.ps1"` is created upon launch, which contains hooks to modify the prompt. Otherwise everything else still loads just like you'd expect. [template creation](https://github.com/cmderdev/cmder/blob/9d6e5c12a2fb7f0fcd6b5eaa42100605c3314895/vendor/profile.ps1#L150)

# Fix

I think `$CmderUserProfilePath` should be leaked out of our profile script which would allow you to append to the end of it. 

``` powershell
"Set-PSReadlineOption -EditMode Emacs" | out-file $CmderUserProfilePath -append
```
There may be an encoding issue. I find PS funny when writing files. Just fix it in a text editor in that case.

## Reasoning
Cmder, being portable, didn't seem right to inherit user's profile settings. (I'm making a further assumption that many users, the first thing they might do is customize their own prompt. Then we'd start to clash).  

But that's a choice made long before all the above customization was added.
