### ISSUE TITLE
"-ExecutionPolicy' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by mindstormer12** [cmderdev/cmder#830]
Running PowerShell as Admin gives the error:

>'-ExecutionPolicy' is not recognized as an internal or external command, operable program or batch file.

I did not modify anything significant in the settings.

**Comment by dcolliervb23** [comment]
What was the solution for this? I am getting this now for running Powershell as Admin, whether its at startup or creating a new tab

**Comment by dcolliervb23** [comment]
But running Powershell regularly (not as admin) works just fine

**Comment by michael-wise** [comment]
I just started using Cmder. I was getting the same error. Turns out while I was tinkering with settings, I didn't realize the Settings->Startup->Task->Group3->Add: Tab...Startup dir...etc... buttons at the button inserted the new config text wherever the text cursor was.
That is, I had an extra `-new_console:d:C:\sites*` at the beginning:
`-new_console:d:C:\sites*PowerShell -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''" -new_console:d:"%USERPROFILE%"`
Changing back to:
`PowerShell -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''" -new_console:d:"%USERPROFILE%"`
