### ISSUE TITLE
cannot use Caret with Git

### ISSUE THREAD

**Issue by okoetter** [cmderdev/cmder#840]
If I have a git command ending with ^ like `git rebase abcdef^` the command is not executed but on the next line I get a "Mehr?", that's German for "More?".

**Comment by MartiUK** [comment]
Try running it with two carets: `^^`

http://www.psteiner.com/2008/12/using-caret-in-windows-batch-files.html

or use Powershell!

**Comment by okoetter** [comment]
ok, thanks. But this worked before I updated my older version some days ago... :-)

**Comment by kenny-reyes** [comment]
Closed, really? it still not working it's only a bad workaround

**Comment by chrisant996** [comment]
This is how CMD works.  If it was "working" at some point, then it was probably due to some _bug_ in Clink, which got fixed.

You can confirm easily:

1. <kbd>Windows</kbd>+<kbd>R</kbd> to show the Run dialog.
2. Type `cmd` and press <kbd>Enter</kbd>.
3. Type `echo one two^` and press <kbd>Enter</kbd>.

CMD is designed to prompt `More?` when the input ends with `^`; it's just how CMD works.

**Comment by kenny-reyes** [comment]
I still think there is some bug. There are some weird behaviors. For example with the whitespace.
![problem](https://user-images.githubusercontent.com/11137579/112472453-6deafb00-8d6d-11eb-84d8-09b689797cb3.gif)

**Comment by chrisant996** [comment]
Can you clarify specifically which actions in the video you feel illustrate a bug?
Everything looks how I would expect.

Maybe it isn't clear what `^` does.
The `^` is the CMD escape character.  It's similar to `\` in bash.
Typing `git checkout HEAD^  here` is the same as `git checkout HEAD here`.
Typing `git checkout HEAD^2 here` is the same as `git checkout HEAD2 here`.
Typing `git checkout HEAD^here` is the same as `git checkout HEADhere`.
Typing `git checkout HEAD^^` escapes the escape character, so that the command line ends up as `git checkout HEAD^`.
Typing `git checkout HEAD^` ends with an escape character, which is incomplete input -- because it is incomplete input, CMD prompts `More?` asking for the input to be finished.

**Comment by kenny-reyes** [comment]
Sorry, I thought I was clear enough.

if you type caret `'^'` and `' '` whitespace (spacebar) in notepad, cmd, git bash, power shell, VSCode, etc.... you will have `'^'` (simple caret). 
If you do the same in **cmder** you will have nothing (not simple caret).

It's possible it is happening only on my machine because It's weird nobody more reported previously, (it's very annoying can't type simple caret). I will install **cmder** in all my computers to testing that and write again later.
