### ISSUE TITLE
Remove `Cmder.bat` from repository?

### ISSUE THREAD

**Issue by Maximus5** [cmderdev/cmder#857]
I think `Cmder.bat` is obsolete and have to be removed. I do not see any reason for it's existence, if user clones the repo, the batch would not work because of vendor's products are not unpacked properly.

There is `Cmder.exe` instead.

Or, at least `Cmder.bat` must be fixed

``` diff
diff --git a/Cmder.bat b/Cmder.bat
index 4ae276a..bd77acc 100644
--- a/Cmder.bat
+++ b/Cmder.bat
@@ -1,3 +1,3 @@
 @echo off
 SET CMDER_ROOT=%~dp0
-start %~dp0/vendor/conemu-maximus5/ConEmu.exe /Icon "%CMDER_ROOT%\icons\cmder.ico" /Title Cmder /LoadCfgFile "%CMDER_ROOT%\config\ConEmu.xml"
+start "cmder" "%~dp0/vendor/conemu-maximus5/ConEmu.exe" /Icon "%CMDER_ROOT%\icons\cmder.ico" /Title Cmder /LoadCfgFile "%CMDER_ROOT%\config\ConEmu.xml"
```

**Comment by daxgames** [comment]
I actually prefer cmder.bat because I can change and use it daily when I run and develop cmder. Because I do not have the tools to build Cmder.exe.

I have a modified version that accepts command linebarguments that allow me to load different come my.xml files.

I think it should stay in the repo as a dev tool, it is already excluded from the binary distro.
