### ISSUE TITLE
Babun not captured.

### ISSUE THREAD

**Issue by sigmap** [cmderdev/cmder#907]
When I try to run Babun through cmder it always launches mintty as a separate terminal window. I followed the guide from the wiki to the letter. I've looked it up on the conemu github page and not found anything there that works. From one of the screencaps on the page about intergrating babun with cmder there was a task for babun without mintty. Any chance that could be added to the wiki?

**Comment by daxgames** [comment]
With mintty: E:\tools\.babun\cygwin\bin\mintty.exe -

or 

without mintty: e:\tools\.babun\cygwin\bin\zsh.exe -l

**Comment by sigmap** [comment]
Thanks a ton, this does help to run without mintty. However I noticed a black '%' on a white background above my prompt. Does that happen for you?
![What I mean](https://i.imgur.com/og6vKqx.png)

**Comment by daxgames** [comment]
Nope.

**Comment by floydpink** [comment]
@sigmap - I am also getting the stray `%` characters both above and after the prompt (and the one after the prompt seems to appear only for certain themes).

Have you managed to figure out where to fix it?

**Comment by floydpink** [comment]
[This answer on ServerFault](http://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows/645612#645612) was helpful for me to fix the issue of stray `%` characters.

Just add this to your `.zshrc`:

```shell
unsetopt PROMPT_SP
```

**Comment by daxgames** [comment]
I am also using the 'cmder_exinit' component in Cmder with Babun to allow Babun to use the init scripts defined in $CMDER_ROOT/config.  Maybe why I am not getting it?

**Comment by floydpink** [comment]
Probably - I tried looking into using cmder_exinit without much success. I was not able to get SSH-Agent to load my SSH keys using that approach.

Also, this `%` character was [an issue](https://github.com/babun/babun/issues/321) that Babun had fixed by [adding](https://github.com/babun/babun/commit/8a61c3a71ac8ff2e2b0dc8f3e3586aa7c37b2d16) an `unsetopt promptcr` a while ago. So it could be the way we're not loading [the right files](https://github.com/babun/babun/commit/8a61c3a71ac8ff2e2b0dc8f3e3586aa7c37b2d16#commitcomment-13258909) with our cmder configuration.

**Comment by sigmap** [comment]
I'm assuming we'll see that in the future release of [1.3.0](https://github.com/babun/babun/issues/393)
