### ISSUE TITLE
chocolatey.lua:1: module 'tables' not found

### ISSUE THREAD

**Issue by borekb** [cmderdev/cmder#957]
With Cmder 1.3.0-Pre, this happens to me every time I start cmder on my main PC:

```
...lePrograms\cmder/vendor/clink-completions/chocolatey.lua:1: module 'tables' not found:
        no field package.preload['tables']
        no file 'C:\WINDOWS\SYSTEM32\lua\tables.lua'
        no file 'C:\WINDOWS\SYSTEM32\lua\tables\init.lua'
        no file 'C:\WINDOWS\SYSTEM32\tables.lua'
        no file 'C:\WINDOWS\SYSTEM32\tables\init.lua'
        no file '.\tables.lua'
        no file 'C:\WINDOWS\SYSTEM32\tables.dll'
        no file 'C:\WINDOWS\SYSTEM32\loadall.dll'
        no file '.\tables.dll'
```

Everything works fine then but I see this message every time. What is strange is that I have the whole cmder installation synced via OneDrive and on my laptop, there's no such message – all works as expected. I find it really strange to be honest but it would be nice to be able to get rid of this error.

**Comment by MartiUK** [comment]
@vladimir-kotikov

**Comment by vladimir-kotikov** [comment]
@borekb, I could you please elaborate? You're seeing the error message when running Cmder from Onedrive directory? Or you see this on some particular machine and do not see it on other?

**Comment by borekb** [comment]
@vladimir-kotikov The latter – I always start cmder from the same location on all machines but the error is produced on one machine only.

**Comment by rossinimartins** [comment]
@borekb @vladimir-kotikov @Stanzilla was this issue fixed? This is also happening with me, on version 1.3.3.

**Comment by rossinimartins** [comment]
Update: downloading the content of the master of [vladimir-kotikov/clink-completions](https://github.com/vladimir-kotikov/clink-completions) repository into `vendor\clink-completions` directory seems to solve the problem.

**Comment by Stanzilla** [comment]
1.3.3 comes with the latest release which is the same as master though, did you maybe have old files left over that got loaded?

**Comment by rossinimartins** [comment]
This is weird because I only downloaded the 1.3.3 full version zip from the site, put it on a new synced directory (I'm using Mega, not OneDrive like the OP) and then run it on another computer. Maybe the files are not synced? But why? Maybe the full version zip in the site is not updated?

**Comment by Stanzilla** [comment]
The site only links to GitHub but you can just use the releases page to make sure https://github.com/cmderdev/cmder/releases

**Comment by rossinimartins** [comment]
Ok, today I got access to another computer that also have this synced folder and the problem still there, even I already fixed it on my home computer. I guess this means that is a problem in the sync tool, or in the Windows API that the sync tools are using (since it happens in Mega *and* OneDrive), not in the cmder.

**Comment by DannyFeliz** [comment]
I still having this problem

**Comment by samirergaibi** [comment]
> Update: downloading the content of the master of [vladimir-kotikov/clink-completions](https://github.com/vladimir-kotikov/clink-completions) repository into `vendor\clink-completions` directory seems to solve the problem.

Worked for me, thank you for the solution.

**Comment by DDorch** [comment]
I confirm that the problem comes from the sync tool. I've Cmder installed on a synced folder with OwnCloud and I face the same issue. OwnCloud is configured to not sync linux hidden files and folder (beginning with a dot) and some usefull files in `clink-completions` folder are ignored by the sync:

- Apps/PortableApps/cmder/vendor/clink-completions/.luacov
- Apps/PortableApps/cmder/vendor/clink-completions/.luacheckrc
- Apps/PortableApps/cmder/vendor/clink-completions/.init.lua
- Apps/PortableApps/cmder/vendor/clink-completions/.gitignore
- Apps/PortableApps/cmder/vendor/clink-completions/.busted
- Apps/PortableApps/cmder/vendor/clink-completions/.appveyor.yml
- Apps/PortableApps/cmder/vendor/clink-completions/.vscode

**Comment by vladimir-kotikov** [comment]
While most of the files you mentioned shouldn't affect how the code is loaded into cmder, I believe there's one which is a problem. Basically `.init.lua` is the root cause here as it modifies modules path so other modules can be loaded and I believe it just needs to be renamed into something else to not start with the dot (perhaps underscore should work, it just needs to be a symbol that goes before other ASCII symbols so that this module gets executed first by Clink)
