### ISSUE TITLE
Update version on Chocolatey

### ISSUE THREAD

**Issue by corydeppen** [cmderdev/cmder#959]
I was wondering if there is anyone actively working on updating the versions of cmder on Chocolatey.

The current version that's available on Chocolatey (1.1.4.1) has an updater that is now broken with the following error because the conemu repository has moved.

```console
---------------------------
ConEmu 140707 [32]
---------------------------
Version update information is broken (not found)
[ConEmu_Stable_2] "version"

http://conemu-maximus5.googlecode.com/
svn/trunk/ConEmu/version.ini

Error code=2
---------------------------
OK
---------------------------
```

**Comment by MartiUK** [comment]
We have not and will not support the version in chocolatey.

**Comment by artisticcheese** [comment]
Please use chocolatey for distribution. Big number of Windows admins are about to endavour of WMF5 package management which will eventually lead them to Chocolatey repo.

**Comment by corydeppen** [comment]
Yeah, I'm a bit curious why there's an aversion to updating cmder on Chocolatey. A "...have not and will not support..." stance seems to be an odd choice given the benefits Chocolatey offers and the community support behind it. Would be helpful to understand the reasoning behind the decision.

**Comment by daxgames** [comment]
There is no need to use Choclatey to install cmder, there is no install process.  Download, unzip, done!

Just my $.02.

**Comment by artisticcheese** [comment]
There is a need for chocolatey for bunch of scenarios, one of them is automation. For example if you use Chef there is chocolatey cookbook which will allow you to specify list of software you want your servers to have installed and keep updated.

**Comment by janschulz** [comment]
As far as I can see choco devs for cmder are not the same as the devs for cmder itself, so I think it's easiest to ask the choco devs to build new package instead of here. 

And thats possible happening here: https://chocolatey.org/packages/Cmder/1.3.0-beta

**Comment by Jackbennett** [comment]
You should be using PS Remoting for your servers not using remote desktop with cmder on there.

**Comment by MartiUK** [comment]
It’s up to the package maintainer to package it for chocolatey, not us.

--
Martin

**Comment by dtgm** [comment]
@MartiUK sorry about all the confusion. I'm not sure why folks think you are the maintainer of the chocolatey package. The [maintainer](https://chocolatey.org/packages/cmder#maintainers) and [software authors](https://chocolatey.org/packages/cmder#authors) are clearly listed separately 

To clarify to anyone who may still come across this. The chocolatey package is community driven package that is not affiliated with this project. Currently, the chocolatey package simply downloads the associated zipped file as released from cmderdev/cmder repository and extracts to whatever `$env:ChocolateyToolsLocation` is set to (if the variable does not exist or is empty, it defaults to `C:\tools`). It then adds the location to the path.

**If anyone has an issue with the chocolatey package, please use the [Contact Maintainers](https://chocolatey.org/packages/cmder) as listed alongside the package.**

The package gets automatically built whenever a new version is detected from the URL https://github.com/cmderdev/cmder/releases/latest (currently 1.1.4.1)

Pre-release versions are required to be built manually. See the "Package Source" link also listed alongside the package for contributing. You must also pass `--prerelease` option when installing or only the latest stable version will install, since packages marked --prerelease are exempt from moderation.

**Comment by janschulz** [comment]
@dtgm:

> The package gets automatically built whenever a new version is detected from the URL https://github.com/cmderdev/cmder/releases/latest (currently 1.1.4.1)

Do you have a pointer to the script which does this? I'm curious and have a use case in conda-forge for it :-)

**Comment by dtgm** [comment]
@janschulz Yup, the package source files are all in my repo including the auto-updating routines. The relevant file is https://github.com/dtgm/chocolatey-packages/blob/master/ketarin/cmder.xml You can see the regex I'm using in that file to scrape the page for the relevant file and extract the version. Also grab the MD5 from GitHub. You can either use the relevant bits of the XML in another program or load it into ketarin (GPLv2). There are some other bits that do the actual building of the nupkg.

**Comment by DRSDavidSoft** [comment]
For future visitors: the Chocolatey ownership and status work is now tracked in the master package-manager issue and wiki.

Cmder and cmdermini packages exist on Chocolatey, but they are still community-maintained rather than owned by `cmderdev`. The package pages currently point to [`automatic/cmder`](https://github.com/AdmiringWorm/chocolatey-packages/tree/master/automatic/cmder) and [`automatic/cmdermini`](https://github.com/AdmiringWorm/chocolatey-packages/tree/master/automatic/cmdermini), with [`AdmiringWorm`](https://github.com/AdmiringWorm) and [`dtgm`](https://github.com/dtgm) listed as owners.

The proposed path is to ask the current maintainers to add Cmder core maintainers or coordinate ownership. Chocolatey's vendor guidance says to contact current maintainers first, then contact Chocolatey site admins with the contact record if the package owners do not respond after the guidance waiting period.

Master package-manager tracker: https://github.com/cmderdev/cmder/issues/3094
Wiki status page: https://github.com/cmderdev/cmder/wiki/Package-Manager-Status
